### ISSUE TITLE
Only when playing on server: crash when autocrafting

### ISSUE THREAD

**Issue by condensedapple** [p455w0rd/WirelessCraftingTerminal#10]
I put WCT on my server, and inserting/extracting itmes works, but if I want to autocraft something (e.g. clicking on an item to craft it), the client crashes to title screen, and the following error appears in the server console, but the server does not crash.
http://85.214.16.155:81/randomstuff/autocrafting-crash.txt
In SP everything worked as expected, in all versions of WCT.

**Comment by p455w0rd** [comment]
found where the bug is..i'll get a fix out asap
