### ISSUE TITLE
Infinity Booster Card don't work with auto-crafting

### ISSUE THREAD

**Issue by jk1895** [p455w0rd/WirelessCraftingTerminal#100]
Hello,
I don't know if this is working like intended or a bug. But when I try to autocraft something and I'm out of range of the wireless transmitter then the crafting CPU-GUI don't show up although I have the infinity booster card installed.
Hope you understand what I mean.
My wireless transmitter has zero booster cards in it. When I go more than 16 blocks away from it I have still access to my storage because of the infinity card but when I try to craft an item it don't work. I can set the amount and try to click on the start button but nothing happens. When I move in range and do the same again it's working.

Forge: 12.18.3.2219
WCT: 1.10.2-0.0.7
Java 1.8.0_25 64 bit
Lots of another mods installed. 

Thank you.

**Comment by vohan1212** [comment]
I found that I could autocraft while in range of the wireless access point. But while outside the range of it you could not.

**Comment by jk1895** [comment]
WOW O.O That was fast!
Thank you very much!
Keep up the good work.
Thank you again.

**Comment by jk1895** [comment]
Yes, I downloaded the new version via curse and tested it. Works like I thought it should working :-)
Thank you!
