### ISSUE TITLE
Two small bugs found

### ISSUE THREAD

**Issue by jk1895** [p455w0rd/WirelessCraftingTerminal#101]
Hello,
me again. I found two small bugs (1st very hard to describe with my poor English knowledge):
1. When I search something that I want to autocraft - than I craft it - the entry is cleared and I have to type it again to grab my auto-crafted stuff. The AE2 GUI keeps the entry so I can just wait till it is finished and grab it.

2. When I want to craft something in the crafting frame (not autocraft) with a hammer or infusion stone - I shift click for a stack than I get only one item because the tool which is needed goes into my inventory. I have to put it back 63 times to get one stack.

Hope you understand. :-)

Greetings

**Comment by p455w0rd** [comment]
i'll look into both of these issues when I have time. I marked this as enhancement because I will probably add a button to toggle whether or not the search box retains its memory
