### ISSUE TITLE
[1.10.2] Wireless booster

### ISSUE THREAD

**Issue by YOYOK9** [p455w0rd/WirelessCraftingTerminal#105]
Something I've noticed is sometimes when you are crafting the wireless booster upgrade will move from its slot to either the player's inventory, or the crafting terminal slots. or even just drop on the ground without clicking on it/moving it. Which kinda kills the "away from base" crafting.

**Comment by p455w0rd** [comment]
it doesn't do this with only required mods installed. Moue tweaks did this in 1.7.10. Do you have mouse tweaks installed? Inventory tweaks?

**Comment by YOYOK9** [comment]
Yes to both. 
Mouse: 2.6.4-mc1.10.2
inv: 1.6.2-dev-64

**Comment by p455w0rd** [comment]
yeah..out of my control..it's mousetweaks messing with stuff

**Comment by p455w0rd** [comment]
i mean i'll look into it and see if I can figure omething out

**Comment by p455w0rd** [comment]
ok..so they've finally implemented a way of disabling MT on a per-slot basis, but it's only in 1.11. So for now, I'll just disable MT completely for WCT..this sucks, but it's the only option available for 1.10.2

**Comment by p455w0rd** [comment]
https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2383890 - should be fixed ..let me know if not :)

**Comment by YOYOK9** [comment]
Seems to be fixed. I will let you know if anything comes up. Thank you for your fast help! :D
