### ISSUE TITLE
Wireless Crafting Terminal Doesnt Work.

### ISSUE THREAD

**Issue by Ruthless-One** [p455w0rd/WirelessCraftingTerminal#106]
I hold shift and cycle thru everything, but after essentia and i shift and click again its back to the top in items, i dont see any "crafting" section. It is charged and linked. I had to use creative to get this, cause when i try to craft thru the crafting recipe, it does not have a "crafting" part installed.  Is there something i need to do? the "enable wireless crafting terminal" is set to true in the config.

**Comment by p455w0rd** [comment]
This would be an issue with ExtraCells, not Wireless Crafting Terminal. Also, I no longer support the 1.7.10 version of WCT anyway as clearly stated on the project page.
