### ISSUE TITLE
Trash slot not working

### ISSUE THREAD

**Issue by wasweb** [p455w0rd/WirelessCraftingTerminal#107]
When something is placed into the trash slot then clicked on empty, it doesn't actually delete the stack. You can click on the slot again and pull out the stack you put in.

**Comment by p455w0rd** [comment]
will look into this

**Comment by p455w0rd** [comment]
it actually doesnt delete until the terminal is closed..this is pretty minor, but a bug nonetheless..will fix :)

**Comment by donbubu** [comment]
hi,
first, a big thanks for this mod, a really nice work.

but i have the same problem with the WirelessCraftingTerminal-1.10.2-2.1.49 from Mar 6, 2018

Is there another version ?
thanks :)
