### ISSUE TITLE
Ability to close the terminal with the same button

### ISSUE THREAD

**Issue by wasweb** [p455w0rd/WirelessCraftingTerminal#108]
Terminal can only be opened with the binded key. It would be useful to toogle with the same button, like the player inventory (E).

**Comment by p455w0rd** [comment]
i agree! will implement :)

**Comment by p455w0rd** [comment]
![close keybind functionality](https://puu.sh/ufzxl/924db4f4a9.gif) - in this gif what you are seeing is me binding to the "C" key..i then press "C" to open and "Ctrl+C" to close..you have to have a modifier (Ctrl key) due to the text box..so this will be in next update :) good idea!

**Comment by wasweb** [comment]
hmm.. i usually don't use the auto search box, can you make it so it is configurable to use Ctrl or not for closing

**Comment by p455w0rd** [comment]
no
