### ISSUE TITLE
Keybinding, chat text with magnet cards

### ISSUE THREAD

**Issue by Leonyx1175** [p455w0rd/WirelessCraftingTerminal#109]
The keybinding for changing modes on the magnet card doesn't seem to work anymore with v. 0.0.12. Also, I'm not sure if it's implemented yet, but it'd be nice to see the chat text when changing magnet card modes (like in 1.7.10) as well. Lemme know if there's any other information you need from me.

**Comment by p455w0rd** [comment]
I literally just tested this before i pushed lol..worked perfectly..just got home..i'll look into it..SSP or SMP? cuz I was testing in SMP..

**Comment by Leonyx1175** [comment]
SMP, I tried changing my keybinding as well, to no avail.

**Comment by p455w0rd** [comment]
ok..i'm looking into it now..for sure another update within the coming hours..I'm hoping to clear this issue tracker :) thanks for letting me know

**Comment by Leonyx1175** [comment]
Sure thing, happy to help out however I can. Could I throw another enhancement in there too? It'd be nice if the searchbar persisted through auto-crafting, don't know how hard it'd be to implement though.

**Comment by p455w0rd** [comment]
#101

**Comment by p455w0rd** [comment]
[Magnet Working as Intended](https://puu.sh/ufwGZ/8fb8fa92e1.gif) - this is SMP..working as intended

**Comment by Leonyx1175** [comment]
Interesting,.. maybe it's a conflict with SF (I know, you don't support it). Thanks for looking into it.

**Comment by p455w0rd** [comment]
if you could check for me that you experience this without spongeforge, then there is definitely a bug somewhere..let me know if anything becomes of this

**Comment by Leonyx1175** [comment]
Tested without SF in SSP, magnet card works perfectly.

**Comment by p455w0rd** [comment]
just so u know, you can still use it, you'd just have to take it out and manually change it...I have no clue how to go about making my code compatible with SF or I would

**Comment by Leonyx1175** [comment]
Yeah, it's still usable, just inconvenient. If I could find a mod that applied effects to a player that dies (our server has keepInventory on), I'd probably swap over to ThutPerms/Essentials and just drop SF altogether.
