### ISSUE TITLE
[1.10.2] Unable to use terminal

### ISSUE THREAD

**Issue by YOYOK9** [p455w0rd/WirelessCraftingTerminal#111]
When we try to open the terminal console spits out an error and the terminal will not open. Have tried re-linking it to the ae2 system and even recrafting a new one. Still doesn't work. 

Console: http://pastebin.com/wPTtHVzP
Forge: 1.10.2-12.18.3.2234
WCT: 1.10.2-0.0.13

**Comment by p455w0rd** [comment]
Thanks for the report. Would it be possible for you to join my discord at https://discord.gg/9J7yhUP ? I'm going to do a build and test, but I'd like to have you test as well before I push to Curse.

**Comment by YOYOK9** [comment]
Yeah for sure. I have connected
