### ISSUE TITLE
Infinite power drain in ftb beyond

### ISSUE THREAD

**Issue by pennyvise1** [p455w0rd/WirelessCraftingTerminal#113]
Using a Flux Networks controller set to transmit mode (wireless charging) with the wireless crafting terminal in inventory will drain the RF storage at 100% of the rate set.  If you have the controller set to ignore limit you can empty a draconic energy core in 1 tick.

**Comment by p455w0rd** [comment]
can you tell me if it does this with the AE wireless term?

**Comment by pennyvise1** [comment]
Hrm, yeah it does with the regular one too, hadn't thought to try that.  Ill post this over on their github. Thanks for the quick response

**Comment by p455w0rd** [comment]
no..this is a long known issue..I'll figure out what it is and fix it on my end..yueh refuses to fix it and claims it's fixed on their end..i'll have a fix out asap

**Comment by p455w0rd** [comment]
so this appears to be an issue with Fluxed Networks as this doesn't happen anywhere else (EnderIO wireless charger for instance)

**Comment by p455w0rd** [comment]
I submitted a PR to SonarCore ( SonarSonic/Sonar-Core#30 )..no clue if this has anything to do with it as I haven't looked into how the handle their power, but it _might_
