### ISSUE TITLE
View Cell support

### ISSUE THREAD

**Issue by WinterAU** [p455w0rd/WirelessCraftingTerminal#117]
It'd be nice to be able to put View Cell's in the WCT. It helps remove a lot of the clutter and if you're like me and you like compacting drawers, the nuggets are very annoying.

**Comment by p455w0rd** [comment]
if you want to submit a PR, I'll gladly merge it, but I specifically removed them because of how pointless they are to me. it would have been easier to just leave them in..but they just clutter up the screen and very few people use them
