### ISSUE TITLE
Terminal Hotkey not closing a GUI enhancement

### ISSUE THREAD

**Issue by WinterAU** [p455w0rd/WirelessCraftingTerminal#118]
So, I had the genius idea of replacing my inventory hotkey with the WCT hotkey, and I soon discovered it didn't close a GUI when you're in one (for example a furnace..) an option for closing the terminal with the key you pressed would be nice for users like me who use the numpad since we're left handed with the mouse.

Version: 1.10.2-1.0.0

**Comment by p455w0rd** [comment]
I was actually thinking bout this since I was messing with Baubles and precisely this functionality exists there. In the mean time, you can always use escape, but I will implement this. :)

**Comment by p455w0rd** [comment]
ok, just so you know, I've implemented this, but to minimize bug with the terminal's search box, you must hold ctrl as well..so if you bind it to "E" key, to close, you must hold Ctrl+E

**Comment by p455w0rd** [comment]
lol..so it appears I already implemented the ctrl+keybind functionality..I've just implemented pure functionality when not in any form of 'AutoSearch'...aka if you have the terminal not set to auto focus on the search box, then you will be able to just use the keybind key as you would with the normal player inventory :)
