### ISSUE TITLE
No gui open when right click, only chat message "Station can not  be Located"

### ISSUE THREAD

**Issue by adcrafter27** [p455w0rd/WirelessCraftingTerminal#12]
in version "WirelessCraftingTerminal-1.7.10-rv3-1.3.b" the WirelessCraftingTerminal worked perfect

i updatet today to version "WirelessCraftingTerminal-1.7.10-rv3-1.4.b" the WirelessCraftingTerminal was linked but when i right clickt no gui open only a message in the chat "Station can not be Located"
when i Craft a new i have the same problem but when i use the shortkey the gui normal open and it work :S

I use appliedenergistics2-rv3-beta-6 and have changed the config to channel off (no Channel and ME Controller)

Picture:
Right Klick: http://imgur.com/a/ICby4
Shortkey: http://imgur.com/8evDDK9

**Comment by p455w0rd** [comment]
turning channels off causes a lot of bugs. I can almost guarantee that's where the problem is. I'll look into seeing if I am able to check the AE2 config, but I don't know if it is even feasible for me to try to make a workaround for this..we'll see

**Comment by p455w0rd** [comment]
since it opens with keybind, it should be fixable =D

**Comment by adcrafter27** [comment]
yes with keybind works
i switch channels on an nothing changed :(

**Comment by p455w0rd** [comment]
are you playing single player (offline) and what version of forge are you running?

**Comment by adcrafter27** [comment]
i play on a local server and use Forge 1.7.10 - 10.13.4.1614

**Comment by adcrafter27** [comment]
ok i  tested: 
in single player the right klick works
but on a server not

**Comment by p455w0rd** [comment]
ok, I believe I now what it is..I'll keep you informed

**Comment by p455w0rd** [comment]
tweeted you with a link to a pre-update release..it's really v4.5 as I still have one more bug to fix before v1.5

**Comment by p455w0rd** [comment]
try http://p455w0rd.net/mc/WCT/WirelessCraftingTerminal-1.7.10-rv3-1.4.2.b.jar

**Comment by adcrafter27** [comment]
good job :) 
its work with WirelessCraftingTerminal-1.7.10-rv3-1.4.2.b 
thanks you
