### ISSUE TITLE
[Feature Request] Interface and Pattern Terminal / Switch

### ISSUE THREAD

**Issue by maginator** [p455w0rd/WirelessCraftingTerminal#120]
Hello i have a Feature that could be cool but i dont know if is possible.
My Idear is to have in the WCT a button to switch between a Crafting and a Pattern Terminal and if the Pattern Terminal is selected ther is a button for a Interface Terminal. Pleas Add that it could be so cool

**Comment by p455w0rd** [comment]
maybe in another mod
