### ISSUE TITLE
Item dupe bug

### ISSUE THREAD

**Issue by badguy2003st** [p455w0rd/WirelessCraftingTerminal#123]
If our having the crafting terminal open and throw away items with "Q" (must have at least 2 of the sime item that you're trowing away) the item appears in the AE system and in your inventory. Using 1.10.2-0.0.17

**Comment by badguy2003st** [comment]
Using it in FTB Beyond 1.2.1 if it matters.

**Comment by p455w0rd** [comment]
can you post a gif or video to youtube, because I can't replicate this bug...also trying using v0.1.22b from Curse

**Comment by p455w0rd** [comment]
nevermind..got it..NEI was interfering with ctrl+Q, also you forgot to mention that you had magnet active..working on a fix

**Comment by p455w0rd** [comment]
After testing, it's not on WCT's end. If you install AE2+Baubles+ACT+p455w0rdsLib this will not happen (at least with v0.1.22b of WCT). Another mod is causing this. I have mousetweaks disabled via their API in WCT, so it's not that. It would be a great help if you could try and track down which mod is causing this. If not, I'm sorry but I don't have time to investigate other mods atm. If it were WCT I'd take full responsibility and fix it, but as far as I can tell from testing, WCT works as intended outside of the pack.

**Comment by badguy2003st** [comment]
I'll test this when i come home from work.

**Comment by p455w0rd** [comment]
ok,it'sforestry..took a couple hours to figure that out...so the easy solution is to just disable Q'ing items from WCT if forestry is loaded...i'll look into another option, but this might be what I have to do

**Comment by p455w0rd** [comment]
this really isn'ton their end after all...they're cancelling the ItemPickupEvent, which, IMO should only affect things pertaining to their mod, but w/e..I've removed my dependance on the event and things seem to behave as they should now
