### ISSUE TITLE
Items Disappearing when left in terminal crafting grid

### ISSUE THREAD

**Issue by Hazmatik** [p455w0rd/WirelessCraftingTerminal#125]
I went to craft some blank blood runes from blood magic and realized my orb wasn't in my ME system so had to go grab it out of chest when i closed out the terminal to get it and re-opened the terminal some of the blank slates I had just placed in the crafting grid were gone. I had 2 stacks of 52 slates in there when i opened it back up the stacks were down to 33 in each. Had a similar issue happen to where all but one of the items in it disappeared when closing it and re-opening it.

**Comment by p455w0rd** [comment]
version?

**Comment by Hazmatik** [comment]
it's in FTB Beyond version 1.1.0
WCT version: 0.0.16
AE2 version: rv4-alpha-11

I realize these versions are old, I've been bugging the server admin to update the pack. It might not be an issue in the newer versions.

**Comment by p455w0rd** [comment]
no there's definitely a bug even in my local version..working on it
