### ISSUE TITLE
Wireless Crafting Terminal Item crashes server on first use.

### ISSUE THREAD

**Issue by jarquafelmu** [p455w0rd/WirelessCraftingTerminal#126]
I have created two wireless crafting terminal items with both infinity and magnet cards inserted. When I used the first terminal everything was fine at first and then I wasn't able to right click on anything then. I decided to relog to see if that fixed it and then as I quit the server crashed.

After the server came online I tried it again and no issues. Then I gave the second one to my buddy for his use and though it didn't crash the server for me to open it when he opened it for the first time once again no one could interact with blocks. I re-logged again to try and fix it and the server went down.

Here is a crash log from the event showing that wireless crafting terminal threw a `NoClassDefFoundError` error.

Please let me know if any other information would be helpful.

First Crash: [crash-2017-04-03_04.23.50-server..txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/889055/crash-2017-04-03_04.23.50-server.-.wireless.crafting.terminal.txt)

Second Crash: [crash-2017-04-03_04.54.20-server.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/889050/crash-2017-04-03_04.54.20-server.txt)

**Comment by p455w0rd** [comment]
derp on my end, thanks for the report..sorry about that! i'll get a new version up as soon as I can..I'm currently doing a decent sized rewrite of some of the core parts of this mod, so it may not be tonight

**Comment by jarquafelmu** [comment]
Thanks for the quick reply and fix to the issue. I really hope to be able to use your mod again soon. I really love the idea of being able to access my ME system from anywhere. It was unfortunate that the crashes resulted in world corruption but I was able to restore the world from backups but it was sad how far back I had to go.

**Comment by p455w0rd** [comment]
no problem, if you want to join my discord I can get you a private build for your server - https://discord.gg/8SB3T5C just ping me
