### ISSUE TITLE
WCT causes crash when picking up it when it is opened (bug)

### ISSUE THREAD

**Issue by EnderSam** [p455w0rd/WirelessCraftingTerminal#129]
If you open the WCT gui then pick it up it causes a crash. Beyond version 1.4.0

Wireless crafting Terminal version: 1.10.2-0.1.25

Pastebin: https://pastebin.com/2wkcQcmY

**Comment by jarquafelmu** [comment]
Tested issue in version 1.10.2-0.1.26, still crashes the game with `NullPointerException`.

[crash-2017-04-10_19.04.46-client.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/911827/crash-2017-04-10_19.04.46-client.txt)

**Comment by p455w0rd** [comment]
this issue has the label fixed-waiting..AKA...this isn't on curse yet..please be patient
