### ISSUE TITLE
[Minor Improvement] Add different chat message if wireless access point was removed

### ISSUE THREAD

**Issue by condensedapple** [p455w0rd/WirelessCraftingTerminal#13]
If you set up your wct, and destroy the wireless access point afterwards, currently the message "chatmessages.ae2wct.NoNetworkPower" (`chatmessages.ae2wct.NoNetworkPower`) is displayed (and the wct does not open anymore), which might be confusing if another player destroyed the wireless access point and, suddenly, the wct does not work. Another chat message might be auxiliary.

**Comment by p455w0rd** [comment]
already addressed this in #12 ..check this file out: http://p455w0rd.net/mc/WCT/WirelessCraftingTerminal-1.7.10-rv3-1.5.b.jar tell me if you still get the wrong chat message..it should all work..take note that this is a pre-update file..the actual v1.5b will include another fix, so you will still need to download it when I release it

**Comment by condensedapple** [comment]
Sadly, no change, but only tested in SP though. I dont think this is related to #12, as it is not about destroying the wireless access point.

**Comment by p455w0rd** [comment]
actually it is...i was doing the network check in 2 different places and now i reduced that to only the one needed..i'll reopen this till i make sure it's solved

**Comment by p455w0rd** [comment]
ok..i've fixed it 100% this time =]..i'll ship you a pre-copy in 15mins to be sure

**Comment by p455w0rd** [comment]
try http://p455w0rd.net/mc/WCT/WirelessCraftingTerminal-1.7.10-rv3-1.4.2.b.jar

**Comment by condensedapple** [comment]
sry for the late reply (sleeping + school), with the new version everything is fine!

**Comment by p455w0rd** [comment]
just reopening until i get the official version(v1.5b) uploaded and everything

**Comment by p455w0rd** [comment]
Awaiting Curse approval for new version - in the mean time,you can get latest version here: http://p455w0rd.net/mc/WCT/
