### ISSUE TITLE
WCT causes NullPointerException crash when clicking on it with a held item when the WCT GUI is open

### ISSUE THREAD

**Issue by jarquafelmu** [p455w0rd/WirelessCraftingTerminal#130]
**Bug:** Clicking on the WCT terminal item with any item while the ME storage inventory is open causes a `java.lang.NullPointerException: Ticking screen` client crash.
****
**Steps to Reproduce:** Open the WCT GUI when connected to the ME storage with a magnet card installed or not. Grab an item from the ME storage and while it's still in your hand click on the WCT item. The game crashes with the `Ticking screen` description.
****
**Affected Mods**
- FTB Beyond 1.4.2
- Forge 12.18.3.2254
- Wireless Crafting Grid 1.10.2-1.0.0
- Wireless Crafting Terminal 1.10.2-0.1.25
- WCT API 1.10.2-rv4-1.0.0b
****
**Crash-report:** [crash-2017-04-09_22.42.34-client.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/909025/crash-2017-04-09_22.42.34-client.txt)

**Comment by p455w0rd** [comment]
Duplicate #129
