### ISSUE TITLE
1.10.2 - Infinite booster card drop doesn't work

### ISSUE THREAD

**Issue by FangedHex** [p455w0rd/WirelessCraftingTerminal#132]
Hello, first of all, I love your mod.
So about my problem, I'm making a private modpack for my friend and me and I wanted to try to disable crafting of the infinite boost card(this part works) and the only way to get it was the drop by Wither or Ender Dragon but it doesn't work for me :(

I use Minecraft 1.10.2 with AE2 RV4 Alpha 11 and WCT 0.1.27 with other mods that you can see here https://pastebin.com/6TVD5u6x

Here is the config file I use to test https://pastebin.com/yU69PNVR (100% chance to drop on the wither)

I don't know if your mod is incompatible with one of the mods I use or if I'm doing something wrong ...
Also, I don't know how I can test if your item is correctly added to the wither drop because Just Enough Resources is not working with the Wither or Ender Dragon ...

If you have any question or you want me to test something, I can do it. I can also test with just AE2 and your mod alone if you want to.

Thanks for reading :)

**Comment by p455w0rd** [comment]
oops..forgot to remove the config..I removed the wither drop entirely..you can either enable the recipe or get them as dragon drops now..

**Comment by FangedHex** [comment]
Ok thanks. Did you add the card drop to the loot tables of the enderdragon ? Because it doesn't seems to drop with Woot which use the entity drop table :/

**Comment by p455w0rd** [comment]
last I knew the wither and ender dragon didn't have loot tables..this may have changed now..I'll look at woot and see how they get it..I know when I had the wither drops enabled, woot did drop the booster card from the wither spawner, so I imagine that they special-cased the wither and dragon..if there are tables, I'll add support, but afaik, this still hasn't been implemented

**Comment by FangedHex** [comment]
I think there is no loot tables that why Not Enough Resources doesn't show up for bosses. I will try to add the wireless boost card directly in the Woot config.
