### ISSUE TITLE
WCT + Ender-io Wireless Charger

### ISSUE THREAD

**Issue by Demonpriest** [p455w0rd/WirelessCraftingTerminal#133]
When the WCT is in the inventory it recharges fine with ender-ios wireless charger, but when you put the WCT in the baubles slot (awesome feature btw) it doesnt recharge.

**Comment by p455w0rd** [comment]
there is nothing I can do about that...WCT implements IEnergyContainerItem (the proper method of implemnting the RF API on an item), so it would be up to the EnderIO team to support baubles with their charger
