### ISSUE TITLE
All Items with Space to Ae

### ISSUE THREAD

**Issue by maginator** [p455w0rd/WirelessCraftingTerminal#135]
Hi after i have update WCT to 0.1.27
I cant move all Items when press Space to my Me System.
LG Magi

**Comment by p455w0rd** [comment]
this isn't a bug..just something that's not implemented...i'll get to it when I have time

**Comment by maginator** [comment]
But before the update it work

**Comment by p455w0rd** [comment]
what was the last update where it worked? because I would have to guess that it stopped working after I disabled mousetweaks support then..I plan to research mousetweaks and properly add support in the future, but I just have too much going on atm for such a trivial feature

**Comment by maginator** [comment]
i have update from 0.1.21 to 0.1.27 and there it work
