### ISSUE TITLE
Wireless crafting Terminal out of range while standing at a connected security terminal

### ISSUE THREAD

**Issue by StubenHock3r** [p455w0rd/WirelessCraftingTerminal#136]
The WirelessCraftingTerminal/Wireless Terminal is linked and got power but even if i stay above or at any of the sides of the security terminal it says "Wireless Out Of Range"

**Comment by p455w0rd** [comment]
do you have a wireless access point on the network?

**Comment by p455w0rd** [comment]
I'm unable to reproduce this in any setting, so I'm goin to mark it as invalid and close it. I'll reopen if you ensure that there is a wireless access point on the network and this issue still persists.

**Comment by StubenHock3r** [comment]
I didnt even know that i need the wireless acces point x) Sorry for wasting your time but thanks for your help tho
