### ISSUE TITLE
1.7.10 source?

### ISSUE THREAD

**Issue by ThatGamerBlue** [p455w0rd/WirelessCraftingTerminal#137]
Want to patch a few fixes into 1.7.10, can I get the source for 1.7.10 version?

**Comment by p455w0rd** [comment]
The master branch of this repo is the 1.7.10 version. If you don't understand how to use github, I don't know how I would feel about you attempting to patch something

**Comment by ThatGamerBlue** [comment]
I was assuming the master branch would be the most up to date version available (i.e. 1.10 / 1.11) because that's how most repos work.

**Comment by p455w0rd** [comment]
Hardly. But go ahead and throw a temper tantrum. Hope you feel better now :)

**Comment by ThatGamerBlue** [comment]
Wasn't expecting such a toxic reaction from you from a simple question. Not everyone is a genius.

**Comment by p455w0rd** [comment]
It wasn't a toxic reaction. I was being serious. It's pretty basic stuff when collaborating to know how to use a repository. Put yourself in my shoes. You have a mod. Some random person that doesn't understand the basics of project collaboration claims he wants to patch your code. What would you do?
