### ISSUE TITLE
Compact Machines compatibility

### ISSUE THREAD

**Issue by CloWnicide** [p455w0rd/WirelessCraftingTerminal#138]
I had my AE2 system inside a machine from said mod, and only when WCT is installed can I not:

A. Use auto-crafting while inside the machine.

B. Open the in progress crafting tab without the game crashing.

Unsure if it only happens in a world already made or just with AE systems inside the machines. Will test here in bit under both circumstances.

**Comment by p455w0rd** [comment]
1) test without wct and also i will need to know what version of WCT you are using..pack also if applicable

**Comment by CloWnicide** [comment]
Autocrafting and accessing the current crafting tab works fine without WCT while in the machines.

Version I am currently using: WirelessCraftingTerminal-1.7.10-rv3-1.8.7.4b

Mod List, have fun.
[Mod List.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/949504/Mod.List.txt)

**Comment by p455w0rd** [comment]
1.7.10 hasn't been supported for around 10 months now, sorry
