### ISSUE TITLE
dupe bug with multiple terminals

### ISSUE THREAD

**Issue by Saereth** [p455w0rd/WirelessCraftingTerminal#139]
The stack size for the wcts are >1 so you can stack them and then insert a magnet/booster card. It then applies that booster card/magnet card to all of them, even if you only had 1 booster.

WirelessCraftingTerminal-1.10.2-0.1.29.jar

**Comment by p455w0rd** [comment]
thanks for the report :) will get it fixed asap

**Comment by p455w0rd** [comment]
fixed in v0.1.31
