### ISSUE TITLE
[1.10.2] Serverlags during Stackcrafting

### ISSUE THREAD

**Issue by Hodel1** [p455w0rd/WirelessCraftingTerminal#140]
Hi,

when i craft min. 1 stack per time, it results a massive serverlag.

Tested on FTB Beyond 1.5.3 with Wireless Crafting Terminal 0.1.27 and AE2 rv4-alpha-11

**Comment by maginator** [comment]
Hi, so far i know that this dosent belongs to WCT. I think it is the same in a normal Crafting Terminal. But that is only what i think

**Comment by p455w0rd** [comment]
Are you saying it doesn't happen with a normal AE2 terminal/wireless terminal? Because I have nothing to do with AE2's autocrafting system. Also 0.1.27 is outdated. I'm waiting on FTB Team to update. Thanks for the report!

**Comment by p455w0rd** [comment]
Yeah...clsoing this issue :)

**Comment by Hodel1** [comment]
In my Crafting Terminal from AE2 doesn't lag the server. When i craft for example 10 Stacks Blocks of Redstone, it lags a little bit for really short time. 

In Wireless Crafting Terminal it lags if you craft only one stack.

Autocrafting is not affected here.
