### ISSUE TITLE
Shift clicking items from WCT drops TPS dramatically

### ISSUE THREAD

**Issue by tolly7654** [p455w0rd/WirelessCraftingTerminal#141]
Basically, whenever people start shift clicking items from either the crafting output or the storage area of the Wireless Crafting Terminal (linked a screenshot too), it causes a huge TPS drop, to the point where the entire server hangs to process the output.
![6b51b841f380459fba24dac6b5e78386](https://cloud.githubusercontent.com/assets/9297773/25592359/6c77802e-2eb0-11e7-8f7b-a697fb4e0ce5.png)
There is nothing in the console or the logs about it either.
![screenshot_20](https://cloud.githubusercontent.com/assets/9297773/25592645/70db4438-2eb1-11e7-9adf-4412a8a601d7.png)
That is the TPS output whilst shift clicking from the system.

**Comment by p455w0rd** [comment]
does this happen with the AE2 crafting terminal as well?

**Comment by tolly7654** [comment]
It happens when tps has dropped below 13 with the regular AE2 terminal. With the wireless crafting terminal, it happens regardless of what the tps is. Not sure why to be honest 😕

**Comment by p455w0rd** [comment]
I've looked through the code on my end and don't see anything that stands out..i'll do more in depth testing as soon as I get a chance..thanks for the report :)

**Comment by tolly7654** [comment]
No problem. If you don't find any conclusive results, let me know and I'll make an issue with the devs of AE2. Thanks for the quick responses!

**Comment by Hodel1** [comment]
Yes, i reported it few hours ago :D 
Thats a big problem

**Comment by p455w0rd** [comment]
@Hodel1 i get the point and I have responded..stop spamming my repo please

**Comment by p455w0rd** [comment]
ok..so we've tested this extensively on the All The Mods dev server..this is not related to WCT, but rather something beyond WCT, and AE..AE2, WCT, and Refined storage all do this..I was easily able to hang the server from both the AE2 Crafting Terminal and the Refined Storage Crafting Grid..there is nothing I can do on my end to recitfy this. Sorry :(
