### ISSUE TITLE
[1.10.2] Crash when shift clicking out of crafting slot

### ISSUE THREAD

**Issue by P3pp3rF1y** [p455w0rd/WirelessCraftingTerminal#144]
I get this crash on all the mods modpack when sometimes shift clicking the recipe result crashes me. I find it quite odd that it is just sometimes as it seems to be crashing when it checks bauble slot, but that slot is there all the time and in all cases I had one bauble item in one of the slots. 

https://hastebin.com/doyucojavi.scala

**Comment by p455w0rd** [comment]
looks like the mod item scroll would need GuiWCT blacklisted..i'll look into integrating this internally..so that mod is doing something with guis..dunno what didn't look into it much..just know that i'll do what I can on my end..thanks for the report

**Comment by p455w0rd** [comment]
Have you used this since then ^ @P3pp3rF1y ? Did this ever improve?

**Comment by P3pp3rF1y** [comment]
Sorry didn't have a chance to play that pack since. But I guess others would report this issue if it still existed.
