### ISSUE TITLE
Wireless crafting terminal not Keeping settings

### ISSUE THREAD

**Issue by KendirkRS** [p455w0rd/WirelessCraftingTerminal#145]
Version 0.1.27

Pretty simple i prefer to always have it set to quantity but when i close screen it comes back to alphabetical settings again basically all setting return to default if need images/video what i mean i will supply

the only thing it does remember is the Search bar

**Comment by Earthgamez** [comment]
I can confirm this happening in version 1.8.1 of FTB Beyond. Seeing as the mod is in alpha and has an alpha tracker, its to be expected but yes, this is an issue that exists.

**Comment by p455w0rd** [comment]
I'm not expeiencing this in latest version on CurseForge.
