### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by HazardYT** [p455w0rd/WirelessCraftingTerminal#146]
i made my own modpack with mods that work together and i have all the dependant mods for this mod and when i load it without the wct it works fine but when i load it with wct it says a fatal error has accured the game has crashed. and yes i have ae2 r4 and newest version of wct

it says: 
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Wireless Crafting Terminal 2 (wct)

Log: https://pastebin.com/STrn7LH9

**Comment by p455w0rd** [comment]
use the correct version of p455w0rdsLib: https://minecraft.curseforge.com/projects/p455w0rds-library/files/2385958/download

**Comment by HazardYT** [comment]
tanks
