### ISSUE TITLE
Displayed item staying crafting terminal

### ISSUE THREAD

**Issue by nodar86** [p455w0rd/WirelessCraftingTerminal#147]
Version 1.10.2-0.1.31

Minor issue: Having the wireless crafting terminal on the hotbar then switching to it sometimes causes it to "get stuck to your hand" meaning that if you switch to another item the item displayed will still be the wct.
This is only a graphical error and switching to bare hands always fixes it.

**Comment by p455w0rd** [comment]
yeah, not much can be done afaik..I override the appriate method, but sometimes it still does it..
