### ISSUE TITLE
Server Crash - putting the terminal into itself

### ISSUE THREAD

**Issue by robertmaxton42** [p455w0rd/WirelessCraftingTerminal#149]
By using the number keys while hovering over an item in the crafting table in the WCT, it is possible to swap the item in the crafting grid with the WCT itself, causing an immediate server crash. Fortunately, the server reboots with no problems.

**Comment by redcatone** [comment]
What version of the mod are you using? This sounds like an issue I had a while back, but got fixed. #115

**Comment by robertmaxton42** [comment]
Huh. Apparently 0.0.17 isn't latest; news to me. I'll update tomorrow. Thanks!

**Comment by p455w0rd** [comment]
thx @redcatone ..going through a lot of stuff IRL and when I saw this I just closed chrome since I was pretty sure I had already tackled this
