### ISSUE TITLE
low priority request

### ISSUE THREAD

**Issue by kurokuno** [p455w0rd/WirelessCraftingTerminal#15]
can we have a way to disable all dropping of the booster card inc the dragon as i wish to set it up as a quest only reward in a mod pack im building

**Comment by p455w0rd** [comment]
sure thing =D

**Comment by kurokuno** [comment]
thankyou so very much =D trying to make a massive tech pack that is very heavily mine tweaked and quest's with npc's =D so this will help lots ty

**Comment by TheCodedOne** [comment]
Surely just setting the drop chance to 0 would disable it dropping?
