### ISSUE TITLE
Can't charge Wireless Crafting Terminal while it's in Bauble slot.

### ISSUE THREAD

**Issue by TechieJunk** [p455w0rd/WirelessCraftingTerminal#150]
I'm using an Ender IO wireless charger, and while my WCT is in my bauble slot, it doesn't charge.

**Comment by p455w0rd** [comment]
version?

**Comment by TechieJunk** [comment]
Minecraft 1.10.2
Forge 12.18.3.2316
WCT 1.10.2-0.1.31
Ender IO 1.10.2-3.1.193
