### ISSUE TITLE
item dupe(or lost) bug with ender io wireless charger

### ISSUE THREAD

**Issue by mystictales** [p455w0rd/WirelessCraftingTerminal#160]
(minecraft 1.10.2, Forever Stranded 1.9.3 Modpack)

dupe...
1) setup wireless charger block in ender io.
2) wireless crafting terminal(WCT) on hand and fill items in crafting grid.
3) close WCT UI and WCT move to bauble slot.
4) open WCT UI from hotkey and remove items in crafting grid.
5) close and reopen WCT UI. removed item exists in crafting grid.

lost...
1) empty crafting grid and move to bauble slot.
2) open WCT UI, fill items in crafting grid.
3) close and reopen WCT, lost items in crafting grid.

**Comment by p455w0rd** [comment]
Is this SMP? I'm working on reproducing the dupe bug atm and I am unable to.

**Comment by p455w0rd** [comment]
also, by 'empty' are you manually removing items or using the 'Store Items' button that returns items to the network?

**Comment by mystictales** [comment]
tested on FTB Beyond 1.11.0 modpack, has same issue.

**Comment by p455w0rd** [comment]
definitely appreciate the in-depth report! i'll get to it as soon as I can...likely wont be for a couple days just to give you a heads up...

**Comment by p455w0rd** [comment]
UPDATE: working on this now...I have reproduced the dupe bug thanks to your outstanding explanation...I'll get this fixed, then work on reproducing the item loss

**Comment by p455w0rd** [comment]
Would you mind joining my discord so I can ship you a copy of a version with these fixes implemented? https://discord.gg/9J7yhUP

**Comment by p455w0rd** [comment]
uploaded to CurseForge..just awaiting approval...if you want a version before curse approves (they're slow atm), join my discord @ https://discord.gg/9J7yhUP - the fix I implemented should fix both of these problems...let me know if it persists

**Comment by p455w0rd** [comment]
got a report from @Lordmau5 that this issue still still exists

**Comment by zetx** [comment]
Hi, this set of bugs have resurfaced. Reproduction should be the same, please see these gifs for more detail: [Losing the item](https://gfycat.com/MediumSmugIggypops) and [Duping the item](https://gfycat.com/DefiniteFavorableBanteng)

Minecraft: 1.12.2
WirelessCraftingTerminal: 3.9.64
Using the Enigmatica 2 modpack: 1.36

Thanks!
