### ISSUE TITLE
[1.10.2] Crafting multiple stack lag

### ISSUE THREAD

**Issue by Lordmau5** [p455w0rd/WirelessCraftingTerminal#162]
MC: 1.10.2
Forge: 12.18.3.2488
WCT: 2.1.34

Title should be self-explanary

**Comment by p455w0rd** [comment]
Are you still able to reproduce this with latest version (2.1.35)? send you some gifs in discord DM...I am unable to reproduce.

**Comment by Miner94** [comment]
im sure this is mod interaction

**Comment by Miner94** [comment]
i have the same problem but im running like 136 mods so

**Comment by p455w0rd** [comment]
So in 1.12.2 I use recipe caching..I think if I implement the same in 1.10.2 it'll greatly reduce lag

**Comment by p455w0rd** [comment]
this was something suggested my @Lordmau5 ...seems to work on 1.12.2..should work here as well :)
