### ISSUE TITLE
[1.12.1] Crash with Applied Llamagistics

### ISSUE THREAD

**Issue by TonRZN** [p455w0rd/WirelessCraftingTerminal#163]
Can you consider adding support to it ? It's much more stable than current AE2 and has an addon that adds fluid support :)

Here's the crash log when the compatibility issue happen :
[crash-2017-10-05_14.34.58-client.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/1360798/crash-2017-10-05_14.34.58-client.txt)

**Comment by p455w0rd** [comment]
nope..use AE2..no reason to use that mod..it's fork..aka literally a rip off created for 1.11 before AE2 had the time to get a release out..AE2 is supported in 1.12

**Comment by DeadSix27** [comment]
@TonRZN I reported it to the dev of the fork, it's in his hands for reasons mentioned by @p455w0rd  see: https://github.com/thiakil/Applied-Energistics-2/issues/81

**Comment by p455w0rd** [comment]
AE2 1.12 versions have been getting some nice overhauls...there will be more to come...trust me..it's worth it to use AE2...the crash here is due to a rework in AE2

**Comment by DeadSix27** [comment]
@p455w0rd I'm mainly interested in the Fluid part, sadly extracells is only out for 1.10 yet and there is no info whether it gets a 1.12 update yet

**Comment by p455w0rd** [comment]
can you please join my discord..you might be interested in something I'm working on ;)

**Comment by TonRZN** [comment]
@p455w0rd what's your discord ?

**Comment by DeadSix27** [comment]
@p455w0rd ^same question

**Comment by p455w0rd** [comment]
sorry was referring to @DeadSix27 but you are welcome to join as well.. http://p455w0rd.net/discord

**Comment by TonRZN** [comment]
@p455w0rd sorry, I use a lot of fluids in my AL system too, like him
