### ISSUE TITLE
[1.12] Out of Range and No Power messages appearing despite having power and being in range

### ISSUE THREAD

**Issue by DeadSix27** [p455w0rd/WirelessCraftingTerminal#164]
In version `WirelessCraftingTerminal-1.12-0.2.36.jar`
If you are within range of the AE2 Access Point your WCT will still message you saying that it is not in range, but still works.

Also wrong is the `No Power` message, which appears if you insert the infinity booster and open the terminal.

Both issues do not seem to impact the usage of the terminal though.

**Comment by p455w0rd** [comment]
ths for the report, will try and figure that out asap..this is actually a bug i was semi aware of..kinda forgot when updating
