### ISSUE TITLE
1.12 crash with newest AE2

### ISSUE THREAD

**Issue by ItzKdoge20YT** [p455w0rd/WirelessCraftingTerminal#165]
i was trying this mod for 1.12.2 and it crashes
Using AE2 rv5 Alpha 7

crash report : https://pastebin.com/eUqBm4T2

**Comment by covers1624** [comment]
Caused by: java.lang.NoClassDefFoundError: cofh/redstoneflux/api/IEnergyContainerItem
Install RedstoneFlux.

**Comment by p455w0rd** [comment]
so while doing some testing yesterday I removed the RF API..after re-adding I forgot to make it optional is all..will get a fix out today...for now, as covers said, just add the RF API via Curse/Twitch
