### ISSUE TITLE
1.12 Shift click from JEI not filling recipe

### ISSUE THREAD

**Issue by chooven** [p455w0rd/WirelessCraftingTerminal#167]
I have ATM3 4.1 as a base
added Wireless Crafting Terminal.
JEI is jei_1.12.2-4.7.11.102
forge is 2497
AE2 rv5-alpha-7
I click the item in JEI when click the + to populate the crafting grid and the item don't fill

**Comment by p455w0rd** [comment]
confirmed ..will try and include this fix in the next update which will be at some point yet today...thanks for the report :)
