### ISSUE TITLE
[1.12] Wont link in security terminal

### ISSUE THREAD

**Issue by chooven** [p455w0rd/WirelessCraftingTerminal#172]
Version: 1.12-3.2.40

https://pastebin.com/G1ZPifb0

**Comment by p455w0rd** [comment]
can i please see the FULL log?

**Comment by chooven** [comment]
Sure thing, here you go

https://pastebin.com/qFnum9YY

**Comment by p455w0rd** [comment]
thanks! i'll get the latest build on CurseForge asap :)

**Comment by p455w0rd** [comment]
fixed version is live: https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2489175
