### ISSUE TITLE
Magnet Card

### ISSUE THREAD

**Issue by Miner94** [p455w0rd/WirelessCraftingTerminal#173]
one thing i have noticed is if i exit the game without disabling the magnet card first whenever i reenter the game the card no longer inserts directly to the network

**Comment by Miner94** [comment]
This is the most recent version for 1.10.2 btw

**Comment by p455w0rd** [comment]
I will definitely look into this. Thanks for the report!

**Comment by Miner94** [comment]
No problem other than that the mod works great

**Comment by p455w0rd** [comment]
is this very reliably reproduced? is this in a pack, if so, which pack? you're welcome to discuss this in real time in my discord http://p455w0rd.net/discord

**Comment by Miner94** [comment]
heres the mod list man

https://pastebin.com/dAKc687d

**Comment by Miner94** [comment]
hope this helps
