### ISSUE TITLE
[1.12.2] WCT wont open (Errors)

### ISSUE THREAD

**Issue by UnPure** [p455w0rd/WirelessCraftingTerminal#175]
Everytime i try to open the WCT, nothing happens but in the server console in get some errors.
It doesnt matter if i right click it or use the keybind while wearing it as a bauble.

Part of the log that appears while trying to open it:
https://pastebin.com/Wfw4t8hu

**WCT:** 3.2.41
**p455w0rdslib:** 2.0.21
**Forge:** 14.23.0.2512
**AE2:** rv5-alpha-8

**Comment by p455w0rd** [comment]
yeah, the AE2 team made some good changes to their codebase which likely break any current addon. I'll be working on this today :). Thanks for reporting!

**Comment by p455w0rd** [comment]
fixed version is live: https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2489175
