### ISSUE TITLE
[1.12.2 SMP] Sort/Filter button not working

### ISSUE THREAD

**Issue by chooven** [p455w0rd/WirelessCraftingTerminal#176]
The 3 sort buttons (Sort by Type, alpha, Quantity and direction and crafting/inventory) on the WCT are not working.  No messages just nothing happens on click

**Comment by p455w0rd** [comment]
hmmm...I'm experiencing some weird stuff in dev..it's like all the changes I made, have been reverted :/

**Comment by p455w0rd** [comment]
![](http://p455w0rd.net/u/12.48.31-10.10.17.png)

playing in SMP atm, everything seems to be fine...

**Comment by chooven** [comment]
AE2 rv5 alpha 8 
WTC 3.4.42

**Comment by p455w0rd** [comment]
yup..same version as me..dunno..i'll look into it, but so far, I am unable to reproduce

**Comment by p455w0rd** [comment]
i dunno how it would make a difference, but please try the latest version on curse

**Comment by chooven** [comment]
These sort button are working in newest version SMP, thanks
