### ISSUE TITLE
[1.12.2 SMP] Can't start crafting jobs from WCT

### ISSUE THREAD

**Issue by chooven** [p455w0rd/WirelessCraftingTerminal#178]
You can select the item to craft and set the quantity but are unable click the start button.

**Comment by chooven** [comment]
When I get to the modal where it shows all the items needed to do the craft, Cancel is the only button that works.  I get the focus on the CPU and start buttons but when I click them nothing happens they don't even depress

**Comment by chooven** [comment]
Just tried SSP and works like a champ the buttons and crafting so your correct it SMP only

**Comment by p455w0rd** [comment]
yeah.,..i get what you are saying..this just isn't happening for me.. I don't know what else I can do

**Comment by chooven** [comment]
Works great in new version, thanks for getting this working in 1.12
