### ISSUE TITLE
[1.12.2 Singleplayer] Crafting Status

### ISSUE THREAD

**Issue by TheSnowyChickens** [p455w0rd/WirelessCraftingTerminal#179]
Hello,

im kicked out of the WCT ,if I press "Crafting Status" during a crafting task and not.
Im installed the infinity Booster Card and out of the range from 16 (normal accespoint range) the "Crafting Status Interface" don't work very well.

The normal WCT work fine also from a long long long range (10 000 blocks).

MC 1.12.2
Forge 2512
WCT 1.12.2-3.4.42
AE2 rv8

**Comment by p455w0rd** [comment]
will look into it, thank for the report!
