### ISSUE TITLE
Network has no power when out of dimension

### ISSUE THREAD

**Issue by Stalkstalks** [p455w0rd/WirelessCraftingTerminal#18]
The wireless crafting terminal consistently reports that the network has no power when I try to use it in a different dimension than the one the ME network is located in.

The chunks containing the ME network are chunkloaded, and I can export items to the network using an ender pouch/chest connected to the network.

**Comment by p455w0rd** [comment]
working on this now

**Comment by p455w0rd** [comment]
You can get the hotfix version which has the bug fixed @ http://p455w0rd.net/mc/WCT/

**Comment by Stalkstalks** [comment]
Any chance of a version of the hotfix for AE2v2?

**Comment by p455w0rd** [comment]
http://p455w0rd.net/mc/WCT/WirelessCraftingTerminal-1.7.10-rv2-1.5.4b.jar
