### ISSUE TITLE
[1.12.2, low priority] Text :)

### ISSUE THREAD

**Issue by TheSnowyChickens** [p455w0rd/WirelessCraftingTerminal#180]
Hello again,

here is another simple mistake, but nothing that result in a problem. :)

![2017-10-10_23 57 19](https://user-images.githubusercontent.com/29357962/31412845-fbf79852-ae16-11e7-83bf-c7a4f9dcec3a.png)
The text in the action bar.

MC 1.12.2
Forge 2512
WCT 1.12.2-3.4.42
AE2 rv8

**Comment by p455w0rd** [comment]
ummm...that's nothing to do with WCT lol

**Comment by TheSnowyChickens** [comment]
oh fuck xD 
Sry , I was on the wrong side :D
