### ISSUE TITLE
Other items in toolbar show as Wireless Crafting 

### ISSUE THREAD

**Issue by chezpaul** [p455w0rd/WirelessCraftingTerminal#184]
Thanks for this mod man.

2 things.

First, the wireless crafting terminal once I select it will still show in my hand even though I'm selecting a different thing in my toolbar. I need to select my pickaxe or sword in order to show those and then whatever else in the toolbar will show as it should.

Second. I keep getting these errors in my server log which might have something to do with wireless crafting terminal. I'm not too sure about that but [here goes](https://pastebin.com/h1sq4u8r).

EDIT: I don't use the magnet in the WCT, only the long range thing.

**Comment by p455w0rd** [comment]
what WCT version?

**Comment by chezpaul** [comment]
WirelessCraftingTerminal-1.10.2-2.1.33 with latest Forge

**Comment by p455w0rd** [comment]
can you please try https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2488821 and tell me if you still experience this (your version is outdated)

**Comment by chezpaul** [comment]
Yes, with this latest version, it still happens. I also noticed that going back to an empty space in the toolbar will fix the issue too.

Little but of time I was on server seems to have fixed the error that was being spit out on server log.
I'll get back at you on that one later on.

**Comment by p455w0rd** [comment]
This is due to Lex Manos' fix for the jumping item from constant NBT changing as the item drains. I'm not experiencing this though. It's due to a client<->server desync. I cannot reproduce this however. I'm going to have a couple of my testers try to reproduce this.

**Comment by chezpaul** [comment]
Cool. Thanks
Let me know if there's anything I can do on my end.
Thanks

**Comment by p455w0rd** [comment]
Does the AE2 Wireless Terminal do this?

**Comment by p455w0rd** [comment]
I mean, the best thing you could do is take a screen recording (gif or mp4) and show me exactly what you're doing so I can follow those steps exactly to try and reproduce.

**Comment by chezpaul** [comment]
[Here](https://brandonswayrecording.box.com/shared/static/9ye7rjardbbk4m82nqvru4tawkurmxhg.mov) you go.

**Comment by p455w0rd** [comment]
says it was removed
just get sharex and make a gif

**Comment by chezpaul** [comment]
It's working fine.. It's a mov file that's why you can't see it. You are not on a mac.
I'll change the format tomorrow

**Comment by p455w0rd** [comment]
![](http://p455w0rd.net/u/09.25.13-14.10.17.png) ..yeah..workin fine..w/e..
