### ISSUE TITLE
finishing implementing JEI support

### ISSUE THREAD

**Issue by p455w0rd** [p455w0rd/WirelessCraftingTerminal#186]
so i kinda forgot about this...just here as a reminder

**Comment by ruifung** [comment]
Would this by chance be why clicking the move items button doesn't work?

**Comment by p455w0rd** [comment]
which version?

**Comment by p455w0rd** [comment]
![](http://p455w0rd.net/u/11.14.47-02.11.17.gif)

**Comment by ruifung** [comment]
![issue](https://user-images.githubusercontent.com/1073945/32334753-431c303c-c026-11e7-82b8-cfd53a3706e9.gif)

AE2 RV5b3, 3.6.48, MC1.12.2... Maybe it might be caused by something else here...? (it does work with regular AE2 crafting term)

**Comment by ruifung** [comment]
Interestingly, it seems to only happen with that network. Will investigate more on that..

**Comment by ruifung** [comment]
Update: I found that it specifically doesn't work when it's using infinity energy., It works fine while in range of AP though...?

**Comment by p455w0rd** [comment]
found the problem..fixing :D..thanks for reporting!
