### ISSUE TITLE
[1.12] Magnet card disappears

### ISSUE THREAD

**Issue by Leonyx1175** [p455w0rd/WirelessCraftingTerminal#187]
I have the WCT on as a bauble, and when I try to activate the card with the binding after switching it from its default to blacklisting or having it ignore NBT data, it disappears. My client also crashed after trying to enable more than one setting, with no crash report? I'm currently playing in SSP, can't test in SMP just yet.

Edit: Updating to most recent release and testing again, I'll update this comment in a bit.

**Comment by p455w0rd** [comment]
ALWAYS include: Mod Version, AE2 Version, MC Version, Forge Version...with so many versions of all of these how is a dev supposed to just miraculously know how to fix the problem? Also, this should be fixed in newest version...but seriously...__throw me a fricken bone here__

**Comment by Leonyx1175** [comment]
You're right, just trying to be helpful.

**Comment by p455w0rd** [comment]
riight
