### ISSUE TITLE
Client Crash due to WCT

### ISSUE THREAD

**Issue by trilexcom** [p455w0rd/WirelessCraftingTerminal#188]
Crashlog : https://pastebin.com/rz1iHbp7
AE :  appliedenergistics2-rv5-beta-2.jar
MC : 1.12.2
Forge : 2515
WCT : WirelessCraftingTerminal-1.12.2-3.5.45.jar

hi p455w0rd i am getting a crash log let me know if this is related to your mod or AE or forge thanks mat

**Comment by p455w0rd** [comment]
this is due to the p455w0rdsLib update, please use previous version of p455w0rdsLib for now. I'll be releasing a new update today which uses the latest pwlib..sorry bout this

**Comment by p455w0rd** [comment]
newest version will work with latest pwlib - https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2494007
