### ISSUE TITLE
Terminal no longer shows anything with AE2 rv5 beta build 3

### ISSUE THREAD

**Issue by ruifung** [p455w0rd/WirelessCraftingTerminal#192]
Like the title says, the terminal does not show anything with the latest rv5 beta (build 3).
This is needed because the rv5 beta b3 fixes the ridiculous power drain with a wireless charger.

I have tested with this version, and the previous version, therefore it is unlikely to be a regression caused by the latest version. Leaving me to conclude the AE version update is what likely caused it.

Understand that it can insert items, just not display them.

**Comment by p455w0rd** [comment]
I'll get on this asap! thanks for the report :)

**Comment by ruifung** [comment]
Damn, that was fast. I'm looking forward to the commit being pushed here so I can see what broke.

**Comment by p455w0rd** [comment]
basically PacketPartialItem has been replaced with PacketTergetItemStack
