### ISSUE TITLE
Automate installation of infinity booster cards?

### ISSUE THREAD

**Issue by ouroborus** [p455w0rd/WirelessCraftingTerminal#193]
Now that infinity booster cards are essentially fuel, is there some way to automate their insertion? If not, could we get a way to automate this?

**Comment by p455w0rd** [comment]
I'm open to suggestions, but being as more than one person can have access to a network, I don't rly see a feasible way of doing this...I mean i could make it so as soon as an infinity booster card enters player inv, it gets added to their infinity energy, but then what happens when you wants maybe take some out to give to a friend, etc?

**Comment by ouroborus** [comment]
As you suggest, make it so that infinity booster cards in the inventory are auto-consumed. Add a switch of some sort to turn this capability on, default is off.

For a possibly more immersive approach, add an item that goes in the Infinity Energy slot. If this item is is in place, infinity booster cards in the player inventory are auto-consumed.

The magnet would have override capability. If the magnet would push an infinity booster card into the AE2 network then that's what would happen. If the magnet would ignore the card, then the card can be auto-consumed. I imagine that the way the magnet and an auto-consumer both are likely to operate code-wise (on pickup for the magnet; inventory scanning or other non-pickup inventory insertion for the auto-consumer) this may be a natural side-effect but it's an important detail so I thought I'd specify it.

**Comment by RMcD94** [comment]
You should be able to put infinity boosters in when you're out of range. 

But it won't even let me open the wireless crafting to do so
