### ISSUE TITLE
WAP in range detection does not appear to be working correctly.

### ISSUE THREAD

**Issue by ruifung** [p455w0rd/WirelessCraftingTerminal#194]
![image](https://user-images.githubusercontent.com/1073945/32385075-ed5d8cb8-c0f7-11e7-8c07-0f17080c2245.png)

As you can see in the image above, I'm standing next to a WAP, and it's not noticing that I'm in range.
This is not the first WAP i've added to my network, this is a second one about a hundred blocks away from the first one. Both have no range boosters. 

The issue is likely in the detection of when infinity mode is enabled, as after it drains the infinity energy completely, it can still be opened, only then does the tooltip says it's in range of a WAP.

Compared to the previous issues, this is (relatively) minor, but still sort of annoying =)

**Comment by ruifung** [comment]
I believe the issue is in the WCTGuiObject class, rangeCheck() function. 

If field myWap is not null, it will always test to that WAP, and there doesn't seem to be any checks to invalidate the WAP cached in the myWap field, probably causing it to continuously only test against that initially cached WAP, it probably doesn't help that the getWAP method just retrieves the first WAP in the network.... and caches it.

**Comment by p455w0rd** [comment]
ah...i didnt even think about this..it's such an old AE mechanic for the wireless terminals...good catch! yeah..it's totally just that I'm check for the first WAP rather than a full collection of them...I'll work on this as soon as I have time..thanks for the good reports!

**Comment by p455w0rd** [comment]
![](http://p455w0rd.net/u/16.30.55-03.11.17.gif)

**Comment by p455w0rd** [comment]
![](https://thumbs.gfycat.com/TornExhaustedAustralianfurseal-size_restricted.gif)
