### ISSUE TITLE
Bug During Launch

### ISSUE THREAD

**Issue by Phoenix10020** [p455w0rd/WirelessCraftingTerminal#196]
I Have had an issue when launching the new mod with it's latest update (1.12-3.2.41). Don't know if it is another mod though.
[crash-2017-11-04_23.29.45-client.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/1443811/crash-2017-11-04_23.29.45-client.txt)

**Comment by p455w0rd** [comment]
Update to latest WCT ..you are running 3.2.41..latest is 3.6.49 - https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2496611
