### ISSUE TITLE
Nothing in the CRAFTING Terminal?

### ISSUE THREAD

**Issue by GalacticWolf541** [p455w0rd/WirelessCraftingTerminal#198]
Ok got the gui graphics glitch solved, then I got this:
[https://imgur.com/9oX68zA](url)
[https://imgur.com/fxiKR9E](url)

[Ignore the crafting, if I removed the crafting unit they disappear then the whole thing is empty.]

Im able to insert items just cant take them out...

**Comment by p455w0rd** [comment]
![](http://p455w0rd.net/u/14.47.16-05.11.17.png)

**Comment by GalacticWolf541** [comment]
I feel stupid lol thanks
