### ISSUE TITLE
Cannot start autocrafting tasks

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [p455w0rd/WirelessCraftingTerminal#20]
Whenever I open my Wireless crafting terminal, or any AE2 terminal (access/crafting) I simply can't autocraft anything, since once I click on the "next" button, the GUI closes and nothing happens. Clicking on the crafting tasks section in the terminal closes the connections and makes my minecraft return to the main menu (connection lost). No crash report.

Using:
WCT 1.5b for rv3
AE2 rv3 beta 6 - channels disabled (don't know if it matters)
forge .1614

**Comment by p455w0rd** [comment]
try this hotfix version and let me know if the problem persists: http://p455w0rd.net/mc/WCT/WirelessCraftingTerminal-1.7.10-rv3-1.5.1b.jar

**Comment by p455w0rd** [comment]
nevermind.I just reproduced the problem

**Comment by p455w0rd** [comment]
can you tell me if this only happens when you are in a separate dimension from the one that you AE netowrk is in?

**Comment by SmokeyTheBandicoot** [comment]
when this happened I was 1 block away from where my entire ME network was :). I'll try the hotfix and test it cross-dimensionally

**Comment by p455w0rd** [comment]
the hotfix won't work-I've found the problem and I'm working on it as we speak =]

**Comment by p455w0rd** [comment]
it is really odd though that it didn't work in the same dimension as in every scenario I've tested in v1.5b it definitely does work

**Comment by SmokeyTheBandicoot** [comment]
In fact the hotfix didn't fix the problem, that is just the same as before. If it could matter, I'm in a void Galacticraft Space Station dimension (ID=-27), not the overworld.

**Comment by p455w0rd** [comment]
it's to do with how it is accessing the network...shouldn't be long before I have it all worked out..thanks for posting the issue =D

**Comment by SmokeyTheBandicoot** [comment]
perfect, thank you for fixing this awesome mod. I was just looking for something to access cross-dimensionally my ME system and start AE2 autocrafting tasks away from base. Time to throw away the LP remote orderer (which cannot start AE2 autocrafting tasks :D

**Comment by p455w0rd** [comment]
LP is an amazing system..what people fail to realize is that everyone is different. Some people are biased and others are more open-minded as far as which storage system they like/prefer. I, for example, like trying new mods and methods of doing things in Minecraft so things don't get stale. Although AE2 is by far my favorite mod, I have played packs that have it and not even touched it. I instead used the LP remote orderer/ender pouch method of doing stuff. I've also used Botania's storage system just to try something different, although I hate typing, so that didn't last long lol. Another storage system I am eager to try is the new 1.9 BloodMagic system. So although I definitely appreciate you using my mod, I would just ask that you keep an open mind when choosing the system you use. If you choose to use AE2 alone solely because of my mod, my feelings wouldn't be hurt, but I like helping people and I wouldn't want my mod to go to such lengths as to contribute to ruining another amazing mod's usability. I really made this for myself and a few others I've seen posting on the AE2 GitHub repo asking for such an item and was disappointed to hear that they had no intentions of creating any such item. Again, many thanks to you =]

**Comment by p455w0rd** [comment]
please try this HotFix version and respond with results: http://p455w0rd.net/mc/WCT/WirelessCraftingTerminal-1.7.10-rv3-1.5.2b.jar

**Comment by SmokeyTheBandicoot** [comment]
I know that LP is an amazing system, in fact I mostly use LP to automate my base and I currently run an hybrid of LP/AE2 to keep everything tidy in my base. AE2 for storage, LP for logistics. When I said "throw away the remote orderer", I didn't mean "throw away the entire LP mod", since I can't live without it and it's unique features (oredict itemsink? wow, excellent for automated ore processing). Just one thing I didn't like not of LP or AE2, but their interaction: both didn't provide a method to start autocrafting tasks with the other mod. If you set up a bounch of autocrafters you have to use the remote orderer/pouch combo, if you use molecular assemblers you can craft in terminals and in the wireless terminal, but you can't craft in remote orderer. Your mod finally fixes that in AE2 side through the infinity card, and that's why I'm dropping the RO. So don't worry, I'll never ever drop something so amazing such as Logistics Pipes, I LOVE its integration with AE2 and with other mods. I like to be open-minded and to think out of box. This time I started my SP world in a galacticraft dimension, in a single-room space station, with nothing but a little oxygen supply and a teleport to tp back to overworld to gather resources. It is really fun to build in space, find new early game ways of flying, using BC builder to expand your space station or produce more power to increase oxygen production. Long story short, just like you, I love trying out new methods and mods, even if sometimes I feel nostalgic. So, again, many thanks to you for creating this amazing mod, that fills the tiny tiny gap between to masterpieces of mods. 

I apologize for the misunderstanding caused by the incorrect use of my words.

P.S: this is getting strange. At first I was able to reproduce the issue just exactly like before in AE2 terminals (cannot start, click on crafting status to lose connection), then I cheated a wireless crafting terminal, connected to my AE2 network and...worked. Even terminals worked. I though it may be a security station problem, then, so I removed and tested, re-placed and re-tested...works just fine. Doing a game restart to confirm.

**Comment by p455w0rd** [comment]
still witho0ut the hotfix, it won't work across dimensions..the hotfix addresses and fixes this

**Comment by SmokeyTheBandicoot** [comment]
Work beautifully. Thank you!

**Comment by SmokeyTheBandicoot** [comment]
Any news on this? The issue still happens. Again, randomly. I loaded my world, everything was fine, i started many autocrafting tasks, with no problems. Just a moment later, the issue happened. I couldn't start autocrafting tasks from any terminal due to the GUI with +1, +10, +100, ecc not showing, and clicking on "crafting status" closes connection. This time I got the log (when I got disconnected):
http://pastebin.com/AepFWtKX

**Comment by p455w0rd** [comment]
well..by the looks of that log, it's something on AE's end..my mod isn't mentioned anywhere in it

**Comment by p455w0rd** [comment]
I can tell you for sure that using AE2 with channels disabled is bugged. if you don't believe me, hop on IRC, join #appliedenergistics2 and talk to one of the devs/members

**Comment by SmokeyTheBandicoot** [comment]
Yes, but the issue doesn't happen when your mod isn't installed. That's why I reported here, it never happens without WCT

**Comment by p455w0rd** [comment]
well with that report I have nothing to go on..sorry
