### ISSUE TITLE
Autoconsume not updating count

### ISSUE THREAD

**Issue by ouroborus** [p455w0rd/WirelessCraftingTerminal#202]
The infinity energy count isn't updated live when cards are inserted via autoconsume. Closing and re-opening the interface updates the count. The count is updated live, without having to re-open the interface, when the cards are manually inserted.

**Comment by p455w0rd** [comment]
Thanks for the report :) I'll take your word for it that this is valid as I had to do a bunch of stuff to get all the changes to be updated in real time. I likely just overlooked this.

**Comment by p455w0rd** [comment]
works fine for me..are you using latest WCT? I tested in SMP and SSP...as soon as the boosters are consume, the tooltip is updated as it should (I send a packet from server to client to ensure this happens)..

**Comment by p455w0rd** [comment]
![](http://p455w0rd.net/u/10.31.18-13.11.17.gif)

**Comment by ouroborus** [comment]
Looks like it's specifically when you pick up the cards off the ground. (I have a dispenser-like arrangement involving a formation plane that just throws them on the floor).

**Comment by p455w0rd** [comment]
ohh..ok..i'll look into that..wish I'd have thought about that XD
