### ISSUE TITLE
Controller not unloading chunk when broken

### ISSUE THREAD

**Issue by jinkhya** [p455w0rd/WirelessCraftingTerminal#204]
Hello 
It seems like even after breaking a controller, the chunk is still being loaded. You can also see it listed in /ftb loaded_chunks_list even. 

Best regards,
Jin

**Comment by p455w0rd** [comment]
I thank you for the report, If you check out https://github.com/p455w0rd/p455w0rds-Library/blob/1.12/src/main/java/p455w0rdslib/capabilities/CapabilityChunkLoader.java#L130-L137 you will see that I am telling the Forge Ticket Handler to release teh attached ticket. I do this in https://github.com/p455w0rd/WirelessCraftingTerminal/blob/master/src/main/java/p455w0rd/wct/init/ModEvents.java#L114-L125 for the AE2 controller loading. So I can only conclude that it's an issue with Forge's chunk loading system. You can completely disable this in the WCT config file.
