### ISSUE TITLE
[1.12.2] Weird crash

### ISSUE THREAD

**Issue by 016Nojr** [p455w0rd/WirelessCraftingTerminal#206]
A weird crash happened suddenly when trying to opening the Wireless Crafting Terminal with the hotkey when it's a bauble.

Crash Log: https://pastebin.com/sd6T7q1Z

Forge: 14.23.0.2531
P455w0rd's lib: 2.0.24
WCT: 3.8.52
AE2: rv5-stable-2

**Comment by p455w0rd** [comment]
good find..although this shouldn't even be possible lol..what it's saying is that the Not Enough Wands Acceleration Wand is in the WCT Magnet Card slot..still, I should be doing a check to ensure that's what there

**Comment by 016Nojr** [comment]
I was wondering aswell, thanks for fixing it though! :)
