### ISSUE TITLE
[1.12.2] Uncraftable

### ISSUE THREAD

**Issue by EmosewaGamer** [p455w0rd/WirelessCraftingTerminal#207]
It seems that due to recent forge changes in shapeless recipes, the Wireless Crafting Terminal is uncraftable
![image](https://user-images.githubusercontent.com/25333164/32994727-94c67a3a-cd6b-11e7-852b-eb09c61030c6.png)

**Comment by p455w0rd** [comment]
are you using Forge 14.23.0.2546 or newer?

**Comment by p455w0rd** [comment]
nvm..reproduced..lame..go figure..I use the "recommended" version of creating recipes (JSON) and this happens..
