### ISSUE TITLE
Crash with Logistics pipes autocrafting

### ISSUE THREAD

**Issue by Thedrummonger** [p455w0rd/WirelessCraftingTerminal#21]
After installing this mod on my server initiating autocrafting with logistics pipes will crash the server. This only seems to happen in multiplayer.

Crash report:
http://pastebin.com/3iDeYiU6

Versions:
WirelessCraftingTerminal-1.7.10-rv3-1.5.b
appliedenergistics2-rv3-beta-6
logisticspipes-0.9.3.120
forge-1.7.10-10.13.4.1614-1.7.10-universal

**Comment by p455w0rd** [comment]
Try this hotfix and tell me if you still have problems: http://p455w0rd.net/mc/WCT/WirelessCraftingTerminal-1.7.10-rv3-1.5.3b.jar

**Comment by p455w0rd** [comment]
also note that in that hotfix version the magnet gui checkboxes are not yet functional..working on that atm

**Comment by Thedrummonger** [comment]
Unfortunately still crashes. Very similar crash report.
http://pastebin.com/2rh8RWiu

**Comment by p455w0rd** [comment]
yeah crash looks the same..weird..just installed LP to my dev environment..looking into it

**Comment by Thedrummonger** [comment]
Not sure if it helps any but here is the crash report I get with only Applied Energistics, Logistics Pipes, Buildcraft and Wireless Crafting Terminal installed. Everything still works fine in single player.

http://pastebin.com/A4gZ5XtQ

**Comment by p455w0rd** [comment]
what is your setup like? i need to replicate it to reproduce the bug

**Comment by Thedrummonger** [comment]
http://imgur.com/vxr3PC7

This is the setup that caused the crash in my instance with only the four mods installed.

**Comment by Thedrummonger** [comment]
Here is a better one with pipes labeled
http://imgur.com/9X9j3F0

**Comment by p455w0rd** [comment]
ok, well I just did it and it worked perfectly..are you sure you replaced WCT with the link I sent you? It echnically isn't possible to trigger the PlayerEvent.ItemCraftedEvent since i've added the check for it..also I'm using LP 0.9.3.120..yours seems different..but that shouldn't matter as even in my version, it still an instance of FakePlayer requesting it..the only possibility is that you accidentally didn't replace the old WCT with the one in the link above..i just successfully requested a stack of sticks having only planks in the chest

**Comment by p455w0rd** [comment]
http://imgur.com/d7mpU4f - the setup i used

**Comment by Thedrummonger** [comment]
WirelessCraftingTerminal-1.7.10-rv3-1.5.3b Is the version in my client and server mods folder. As I said this crash only happens on my server. When I attempt this in single player it works fine.

**Comment by p455w0rd** [comment]
oh ok..let me check that then..my bad

**Comment by p455w0rd** [comment]
Use this hotfix =D http://p455w0rd.net/mc/WCT/WirelessCraftingTerminal-1.7.10-rv3-1.5.4b.jar

**Comment by Thedrummonger** [comment]
Works perfectly! Thank you for all your hard work!
