### ISSUE TITLE
Config EndermanDropBoosters described/interpreted wrong

### ISSUE THREAD

**Issue by XoMEX** [p455w0rd/WirelessCraftingTerminal#214]
The [config](https://github.com/p455w0rd/WirelessCraftingTerminal/blob/2da5d1daedc1b1c6971b3c68cf8a170742e200c3/src/main/java/p455w0rd/wct/init/ModConfig.java#L67) describes EndermanDropBoosters as
> Will Enderman randomly drop infinity booster cards on death?

Yet when setting this to true, enderman wont drop infinity booster cards. (When setting to false they drop the cards)

This is due to [this line](https://github.com/p455w0rd/WirelessCraftingTerminal/blob/2f6fa71e1ad792405990de4bd22d9c07f34df532/src/main/java/p455w0rd/wct/init/ModEvents.java#L246): 
```
if (event.getEntity() instanceof EntityEnderman && ModConfig.WCT_BOOSTER_ENABLED && !ModConfig.WCT_ENDERMAN_DROP_BOOSTERS) {
```

My Ideas for fixing this:
* Simply remove the `!` in the Code. By this old configs must be changed
* Change the Description in the Config. By this the variable name will seem counter intuitive.
* Remove the variable and add a new one. By this old configs must be changed, if no *upgrading from old config* handler is added.

**Comment by p455w0rd** [comment]
yeah..derp ty :)
