### ISSUE TITLE
[1.12.2] [3.8.55] ClassCastException

### ISSUE THREAD

**Issue by hypnotizd** [p455w0rd/WirelessCraftingTerminal#216]
Modpack: Modern Skyblock 2 v2.7.2.2

Left Twilight Forest, opened wireless crafting term to grab an item and crash.

[crash-2017-12-05_14.12.51-server.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/1532993/crash-2017-12-05_14.12.51-server.txt)

**Comment by p455w0rd** [comment]
thanks..i'll get a build out soon :)
