### ISSUE TITLE
Wireless Terminal wont show inventory

### ISSUE THREAD

**Issue by 314kojioyama** [p455w0rd/WirelessCraftingTerminal#217]
I sync the WCT(wireless crafting terminal) to the ME system with the security block, but the inventory wont show. the WT(wireless terminal) from AE2 shows all my inventory in my drawers(from storage drawers) and the items in my drives. Figured this was a bug and point it out. I can still pull and craft items from WCT, just no inventory shown. I'm using 30+ mods and all are 1.12.X. I can provide lists and logs if requested.

**Comment by p455w0rd** [comment]
wct version?

**Comment by 314kojioyama** [comment]
just says 1.12.jar

**Comment by 314kojioyama** [comment]
v3.5.43

**Comment by p455w0rd** [comment]
update to latest

**Comment by p455w0rd** [comment]
https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2502510

**Comment by 314kojioyama** [comment]
3.8.55?

**Comment by 314kojioyama** [comment]
ok thankyou

**Comment by 314kojioyama** [comment]
be back with results...

**Comment by 314kojioyama** [comment]
still no inventory. this is my mod folder... actually-additions-1.12, angelringtobauble-1.12-0.3.0.46+306787e, Applied-Energitics-2-1.12.1, Baubles-Mod-1.12, Better Slabs Mod [0.0.6], BrandonsCore-1.12-2.3.4.134-universal, Chameleon-1.12-4.1.3, CodeChickenLib-1.12.1, CXLibrary-1.12.1, Draconic-Evolution-1.12, EnderStorage-1.12, Extra-Utils-1.12, HammerCore-1.12.1-1.9.4.4, Hwyla-Mod-1.12.1, IronChest-1.12, Just-Enough-Items-Mod-1.12.2, Mantle-Mod-1.12.1, MobGrindingUtils-1.12, MooFluids-1.12.2, MoreFurnaces-1.12, OptiFine_1.12.2_HD_U_C7, OreExcavation-1.12, p455w0rdslib-1.12-2.0.22, Reap-Mod-1.12.2, RedstoneFlux-1.12-2.0.1.2-universal, SimpleMagnet-1.12.2, SimpleQuarry-1.12.1, StorageDrawers-1.12, TConstruct-1.12, Tinkers-Addons-1.12.1, TinkerToolLeveling-1.12.1, WirelessCraftingTerminal-1.12.2-3.8.55. is something here not right version for WCT?

**Comment by 314kojioyama** [comment]
this feature isn't game breaking for me, as I carry around the AE2 WT to look for certain things if I'm not doing a recipe.

**Comment by p455w0rd** [comment]
Applied Energistics 2 doesn't have a version `1.12.1`..that's not how their versioning scheme works..latest AE2 is RV5-Stable-3..be sure you're using this..this also requires MC `1.12.2` as does WCT since it depends on AE2..this is an error on your end..the `1.12` in mod filenames indicates that they are for Minecraft `1.12.x`..the number proceeding is the mod version number..just make sure everything is running latest and it'll work..you're also running an outdated p455w0rdsLib, but that should make a difference

**Comment by 314kojioyama** [comment]
that fixed it. I coulda swore that p455 was .24, thanks for the help and quick responses. also moved to the AE file you mentioned and replaced the 1.12 one. been awhile since I modded minecraft, forget that you need to find the latest versions.
