### ISSUE TITLE
[1.12.2][3.8.55] NoClassDefFoundError on Startup

### ISSUE THREAD

**Issue by Daedalus27** [p455w0rd/WirelessCraftingTerminal#218]
I crashed with this report while loading a personal pack (on step 2, I believe): 
[crash-2017-12-16_10.20.04-client.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/1565026/crash-2017-12-16_10.20.04-client.txt)

**Comment by p455w0rd** [comment]
you're using a really old version of AE2..use RV5-Stable-3

**Comment by Daedalus27** [comment]
According to the Twitch launcher, I'm using the latest version, are newer ones not available via the launcher yet?

**Comment by p455w0rd** [comment]
You're using RV5-Beta-10 which is not even available on Twitch Desktop:
![](http://p455w0rd.net/u/18.04.09-16.12.17.png)
I don't know what you're doing...but just update everything...always run the latest before posting bug reports

**Comment by Daedalus27** [comment]
Oh wait, I'm stupid. I apparently installed Llamagistics along with Energistics by accident. I was confused because everything showed as being up-to-date.
