### ISSUE TITLE
[1.10.2] booster card dropping/wct not reconnecting

### ISSUE THREAD

**Issue by InhumanR** [p455w0rd/WirelessCraftingTerminal#219]
My booster card somehow feel out of the WCT and now when I try to open it an error message saying "Wireless Out Of Range.", even when I'm standing right next to my system, I can't open the WCT to be able to replace the card. Please Help

**Comment by InhumanR** [comment]
I made a new WCT and re-linked it to the system and still nothing, not to sure what is going on....

**Comment by Morpheus1101** [comment]
This may seem like a silly question, but do you still have the wireless access point ?

**Comment by InhumanR** [comment]
Yes

**Comment by p455w0rd** [comment]
i take it this is with the 1.10.2 WCT?

**Comment by InhumanR** [comment]
I'm playing Project Ozone Lite, however I just launched it for the first time today and it is working now. Not to sure what happened to fix it but it did.

**Comment by p455w0rd** [comment]
the booster falling out is an old bug..i just need to backport all the stuff from 1.12.2 to 1.10.2...dunno when that will happen...As for not reconnecting to the network..i dunno...this is def a bug..i just don't have time currently to work on outdated MC versions of my mods

**Comment by PseudoResonance** [comment]
The booster card isn't falling out. I'm actually having this same issue with the same pack. I get really bad connection to my AE network even though the network is chunk loaded and has power at all times. The wireless crafting terminal is always charged by my battery as well and is at 100% charged, yet sometimes I click it and it reports in chat that I have no power. Other times, I'm using it and it just doesn't work. No items are listed, as though my network's drives have all gone offline. Other times, it's like that with no items right from the start when I open it. It tends to happen when I'm not actually near my system, such as in another dimension or just far away. I use the FTB Utilities mod to chunkload my network and nothing else seems affected, but the wireless crafting terminal just doesn't connect sometimes.

**Comment by p455w0rd** [comment]
is this still happening in 2.1.41?

**Comment by UncleBJo** [comment]
This is happening to me, yes.
I'm running from the latest release/build of Project Ozone Lite via the Twitch App launcher.

Mincraft 1.10.2 (forge-12.18.3.2511/fml,forge/Forge)
Wireless Crafting Terminal 1.10.2-2.1.41

For me, it works flawlessly while i'm within 3-4 chunks of the center of my base. Once I get a few more chunks away, it becomes inconsistent. As soon as I enter another dimension, it stops working as well.

My symptoms are when I open the WCT, my inventory sometimes pops up for a second and goes away. Sometimes it will only show my craft-able items. Sometimes it simply won't show anything in my AE system, but does always open without any errors (e.g. Out of range, etc.).

I'm happy to provide any further details you may need.

**Comment by p455w0rd** [comment]
join my discord - https://discord.gg/9J7yhUP - when I get time, I'll build you a current dev version and you can test

**Comment by K-9Nina** [comment]
I am playing the same pack as UncleBJo and I am also having the same problem he is having. When I leave and go to a different dimension the terminal will open with no problem, but no items show up. I have been playing for about a week using the WCT with no problem, until today. I noticed that when I return back to base, the light on the wireless connection is off. After a few seconds the light comes back on and everything works fine again. I am able to make a video if that would you see the problem as it happens.

**Comment by p455w0rd** [comment]
sounds like chunk loading issue @K-9Nina
