### ISSUE TITLE
Crash when starting

### ISSUE THREAD

**Issue by kuba12345** [p455w0rd/WirelessCraftingTerminal#22]
When i try to start game it  will crash :(
when i will remove WCT mod 
Game will normally startup without any problem
http://pastebin.com/v1K5pqfB

**Comment by p455w0rd** [comment]
What version (rv2 or rv2 and which revision version)?

**Comment by kuba12345** [comment]
WirelessCraftingTerminal-1.7.10-rv2-1.5.4b.jar
An also i tried
WirelessCraftingTerminal-1.7.10-rv2-1.5.b.jar

**Comment by p455w0rd** [comment]
looking into it now..btw, 1.5 is up on CurseForge..not sure if this will still happen. Also are you playing locally or on a server?

**Comment by p455w0rd** [comment]
oh sry..i just woke up lol...you're using v1.5..i read that wrong

**Comment by kuba12345** [comment]
i am playing locally

**Comment by kuba12345** [comment]
now i found WirelessCraftingTerminal-1.7.10-rv3-1.5.b.jar can it help maybe ?

**Comment by p455w0rd** [comment]
running local tests..give me 5-10mins to try to reproduce the error

**Comment by p455w0rd** [comment]
well 1.5.4b works for me, have you change the config options at all?

**Comment by kuba12345** [comment]
i have something about 2 hours :) for now :)

**Comment by kuba12345** [comment]
config file isn't exist

**Comment by p455w0rd** [comment]
should be in /config/WirelessCraftingTerminal.cfg - if it's not there, then there's something wrong on your end. Also I'm developing on forge v1614..i don't know if that would make a difference..it shouldn't

**Comment by kuba12345** [comment]
Maybe it is solved ..

**Comment by p455w0rd** [comment]
?

**Comment by kuba12345** [comment]
wait 1-5 mins

**Comment by p455w0rd** [comment]
ok

**Comment by kuba12345** [comment]
now i am in phase 5 (previous crashes was in end of phase 1)

**Comment by kuba12345** [comment]
but launching is long .. with 205 mods .. (for me)

**Comment by p455w0rd** [comment]
I have had that happen to me before..it's an error loading the item that holds ti icon for the wireless crafting terminal achievement..but I fixed that before I even put v1.0b on Curse

**Comment by kuba12345** [comment]
ok it seems it is working

**Comment by kuba12345** [comment]
i just update to rv3.. version

**Comment by p455w0rd** [comment]
lol ok..well I'm here if you run into any other problems =D

**Comment by kuba12345** [comment]
sorry for that 30 mins :D

**Comment by kuba12345** [comment]
I have one problem (not with your mod) problem is with ProjectE(Equivalent energistics, Modern alchemy and ProjectEAddon Advanced Alchemy)

If you can't help me just say it :) i will try to solve it alone:)



PS: now i am not home now just say if you can help me :) (sorry for that I write here but i don't found any private message on github.io :)  )

**Comment by kuba12345** [comment]
I am back home 
[crash-2016-05-05_18.07.29-client.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/252201/crash-2016-05-05_18.07.29-client.txt)

**Comment by p455w0rd** [comment]
I'll look into it

**Comment by kuba12345** [comment]
ok thx

**Comment by kuba12345** [comment]
is there anyway to send you private message ? skype, ts3, fb, or anything else

**Comment by kuba12345** [comment]
edit: problem isn't with PEAA (ProjectEAddon Advanced Alchemy) 
i think because this mod is functing normally when i removed equivalent energistics

**Comment by p455w0rd** [comment]
on the main of this repo, there's a "Contact" section

**Comment by kuba12345** [comment]
where is contact section ?

**Comment by p455w0rd** [comment]
http://prntscr.com/b0ybwk

**Comment by kuba12345** [comment]
oh :D

**Comment by kuba12345** [comment]
ok modern alchemy and equivalent energistict = crash

**Comment by kuba12345** [comment]
i will send you updated crashlog ok ?

**Comment by p455w0rd** [comment]
sure

**Comment by kuba12345** [comment]
do you want pastebin or txt ?

**Comment by p455w0rd** [comment]
pastebin always

**Comment by kuba12345** [comment]
http://pastebin.com/dr5mZB1R

**Comment by kuba12345** [comment]
BTW download page of mod :http://forum.minecraftuser.jp/viewtopic.php?f=13&t=19445&start=40
xD

**Comment by p455w0rd** [comment]
I don't know how you go about contacting the Modern Alchemy devs, but at load time a tile entity (specifically modernalchemy/block/tile/TileEmcToRf) isn't loaded(registered) and it is being referenced. So, talk to them..tell them this exact message and they should be able to fix it =]

**Comment by kuba12345** [comment]
ok thx but Modern alchemy devs are japans or .... :D 
便利でいつもお世話になっております。
この度、小規模でほそぼそとですがマルチプレイの際のModpackに入れさせていただきたく思います。
idk copied text :D

**Comment by kuba12345** [comment]
and there is harder error with equivalent energistics (harder for me)

**Comment by kuba12345** [comment]
http://pastebin.com/pnMwZmva

**Comment by kuba12345** [comment]
can't read anything from this .-...

**Comment by kuba12345** [comment]
equivalent energistics is normally functing in project ozone  but not there ..: (

**Comment by p455w0rd** [comment]
with the last one, they are refencing something (item/block) that doesn't exist (at least at the time that they are registering the recipe) .Definitely an EE bug

**Comment by kuba12345** [comment]
anyway to repair it or .. ?

**Comment by kuba12345** [comment]
ow :D https://github.com/Mordenkainen/EquivalentEnergistics/issues/53

**Comment by kuba12345** [comment]
i think there is no solution :(

**Comment by p455w0rd** [comment]
Well, I've helped all I can, sorry :(

**Comment by Mordenkainen** [comment]
@kuba12345 You do realize those are two completely different errors right?
