### ISSUE TITLE
WCT GUI won't open.

### ISSUE THREAD

**Issue by Kasper9999** [p455w0rd/WirelessCraftingTerminal#221]
I have set up the security terminal and wireless access point. The regular wireless terminal from AE2 opens just fine, but when I try to open the GUI it doesn't open. A friend of mine lined a terminal to the same AE2 system and it opens just fine for him.
I have played alot of modpacks and this is the first one im having this problem.

Minecraft version 1.10.2
WirelessCraftingTerminal-1.10.2-2.1.39

**Comment by reifnotreef** [comment]
Might be the same issue I'm having.
I'm replacing the WCT jar with the 1.35 version that linked on curseforge.

I'll report back.

**Comment by reifnotreef** [comment]
I played around with about 3 different versions of AE2, WCT and p455lib.
Nothing worked.

I ended up deleting all related mods and doing a force update through MyM launcher.
Instantly started working next time I launched MC.

**Comment by p455w0rd** [comment]
can you please confirm this happens in 2.1.41

**Comment by Kasper9999** [comment]
I reinstalled the pack and it worked.
