### ISSUE TITLE
Custom Infinity Booster Drops

### ISSUE THREAD

**Issue by Zer0Lyfe** [p455w0rd/WirelessCraftingTerminal#223]
I Think if you specify a certain mob like a Twilight Boss or Draconic Evolution Chaos Dragon. I know people could just add it by using LootTweaker or other mods that do the similar thing but having it in the WCT config would be cool.

**Comment by p455w0rd** [comment]
So, I have given this a lot of thought. And so as to not step on any toes, I have decided against this idea. As you stated, this can be done via another mod. So I feel its only right to use that mod to accomplish this.
