### ISSUE TITLE
[1.10.2 ] Crash when opening universal wireless terminal with crafting module

### ISSUE THREAD

**Issue by aionys** [p455w0rd/WirelessCraftingTerminal#224]
Versions:
appliedenergistics2-rv4-stable-1.jar
ExtraCells-1.10.2-2.4.4a15.jar
WirelessCraftingTerminal-1.10.2-2.1.39.jar

Crash Report:
https://pastebin.com/cHm7uSby

The wireless crafting terminal itself does not crash, but when crafting it into the universal wireless terminal, it does.

https://github.com/ExtraCells/ExtraCells2/issues/517

**Comment by p455w0rd** [comment]
definitely on my end..thanks for reporting..i'll get a fix out asap

**Comment by p455w0rd** [comment]
update to latest 1.10.2 version available on curse :)

**Comment by aionys** [comment]
Nope.

"net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Expansion (thermalexpansion)
Caused by: java.lang.NoSuchMethodError: p455w0rd.wct.api.IWCTItems.wirelessCraftingTerminal()Lp455w0rd/wct/api/IWCTItem;
	at extracells.integration.WirelessCrafting.WirelessCrafting$.getCraftingTerminal(WirelessCrafting.scala:25)"

**Comment by aionys** [comment]
Weird that it's Thermal Expansion that does it, but still getting an error. This time the game won''t even launch.

**Comment by p455w0rd** [comment]
damn that's really weird..the method exists everywhere it's needed (including in IWCTItems.class that is being referenced here) - https://github.com/p455w0rd/WirelessCraftingTerminal/blob/1.10.2/src/main/java/p455w0rd/wct/api/IWCTItems.java#L12

**Comment by aionys** [comment]
Yeah, I saw that. I have no idea.
