### ISSUE TITLE
GUI don't open immidietly when set to mouse keybind.

### ISSUE THREAD

**Issue by Wojbie** [p455w0rd/WirelessCraftingTerminal#225]
Hello.

I encountered this weird bug.
When keybind for opening GUI is set to any of mouse buttons - per example mouse_4 - GUI don't open on mouse press - GUI opens when any key on keyboard is pressed after pressing the mouse keybind.

So to open GUI with mouse_4 keybind you have to press mouse_4 and then any button on keyboard.
There is no keybind collision.

MC: 1.12.2
Forge:  14.23.1.2555
appliedenergistics2-rv5-stable-4
p455w0rdslib-1.12-2.0.25
WirelessCraftingTerminal-1.12.2-3.8.55

**Comment by p455w0rd** [comment]
yeah I'm only listening specifically for keyboard presses which are (in the backend of things) linked somewhere to mouse presses..I've dealt with this with the /dank/null and it currently support keybinds for mouse and keyboard so it should be as simple as essentially copying the code from that mod to this one..thanks for reporting :)

**Comment by PanSzelescik** [comment]
I think this problem still exists in 3.12.97
