### ISSUE TITLE
The Items from this mod don't show in creative inventory search results.

### ISSUE THREAD

**Issue by Wojbie** [p455w0rd/WirelessCraftingTerminal#226]
Hello.

When attempting to search for "wireless" or "booster" (or any valid search that would find this mod items) items from this mod don't appear on results list.
They can be only found by manually going into this mod creative tab.

MC: 1.12.2
Forge: 14.23.1.2555
appliedenergistics2-rv5-stable-4
p455w0rdslib-1.12-2.0.25
WirelessCraftingTerminal-1.12.2-3.8.55

**Comment by p455w0rd** [comment]
this should be relatively easy to fix..thanks for reporting :)

**Comment by timhuff** [comment]
I'm seeing this issue on the version downloaded from curseforge. Is this supposed to be fixed?
