### ISSUE TITLE
[1.10.2]crash at initializing error:java.lang.NoSuchMethodError 

### ISSUE THREAD

**Issue by tonimark** [p455w0rd/WirelessCraftingTerminal#228]
so I got crash with 1.10.2 initializing process here the mods that I got: applied energistics 2 stable and extra cells crash link:https://pastebin.com/XuSQNT62

**Comment by p455w0rd** [comment]
yeah this has been reported on the EC2 tracker...the method that it says isn't there is definitely there..I don't know what happened to drummermc..i'll leave this open until I can talk to him and we can figure this out..thanks for posting

**Comment by p455w0rd** [comment]
should be fixed in next EC2 update
