### ISSUE TITLE
Crash when updating from 2.1.39 to 2.1.41

### ISSUE THREAD

**Issue by Chupp4-Jo3** [p455w0rd/WirelessCraftingTerminal#229]
Just updated to the newest version and get a crash between Mekanism and Extra Cells,

rolled back to 39 and all seems fine again (at least at boot)

crash: https://pastebin.com/MMiZdGKU

**Comment by WreckerOfAll** [comment]
I'm getting the same thing between MoarSigns and ExtraCells.. Not sure what's up but it's also happening when porting between versions. Reverting back to the old one (2.1.39) everything goes back to normal.

**Comment by p455w0rd** [comment]
should be fixed in next EC2 update
