### ISSUE TITLE
Wireless Terminal Texture Copying

### ISSUE THREAD

**Issue by WreckerOfAll** [p455w0rd/WirelessCraftingTerminal#230]
After switching from holding the Wireless Crafting Terminal to holding another item, the item's texture does not show, but instead the wireless crafting terminal's texture. This happens with seemingly any item, and only is fixed by holding an empty hand then going back to the item. See screenshot:

![wirelessterminalbug](https://user-images.githubusercontent.com/19937242/35063570-79c3863a-fb95-11e7-9b62-e672046e31a3.PNG)

**Versions:**
AE2: RV4-Stable-1
WCT: 1.10.2-1.39
P455w0rdslib: 1.10.2-1.0.30

**Comment by p455w0rd** [comment]
ae2 version? wct version? p455w0rdslib version?

**Comment by WreckerOfAll** [comment]
Edited

**Comment by p455w0rd** [comment]
thanks for clarifying :)

**Comment by p455w0rd** [comment]
can you please confirm this happens with 2.1.41

**Comment by WreckerOfAll** [comment]
Can confirm, bug recreates itself in 2.1.41 with same AE2 version

**Comment by p455w0rd** [comment]
does it do this with the AE2 wireless terminal? the code is identical as far as this is concerned and I am unable to duplicate

**Comment by p455w0rd** [comment]
i'm gonna close this as it doesn't happen in a normal forge environment..i believe it must be mod interaction somewhere down the line
