### ISSUE TITLE
Creative WCT does not work across dimensions / out of range

### ISSUE THREAD

**Issue by BrisingrAerowing** [p455w0rd/WirelessCraftingTerminal#234]
Is that intended? I would think that it would have infinite range / work across dimensions without using booster cards.

**Comment by p455w0rd** [comment]
def not intended and I even tested in SMP lol..but might have forgotten after updating to Ae2 RV5-Stable-8 in my dev env...I'll take your word for it and mark this as a bug..thanks for reporting!

**Comment by p455w0rd** [comment]
Just tested in SSP and SMP in my dev env, and then set up a local obf server and did same tests..works in all situations. Is it possible that you're network just isn't chunk loaded?

**Comment by p455w0rd** [comment]
I mean if it is chunkloaded for sure, please give more info (pack/other mods, ae2 version, forge version)

**Comment by BrisingrAerowing** [comment]
That particular network was chunkloaded (it existed in the Random Things spectral dimension, which I chunkloaded). I deleted that world after a error in another mod broke it (deleted everything), and I haven't set up a new one yet. I'm going to try and see if it is related to the dimension it is in.

**Comment by BrisingrAerowing** [comment]
It doesn't work for me in the overworld either. I just get the out of range message.

**Comment by p455w0rd** [comment]
i need context..mod versions, forge version, pack, etc..if you use twitch app and just install WCT in a custom instance (which automatically downoads AE2 and pwlib), it works, so this is invalid unless you can help me reproduce

**Comment by BrisingrAerowing** [comment]
I forgot chunk loading in my previous test. I'm testing without Extra Cells right now, to see if that has anything to do with it.

**Comment by BrisingrAerowing** [comment]
I'm at a loss as to what caused this. If I figure anything else out I'll post it here.

**Comment by BrisingrAerowing** [comment]
I discovered the cause: Setting 'UseOldInfinityMechanic' to true breaks the Creative WCT. Having it false makes it work normally.

**Comment by p455w0rd** [comment]
ohhh...good catch :) thank you for figuring it out

**Comment by BrisingrAerowing** [comment]
It finally dawned on me that that may have been the issue. I am kind of kicking myself for not seeing that before.

**Comment by p455w0rd** [comment]
it's live
