### ISSUE TITLE
[1.10.2] Crash on Startup

### ISSUE THREAD

**Issue by surfersmurf** [p455w0rd/WirelessCraftingTerminal#238]
Hi,

I'm getting a crash when starting the game. Seems like the same crash occured a few weeks ago with Mekanism, but this time it seems like it's Thermal Expansion.

https://pastebin.com/Wm1tXdwq

**Comment by p455w0rd** [comment]
this issue isn't mek or thermal..its extracells.. @DrummerMC seems to have gone MIA again..i'm pretty sure the version of EC2 on the EC2 repo has the fix in place, he just needs to push to curse
