### ISSUE TITLE
Issue with running Wireless Crafting Terminal & Mekanism?

### ISSUE THREAD

**Issue by RoboJackPlays** [p455w0rd/WirelessCraftingTerminal#239]
I get this crash report whenever I run the mod with Mekanism.

Running the latest stable version of all mods:
- WirelessCraftingTerminal
- Mekanism
- ExtraCells

Running on Minecraft 1.10.2: https://pastebin.com/Yu0TMmrk

**Comment by p455w0rd** [comment]
duplicate of #238 #232 #229 #228 #224 ..you get the point..FFS check the issues..this is on EC2 and I cannot push to curse..for now remove EC2
