### ISSUE TITLE
wireless crafting terminal causes crash with extra cells

### ISSUE THREAD

**Issue by DerpyNinja476** [p455w0rd/WirelessCraftingTerminal#240]
hello, i have a problem with the mods wirelesscraftingterminal and extracells2 that when i join my single player world on a custom modpack, when i try to make a crafting table, the third piece of wood that i place in the crafting grid, the whole game freezes and crashes. It also happens with the applied energistics 2 crafting terminal and when i put any three items in the grid. 
i asked around on the forge forums and it said that i should ask the mod authors
here are the crash report and logs.
please fix this because applied energistics2 is a great mod with extra cells and wireless crafting terminal.
https://pastebin.com/FdKkawN4
https://pastebin.com/UG953bNR

**Comment by p455w0rd** [comment]
for the first log, this is EC2 and the dev has gone MIA..Fluid stuff is being added to AE2 base..for now all you can do is remove EC2 (refer to https://github.com/p455w0rd/WirelessCraftingTerminal/issues/239#issuecomment-366486685 for all the duplicates)

the 2nd report is either CCL or DE @covers1624 @brandon3055

**Comment by DerpyNinja476** [comment]
the only reason it is a duplicate is because i was told to ask the mod authors to fix the bug on the forge forums

**Comment by p455w0rd** [comment]
yup..you stated that...i was just replying

**Comment by p455w0rd** [comment]
Ok so YeH came up with a perfect solution..ill get this fixed on my end when I get home

**Comment by DerpyNinja476** [comment]
ok thank you for the big help. extra cells and wct are great mods.

**Comment by covers1624** [comment]
The second crash report is related to the fact that you don't have CCL installed fro BrandonsCore's Coremod. This has since been removed in 1.11.

**Comment by DerpyNinja476** [comment]
first, im using 1.10.2, second i do have ccl installed

**Comment by p455w0rd** [comment]
@DerpyNinja476 don't be a prick..closing this....open it on brandon's tracker and try being thankful for what he does before coming off like something is owed to you.
