### ISSUE TITLE
WCT 3.9.60 - Magnet Card stops inserting items to network after second network constructed in world

### ISSUE THREAD

**Issue by Johnyknowhow** [p455w0rd/WirelessCraftingTerminal#241]
I've got a fairly prominent issue with the WCT magnet card installed on the FTB Revelations 1.5.0 modpack.

Upon creating a new world, the card works fine without an issue. Adding an item to the whitelist causes it to function fine. However, it seems like destroying a network and then building a second one and linking the WCT causes the card to just... stop working.

The card is capable of sucking up nearby items, but the filter doesn't seem to work, and nothing is ever inserted into the network. Creating a second world with all of the same mods works fine until you destroy the network and rebuild it.

[Here's a 5-minute video showcase of the issue at hand.](https://youtu.be/CqTGaCJThok)

After the events in the video, I did some more hands-on testing. 

It seems like removing the power and then re-introducing it doesn't cause a problem. Neither does removing the security terminal and replacing it. However, moving the controller causes the card to break. For whatever reason after the video when I moved the controller the card fully broke, now it won't even magnetize items.

I have no idea what would be causing this. In my survival world, I think what caused the network to go haywire was the fact that it was being chunk loaded by an IC2 chunkloader to attempt to keep the network functioning even while I was away. I had a few hitches setting that up and I believe it may have been dropped out of a loaded chunk and reloaded, causing it to experience the bug.

That still doesn't explain why the bug is occurring, though.

I might try doing a fresh forge install and working with just this and AE, to see if it's a mod conflict (probable), or what.

Let me know if there are any logs or whatnot I can send over to help you out.

**Comment by p455w0rd** [comment]
this might be the best issue by anyone XD thanks for the awesome detailed explanation..looking into this now

**Comment by p455w0rd** [comment]
so the initial object the magnet uses to access the network was being cached..this was silly...this is fixed in 3.9.62

**Comment by Johnyknowhow** [comment]
Sounded like it would be a caching issue since re-installing the mod during a modpack update would cause it to function again, albeit temporarily. 

Thanks for the quick response and patch! It's always nice to have people around to fix problems. :)
