### ISSUE TITLE
Magnet card crash

### ISSUE THREAD

**Issue by pinocchiowasjew** [p455w0rd/WirelessCraftingTerminal#242]
Whenever I hold shift while hovering over the magnet card in the slot next to the crafting grid in the wireless crafting terminal menu, the game crashes with the following [report](https://drive.google.com/file/d/1EAmhPq6RgogrNngNh8VhnxYZfJ7VDvYB/view?usp=sharing).

**Comment by p455w0rd** [comment]
what key do you have assigned to open the magnet GUI?

**Comment by p455w0rd** [comment]
is this a key on your mouse?

**Comment by p455w0rd** [comment]
i'll just accept this as a bug..if you want to test a dev version before I ush it to curse hop on my discord ( https://discord.gg/9J7yhUP ) and I'll ship you a copy..I change the method I use to fetch the bound button name...

**Comment by pinocchiowasjew** [comment]
Yes, it is a key on the mouse, and thanks.
