### ISSUE TITLE
WCT Server crash

### ISSUE THREAD

**Issue by flintnsteel** [p455w0rd/WirelessCraftingTerminal#247]
Version WirelessCraftingTerminal-1.12.2-3.9.62

If the WCT is on hotbar and is open, if mouse is hovering over an empty inventory slot, and the hotbar key with the terminal is pressed, terminal moves to new spot and crashes server.

Verified multiple times, different clients, reproduceable

**Comment by p455w0rd** [comment]
thanks will look into this when i get a chance

**Comment by p455w0rd** [comment]
found the issue..it exists in AE2 as well..fixed on my end and I notified yueh in my discord, thank you!
