### ISSUE TITLE
Issue with JEI crafting table auto fill

### ISSUE THREAD

**Issue by Dalethium** [p455w0rd/WirelessCraftingTerminal#248]
#### Description
I use the universal wireless terminal from extra cells 2, and in the crafting menu when using jei to auto fill recipes with the plus button, it only auto fills when in the same dimension as the actual ae system.

To rephrase, using jeis build in feature to click the plus button and have items moved from the inventory to the crafting grid does not work outside the dimension that the ME Controller/Drives are in. 

#### Environment
[Full mod and env list with versions](https://pastebin.com/iB5mzR6k)
- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.2.2611
- Extra Utilities 2 Version:  1.0 (According to mod meta, it is the latest release as of 2018/04/07)
- AE2 Stuff Version: 0.7.0.4
- JEI Version: 4.8.5.159

I also reported this on [Applied Energistics](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3455) & [Extra Cells](https://github.com/ExtraCells/ExtraCells2/issues/547) as I am not sure which mod it belongs with.

**Comment by p455w0rd** [comment]
it's working in WCT, not to rule out that it _might_ be on WCT's end, but atm, DrummerMC (EC2 dev) is MIA..I'll look into this further when I have time

**Comment by BrockWS** [comment]
Strange, i'm not having any issues like that.
Looks like EC2 CraftingTerminal#checkForBooster does not support the new Infinity mechanic.

**Comment by p455w0rd** [comment]
this is using the jar as a lib in dev..not the src from git..I'm working on getting the src running in dev atm..and checkForBooster is handled on WCT's end..not EC2...EC2 just passed the method on to WCT (otherwise the universal terminal in crafting mode wouldn't open beyond the WAP range and def not in other dims)

**Comment by p455w0rd** [comment]
you're welcome to join and discuss this in real time on discord: https://discord.gg/9J7yhUP
