### ISSUE TITLE
Feature Request: Infinite Power for Terminals

### ISSUE THREAD

**Issue by HyperMan19680** [p455w0rd/WirelessCraftingTerminal#25]
Yeah, I basically had trouble with the Terminal losing power rapidly, and I Want to request a way to keep the terminal fully charged at all times, preferably Creative Mode only.

**Comment by p455w0rd** [comment]
Sure, I'll add this before next update. It will be creative mode only though. Losing power rapidly shouldn't be an issue at this point so long as you have the Infininty Booster Card installed. I changed the way power drains when it is installed to a constant 1AE/t (20Ae/second) no matter what range. I have pondered the idea of adding a sort of "capacitor" card with extra energy storage, but with so many other mods that provide things like this, I don't know if I'll do that or not..
