### ISSUE TITLE
crafting keeps reseting

### ISSUE THREAD

**Issue by JoeNoIce** [p455w0rd/WirelessCraftingTerminal#250]
i used this mod to make one storage bus and ever since then even when clearing the crafting terminal the recipe keeps coming back https://i.imgur.com/zd9Cri0.jpg

 this problem causes resource loss.

**Comment by Fuzsoo** [comment]
I have the same problem and you can duplicate items with this bug as well. [1.12.2 - 3.9.62 & 3.9.64]

When you have the WCT in hand it works normaly but when you equip it in the baubles slot on your head it will remember whatever was in the crafting area the last time you had the WCT in your hands. 

Even when you change or empty the items out in the crafting area ,when you reopen the WCT in baubles slot it will change them back in. making you able to lose and duplicate items.

**Comment by ruifung** [comment]
Looks like item NBT isn't being updated while in baubles slot...?

**Comment by ruifung** [comment]
Likely related #258 #160

**Comment by p455w0rd** [comment]
Yeah I noticed myself..happens with other slots...trying to figure it out

**Comment by ruifung** [comment]
Other slots? You mean not just bauble slots?

**Comment by p455w0rd** [comment]
no..what I mean i when it's used as a bauble..other slots don't keep contents..like trash & view cells...I'm working on it :)

**Comment by p455w0rd** [comment]
I have fixed it :D
