### ISSUE TITLE
Checkboxes in Magnet Filter GUI are broken

### ISSUE THREAD

**Issue by aaronhowser1** [p455w0rd/WirelessCraftingTerminal#256]
This is what they show instead of a checkmark:
![image](https://user-images.githubusercontent.com/15698722/39554664-cbe60194-4e39-11e8-8934-8c12e0fbe791.png)

**Comment by p455w0rd** [comment]
this only happens for some people..it's weird..has to be something with the character set..I'll have to think on a way to fix this..might have to end up using PNGs

**Comment by aaronhowser1** [comment]
In case this is important, I was using Faithful 32x Modded Edition

**Comment by p455w0rd** [comment]
so..this would be on the resource pack author to add proper char support..I still do plan to change the checkboxes when I get time from characters to pngs..but that'll be a while yet

**Comment by p455w0rd** [comment]
swapped unicode checkboxes for ascii "x"
![](https://puu.sh/CeDQb/1dbbbfab72.png)
