### ISSUE TITLE
Mystery slot in WCT inventory

### ISSUE THREAD

**Issue by aaronhowser1** [p455w0rd/WirelessCraftingTerminal#257]
There's a slot [slightly overlapping the first slot in the player inventory](https://i.imgur.com/bE2hp0w.png). It isn't a texture issue, [there's a normal slot there too](https://i.imgur.com/0g1hnCI.png). If you hover over the middle, [both are highlighteed](https://i.imgur.com/k6kOlb9.png).

**Comment by p455w0rd** [comment]
i recently came across this myself..i believe it's the booster card slot when booster card has been disabled in config (technically it's supposed to be a hidden slot)..thanks for reporting :)

**Comment by p455w0rd** [comment]
yup that was it.,. :)
