### ISSUE TITLE
item dupe/loss bug with ender io wireless charger

### ISSUE THREAD

**Issue by zetx** [p455w0rd/WirelessCraftingTerminal#258]
Hi, this set of bugs (#160) have resurfaced. Reproduction should be the same as previous, please see these gifs for more detail: [Losing the item](https://gfycat.com/MediumSmugIggypops) and [Duping the item](https://gfycat.com/DefiniteFavorableBanteng)

Minecraft: 1.12.2
WirelessCraftingTerminal: 3.9.64
Using the Enigmatica 2 modpack: 1.36

Thanks!

**Comment by Fuzsoo** [comment]
I only have this problem when i have the WCT in the baubles slot. when i have it in my hotbar/bag it works normally.

**Comment by desvandev** [comment]
So this is how I lost my Grandmaster Pickaxe...
I'm having the same behaviour in FTB Revelation.

**Comment by p455w0rd** [comment]
replicated :) thanks for the report

**Comment by p455w0rd** [comment]
also happens with view cell slots :/ again..only when in bauble slot...working on it

**Comment by p455w0rd** [comment]
closing as this is a dupe of #250
