### ISSUE TITLE
Server crash bug.

### ISSUE THREAD

**Issue by Curiosity1836** [p455w0rd/WirelessCraftingTerminal#261]
Me and a mate have found when playing on the FTB revelations pack when you have the terminal in the number 2 slot and press shift + 2 to get the @ symbol it crashes the server. Its probably just putting the terminal inside itself.

**Comment by p455w0rd** [comment]
revelations is using an outdated version, can you please try this version: https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2552069

**Comment by Curiosity1836** [comment]
Ah yep that did it thanks.
