### ISSUE TITLE
Chunkloading alternative

### ISSUE THREAD

**Issue by 016Nojr** [p455w0rd/WirelessCraftingTerminal#262]
Maybe instead of having chunkloading the ME controller as a config option only limited to ops, maybe add a block that can be attached to the ME-System that makes the Controller chunkload?

**Comment by p455w0rd** [comment]
well..ultimately, due to resource usage, it's up to the server owner whether or not they want to dedicate those resources to a chunk being loaded..I could still add a block, but it wouldn't work if config had it disabled

**Comment by 016Nojr** [comment]
This is true, I dont mind the config staying to disable the block. Having a block would open up the possibility for normal players to chunkload their controller with WCT aswell, not just ops.

**Comment by p455w0rd** [comment]
if the config is enabled, then all controllers are chunkloaded currently, not just ops' controllers

**Comment by 016Nojr** [comment]
Oh
