### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by tyler489** [p455w0rd/WirelessCraftingTerminal#263]
When you have Search by mod name in jei with Prefix @ 
typing @ in the serach bar of the wireless crafting terminal results in server crash for nbt overflow
http://termbin.com/eobo

**Comment by p455w0rd** [comment]
is the pack on curse? if so, what pack? if not, can you upload the pack in zip form somewhere (mainly just the mods and config folders (and scripts if CT installed)...I need to know that this is only happening with WCT and not with normal AE2 terminals or the AE2 wireless terminal

**Comment by tyler489** [comment]
in the ftb pack Continuum 1.12.2

this behavior doesnt not occurr with ae2 terminals or wireless terminals

**Comment by p455w0rd** [comment]
ok, thank you :) i will try to replicate the bug and if I can, I'll get a fix out asap and notify the FTB devs

**Comment by tyler489** [comment]
i have Cross Referenced it on there github tracker here is another crash report of the same thing http://termbin.com/6w1l

**Comment by p455w0rd** [comment]
is this SMP? if so, can you load up a single player world and test? i found this doun't happen in SSP..downloading the server files now to test SMP

**Comment by p455w0rd** [comment]
also what is you search box mode set to?
![](https://i.imgur.com/vMXG103.png)

**Comment by tyler489** [comment]
Sync auto i was going to search @rftools but as soon as i hit @ server crashed

**Comment by p455w0rd** [comment]
did you add any mods to the pack?

**Comment by tyler489** [comment]
Nope

**Comment by tyler489** [comment]
Now im unable to reproduce this. managed to do it 3 times before reporting... went to record a video and cant reproduce ;(

**Comment by p455w0rd** [comment]
weird..i'd really like to figure out what's going on with this
