### ISSUE TITLE
Can't look at active crafting tasks through the WCT

### ISSUE THREAD

**Issue by aaronhowser1** [p455w0rd/WirelessCraftingTerminal#264]
Clicking the button at the top right of the WCT to see what's being autocrafted by the ME system just closes the WCT without opening the autocraft GUI.

**Comment by p455w0rd** [comment]
this used to be an issue, but I have since fixed it..what version are you running?

**Comment by aaronhowser1** [comment]
I'm using 3.9.64

**Comment by aaronhowser1** [comment]
This inexplicably stopped happening, I don't think anything changed at all. No idea why, but hey, if it works it works.
