### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Rocky28447** [p455w0rd/WirelessCraftingTerminal#265]
Hovering your mouse over a grid slot in the crafting grid in the terminal and hitting the number key associated with the hotbar slot that the WCT is in (basically putting the WCT into its own crafting grid) will crash the game. This will also destroy the WCT as when you rejoin the game, since the WCT was inside its own crafting grid and the terminal window closed, it is irretrievable.

MC version 1.12.2

**Comment by p455w0rd** [comment]
confirmed..thanks for reporting and sorry this happened :(

**Comment by Rocky28447** [comment]
No problem :D
