### ISSUE TITLE
Allow being placed into bauble slots other then Head

### ISSUE THREAD

**Issue by ruifung** [p455w0rd/WirelessCraftingTerminal#266]
This would allow you to wear both the WCT and The One Probe as a bauble.

**Comment by p455w0rd** [comment]
hmm..i like the idea, just means I gotta do rendering for each slot..would be low priority, but i do like the idea

**Comment by RalphFox** [comment]
I don't know if I should request it to extracells2 or here, but I'd like also to request to allow the wireless universal terminal also to be able to be put on baubles slot.

**Comment by ruifung** [comment]
@RalphFox That one you should probably request from ExtraCells I think.

**Comment by p455w0rd** [comment]
Just an example showing all possible slots (other than body, in which case the WCT is rendered on the back of the player)...all mods depending on my new library (AE2WTLib), will automatically have the same functionality..also, I will be creating the "Wireless UltimateTerminal" in AE2WTLib which will essentially do what the Universal Terminal did in EC2, and it will also support this. It will be up to dependent mods to decide which Baubles slot(s) they support. To keep people happy, I will be allowing Wireless Crafting Terminal and Wireless Fluid Terminal to be used in any Baubles slot
![](https://www.p455w0rd.net/mc/img/multibauble.png)

**Comment by ruifung** [comment]
\o/ Its been a while since I opened this issue. Heh. I don't even play mc much these days.

I'm curious though, how extensible is this if say... I wanted to integrate the ec2 gas terminal into it with an addon mod for an addon mod.
