### ISSUE TITLE
Cannot autocraft though WCT

### ISSUE THREAD

**Issue by randomlypickedname** [p455w0rd/WirelessCraftingTerminal#267]
It seems I can't autocraft anything through a WCT. I've tried spawning a new one and linking it, and I've tried breaking and replacing my ME controllers, and neither work, though I am able to craft just fine through any AE2 terminal.

https://imgur.com/a/EvZ8o2G

WCT version 3.9.67, AE2 ver. rv6-alpha-1, Enigmatica 2: Expert modpack (NillerMedDild/Enigmatica2Expert#140)

**Comment by codeka** [comment]
I'm also getting this. I also have an infinity booster card, and when I try in another dimension, I get a crash:

https://paste.ee/p/ClOmm

**Comment by codeka** [comment]
Looks like this is caused by https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/3434 ?

**Comment by codeka** [comment]
Looks like this is an incompatibility with AE2 rv6.alpha, I reverted to rv5.stable in my local install and it works again.

**Comment by p455w0rd** [comment]
yeah.some stuff was changed..thanks for the reports :D

**Comment by p455w0rd** [comment]
can one of you please join my discord and ping me and I'll send u a copy with this fixed..I just want confirmation that it is indeed fixed https://discord.gg/9J7yhUP
