### ISSUE TITLE
WCT wont show contents

### ISSUE THREAD

**Issue by ZaosDaOne** [p455w0rd/WirelessCraftingTerminal#269]
the WCT wont show the contents of the ME it opens but it is completely blank however regular wireless terminals work fine AE2 version = rv5 stable 11 WCT version= 3.6.47 p455w0rd version = 2.0.29

**Comment by p455w0rd** [comment]
yeah..u gotta use a matching WCT<->AE2 version..you're running AE2 RV5-Stable-11 when WCT 3.6.47 is made for AE2 RV6-Alpha-2..this is not a bug at all..just the erroneous method curse uses in the twitch desktop app to check that mods are "up to date"..if u go to the AE2 tab and select "VERSIONS"..you notice 2 newer versions..either downgrade WCT or update AE2

**Comment by ZaosDaOne** [comment]
i am unable to update AE2 as it starts causing issues and crashes before it starts on the WCT page i dont see any lower WCT versions
