### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by ZaosDaOne** [p455w0rd/WirelessCraftingTerminal#270]
When i Downgrade my WCT to match my AE2 version the client crashes before even opening the start menu 
[crash-2018-07-12_17.44.31-client.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/2190401/crash-2018-07-12_17.44.31-client.txt)

**Comment by p455w0rd** [comment]
you downgraded way too far..WCT doesn't even have the class being reference here in it anymoresorry this is happening..just update to latest of all of them and it will work..once RV6-Stable-1 is released this won't be happening anymore as I have decided to follow AE2's release process so WCT & AE2 always match in Twitch..until then thjis is going to be borked..again...this is the fault of curse...ditch twitch client and just download the latest versions of all mods..it'll work

**Comment by p455w0rd** [comment]
I can create a Twitch instance if you want

**Comment by ZaosDaOne** [comment]
i dont use twitch can i just get the latest versions link of all 3
