### ISSUE TITLE
[1.10.2]Discarding wct while quickly opening can retain gui, this gui can make items double.

### ISSUE THREAD

**Issue by tanyuguai** [p455w0rd/WirelessCraftingTerminal#272]
Opening wct and then quickly discarding it can preserve the gui, which can take away the items in the card and the composition bar without consuming the contents of the discarded wct.

**Comment by p455w0rd** [comment]
with all of the projects i maintain and 1.13 forge coming out likely not long after the new year..i just don't have time to maintain this obsolete version anymore, sorry
