### ISSUE TITLE
Auto-Crafting Issue

### ISSUE THREAD

**Issue by ZombieKonsti** [p455w0rd/WirelessCraftingTerminal#274]
Everytime I try to Auto-Craft anything in the WCT, the server crashes. Doesn't occur if I am running a local World or crafting in the standart Ae2 Terminals.
Here's the Server Crash Report:  https://hastebin.com/obuzubovuf.pl
Tell me if you need some extra logs or such things.

Note: I'm playing on the newest Version of RV3

Sorry for my bad English. It would be really nice if you could fix this

**Comment by p455w0rd** [comment]
![](https://i.imgur.com/sdsoLkh.png)

**Comment by ZombieKonsti** [comment]
oh wait I meant the newest rv6 version, what i meant to do?

**Comment by p455w0rd** [comment]
are you also using ae2 rv6?

**Comment by ZombieKonsti** [comment]
yes

**Comment by p455w0rd** [comment]
k, ty...l will test now
