### ISSUE TITLE
Broken? Infinity Booster Card Config

### ISSUE THREAD

**Issue by Cazadorsniper** [p455w0rd/WirelessCraftingTerminal#276]
# If true, then simply inserting 1 Infinity Booster Card into the slot, will give limitless infinite range. [default: false]
B:UseOldInfinityMechanic=true

It seems the old Infinity Booster Card mechanic doesn't work at all.

**Comment by MrNinja93** [comment]
May be a config broken entirely, I've tried to disable controller chunkloading in the config ``B:EnableControllerChunkLoading=false`` and it's continuing to chunkload.

**Comment by p455w0rd** [comment]
Caz should've closed this..we discussed in dm and this is invalid

**Comment by p455w0rd** [comment]
Also I added the chunk loading config at tfox's request...ftb team verified it works...

**Comment by p455w0rd** [comment]
Is your controller in spawn chunks?

**Comment by joshuasuperboy** [comment]
why not just chunk load the controller with chicken chunks

**Comment by p455w0rd** [comment]
If ignorance is bliss, Mr joshuasuperboy is all shits n giggles right now..
