### ISSUE TITLE
Shift + Left Click Inserting of Items

### ISSUE THREAD

**Issue by Rasaxe** [p455w0rd/WirelessCraftingTerminal#277]
I don't know if this has already been posted about. I couldn't find it, and I'm also not sure if it's been fixed or changed already. I'm playing the newest release of FTB Revelation modpack. When I use a regular AE2 wireless terminal I can hold shift and hold down left click and just hover over the items I want to insert into the me system. But with the WCT it doesn't work. It only inserts the first item/stack that I left click on. And when still holding down shift and left click and hovering over other items/stacks nothing happens.

**Comment by Rasaxe** [comment]
Found out you can double click the items instead and it will transfer all of them instantly. But still would like it to work the other way aswell. Not really needed though

**Comment by p455w0rd** [comment]
This is a feature of mousetweaks...ae2 doesn't disable it...i do cuz of false reports..this will not be changed
