### ISSUE TITLE
NPE with Wireless Crafting Terminal

### ISSUE THREAD

**Issue by Shybella** [p455w0rd/WirelessCraftingTerminal#280]
#### Description

Server crash with Wireless Crafting Terminal steps to reproduce below.

1. Obtain a Wireless Crafting Terminal
2. Open the Wireless Crafting Terminal (Make sure it's linked)
3. Type 64 quickly with auto-search enabled

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-11
- Forge Version: 2739

Crash Report: https://pastebin.com/raw/jn9WtSMt

If you need any additonal information, let me know.

Thank you.

Originally opened below thinking this was part of AE2.

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3693

**Comment by p455w0rd** [comment]
you are welcome to join my discord - http://p455w0rd.net/discord - ive just spent ~3 updating another project, and its break time for me atm..i'll be back in 15mins or so

**Comment by Shybella** [comment]
Is this fixed now?
