### ISSUE TITLE
WCT cannot calculate crafting plan with 2+ cpus

### ISSUE THREAD

**Issue by infogulch** [p455w0rd/WirelessCraftingTerminal#281]
When using a network with 2 or more separate crafting cpus the "calculating crafting plan" step never completes after clicking next. I first encountered this in the latest Foolcraft 3 modpack update (reported on their [issue tracker here](https://github.com/scalda/Foolcraft_3/issues/286)), and I have reproduced it here with the minimal set of mods.

Steps to reproduce the bug:
1. Create a network with at least 2 cpus and at least one pattern available to craft
2. Attempt to begin a craft using the pattern
3. After clicking "Next", the "Crafting Plan -- Calculating Please Wait..." message appears and never completes.

Things that do not trigger the bug:
1. Having only 1 crafting cpu in the network
2. Using the built-in AE2 terminals

Here is a short 50s video demonstrating the bug: https://media.giphy.com/media/1AiIy09CjNeCU97UUS/giphy.gif

Affected versions and packs:
1. plain-jane setup with *only*:
  a. Minecraft 1.12.2
  b. Forge 14.23.4.2759
  c. Applied Energistics 2 rv6-alpha-3
  d. p455w0rdslib-1.12-2.0.32
  e. Wireless Crafting Terminal 2 1.12.2-3.9.67 (This is the latest by date, and the latest marked stable according to the [releases on curseforge](https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files))
3. Foolcraft 3 1.5.1, with many mods, with the only difference from plain-jane being:
  a. Forge 14.23.4.275**8**
4. Foolcraft 3 1.5.0

Unaffected versions:
1. Same as plain-jane except
  a. Wireless Crafting Terminal 2 1.12.2-3.9.**71** (This is the latest by version *number* but is not the most recent and is not marked stable. The releases are kindof confusing tbh.)

**Comment by p455w0rd** [comment]
yes, you can thank curse for the confusion..they don't allow us to specify specific versions to depend on..i had to do it this way...please don't rely on curseforge release version for whether or not a mod is stable...just get the latest for whatever you are doing...in this case you're using AE2 RV6, so you would need to have the lastest RV6 version of WCT (i posted an update here yesterday to work with RV6 alpha 4 [latest AE2 alpha release]: https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2612298 ) - once AE2 releases a "RV6-Stable-1" version, this will not be a problem..until then, there will likely continue to be confusion..I just tested this in RV5 and it's not an issue, going to test in RV6 now...sorry for the confusion and thank you so much for the detailed report!

**Comment by p455w0rd** [comment]
just completed testing using the following crafting cpu setup:
![](https://user-images.githubusercontent.com/12187748/44991504-455a4600-af62-11e8-829e-57f036dfdf3e.png)
worked fine.please update AE2 to latest RV6 (alpha-4 - https://minecraft.curseforge.com/projects/applied-energistics-2/files/2612061 ) and update to latest WCT (link in previous comment) and report if you still get errors with autocrafting...for now, it seems to work fine for me at least

**Comment by infogulch** [comment]
Ah, so AE2 rv6 alpha 3 broke compatibility, which broke WCT. (It is an alpha after all.) And since curseforge doesn't allow you to specify dependent versions we couldn't tell.

I wonder if it would be beneficial to list the last tested ae2 version in the file name like you do with minecraft. But then I guess if a dependency updated and *didn't* break anything it might not be clear that it still works fine... I dunno maybe not.

I guess ideally curseforge would have a way to specify dependencies, and then we can do things like:
* download a specific version of a mod with all of the correct dependencies at once, even for older versions
* specify a version range and let a dependency resolution algorithm update a whole pack at once, with minimal breakage

Man, wouldn't that be nice.

Thank you for updating!

**Comment by p455w0rd** [comment]
i do this ever since this whole RV5/RV6 thing became an issue lol
![](https://puu.sh/BpBjC/ae256a65fd.gif)
