### ISSUE TITLE
crash when trying to pull items from a system via the wireless crafting terminal

### ISSUE THREAD

**Issue by scalda** [p455w0rd/WirelessCraftingTerminal#282]
Hi please find the attached crash report and some information

Pack: FC 1.5.2
WCT: WirelessCraftingTerminal-1.12.2-3.9.67
AE2: appliedenergistics2-rv6-alpha-4
Forge: forge-1.12.2-14.23.4.2760

I set up a small test network as I got this reported to me via my FoolCraft issues page (https://github.com/scalda/Foolcraft_3/issues/306)

And when you try and pull items from the system via WCT i get the crash report below
any questions, please ask.

[crash](https://paste.dimdev.org/itiropekak.mccrash)

Regards
Scalda

**Comment by p455w0rd** [comment]
update wireless crafting terminal to latest RV6 version: https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2612298 (you're using 3.9.67, you need 3.10.80)
also, the 3.9 in the version indicates AE2 RV5, 3.10 indicates RV6

on CurseForge I have also added the proper AE2 RV version for WCT:
![](https://puu.sh/Bvrsk/ebe3e23e94.gif)
