### ISSUE TITLE
WCT changes to the fluid version if in a Baubles slot when a Wireless Fluid Terminal is opened

### ISSUE THREAD

**Issue by Revvilo** [p455w0rd/WirelessCraftingTerminal#285]
Took me a little while to work out why my WCTs were turning into fluid ones, but I must admit I had a giggle when I found out. Baubles must have some beef with your mod... 😅
## Issue Summary
If you have the Wireless Crafting Terminal in a **Bauble slot** and you open/use a Wireless Fluid Terminal, it will change the **existing WCT in the Baubles slot** into a Wireless Fluid Terminal.
* [GIF of it happening](https://imgur.com/a/1uuMIOB)
## Reproduction
- Place a WCT into the head Bauble slot
  - _does not have to be linked or charged_
- Use a WFT in your hotbar to open the GUI
  - _the fluid terminal does not need to be linked to an ME network, but does need to have enough power_
- Check your Baubles inventory; the WCT should now be an **exact duplicate** of the original WFT

It seems that when you take the freshly "transmuted" WFT out of the slot and place it into your inventory, there is a chance that it disappears altogether - kinda like if you were interacting with a ghost item. Bit weird but there you go.
## Info
Tested in an isolated instance with no other mods:
**(Latest versions at the time)**

| Mod | Version |
|--|--|
| Applied Energistics 2 | rv6-stable-1 |
| Baubles | 1.5.2 |
| p455w0rd's Library | 2.0.35 |
| Wireless Crafting Terminal | 3.10.82 |
| Forge | 14.23.4.2765 |

**Comment by p455w0rd** [comment]
ty for the report..I'm seriouosly surprised this wasnt reported before...I am updating the code for each terminal type to include the slot index # went syncing..this is where they're getting crossed...
