### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by sharkck** [p455w0rd/WirelessCraftingTerminal#287]
Running version 1.12.2-3.10.82 of Wireless Crafting Terminal.

I went to create my WCT today and noticed that there isnt an icon/texture for it.  Currently, there are only 2 out of 8 items from the mod that have a texture and they are the Magnet Card and the Infinity Booster Card.

I downloaded the mod through Twitch and have removed and re-added it just to try to see if it would make a difference and am getting the same result.

Also, I tried backing out of the server and creating a single player world and have the same result there as well.

I'm attaching a screenshot to show what is happening.
![screenshot 2018-10-04 03 48 17](https://user-images.githubusercontent.com/960552/46460372-bec79d00-c789-11e8-922c-cdfa4ec9543a.png)

**Comment by p455w0rd** [comment]
using optifine or a resource pack?

**Comment by sharkck** [comment]
Yes, using optifine.

**Comment by p455w0rd** [comment]
disable :) I'm using Forge's TileEntityItemStackRenderer which is a built in class (not some other rendering class/lib), therefore the issue is either with Optifine not supporting TEISRs or you have some option in Optifine disabled which borks TEISRs

**Comment by sharkck** [comment]
I had no idea.  By chance, do you know anything about OF that may be able to help with a setting?  If I need to get rid of it entirely, then that's what I'll do.

**Comment by p455w0rd** [comment]
i don't use optifine in my dev env and I don't play MC anymore (haven't in years), all I know is it causes a lot of issues with mods

**Comment by sharkck** [comment]
It seems that way.  Just trying to attempt a Google search is turning up all kinda of chaos it reeks on em :(  I've always thought it was a lot better with modded MC b/c of the performance gains it gives... whats the point if it just breaks everything... ugh :(

**Comment by sharkck** [comment]
Without OF... wow...

![image](https://user-images.githubusercontent.com/960552/46493505-8a320080-c7de-11e8-9b20-01b7e94905bb.png)

**Comment by sharkck** [comment]
+1 for the textures btw.
