### ISSUE TITLE
Crafting output into the system

### ISSUE THREAD

**Issue by Cazadorsniper** [p455w0rd/WirelessCraftingTerminal#288]
Think its possible to get AE2 to place items in the system when shift-click crafting rather it going to the players inventory?

**Comment by bloorocksDotD** [comment]
RS does this, but only if your inventory is full. I haven't used AE2 storage yet, but I would suggest trying that(you can just drag some cobble to fill your inventory)

**Comment by p455w0rd** [comment]
=D
