### ISSUE TITLE
Bugg with Compact Machines and Capability Adapter

### ISSUE THREAD

**Issue by Charismara** [p455w0rd/WirelessCraftingTerminal#289]
```
Minecraft: 1.12.2
Forge: 14.23.4.27.66

Applied Energistics 2: rv6 stable 1
Compact Machines: 3.0.12 b215
ME Capability Adapter: 1.0.1
Wireless Crafting Terminal: 3.9.68
```
Hey there,

I'm currently playing a mod pack and I have assembled a ME system which is distributed over several compact machines. The ME system runs and via terminals as well as with the wireless terminal I can interact normally with the system.

However, when I try to remove an item from the system or store it using the wireless crafting terminal, nothing happens. The items are only displayed more you can not do.

I hope the problem is recoverable.

Greetings Chris

**Comment by BrisingrAerowing** [comment]
You need to update WCT to the latest 3.10.x beta version. The 3.9.x versions are for AE2-RV5.

**Comment by Charismara** [comment]
Thanks ^^
