### ISSUE TITLE
Bug Fix needed. Server crashes on crafting in tinkers Crafting grid

### ISSUE THREAD

**Issue by RylaiSlyfe** [p455w0rd/WirelessCraftingTerminal#29]
Whole server crashes if I try to craft ANYTHING. It doesn't matter if I do this using my ME Wireless controller crafting grid or a tinkers crafting table. I'm using version v1.7b for AE2 RV3 Beta

**Comment by TheCodedOne** [comment]
Can you post a crash log?

**Comment by RylaiSlyfe** [comment]
http://pastebin.com/vAAFfuHK

**Comment by p455w0rd** [comment]
I'll get a hotfix out for this asap

**Comment by RylaiSlyfe** [comment]
Thanks. We do love your mod :) :+1:

**Comment by p455w0rd** [comment]
hmmm..I am unable reproduce this...crafting works fine for me and this actually was address and fixed already...looking at your log, you're def using 1.7b...I dunno..I'll have to do some testing...maybe it's something to do with TiC specifically..let me install TiC to my dev env and i'll try to get this sorted

**Comment by TheCodedOne** [comment]
I tried to reproduce this with tinkers... I couldn't seem to get it to crash

**Comment by p455w0rd** [comment]
yeah..as you can see here: https://github.com/p455w0rd/WirelessCraftingTerminal/blob/master/src/java/net/p455w0rd/wirelesscraftingterminal/proxy/CommonProxy.java#L186
I added the check...I'm baffled as to how this is possible..I tried in Integrated (Offline) as well as Server env and everything works for me

**Comment by TheCodedOne** [comment]
Maybe you have a bad installation of the mod? try reinstalling it on both server and client

**Comment by p455w0rd** [comment]
still instead of checking for the instanceof the player, i can change it to just check for which side it's on and that should rectify this..

**Comment by p455w0rd** [comment]
technically i should have done it that way anyway..not enough sleep lately lol

**Comment by p455w0rd** [comment]
I got it to reproduce locally...will be taken care of locally

**Comment by p455w0rd** [comment]
can you please try this hotfix and reply with results? http://p455w0rd.net/mc/WCT/WirelessCraftingTerminal-1.7.10-rv3-1.7.1b.jar

**Comment by RylaiSlyfe** [comment]
yes it works perfectly. thanks for this fix :) Can craft everything in everything again :D

**Comment by p455w0rd** [comment]
cool =D
