### ISSUE TITLE
Magnet card crash

### ISSUE THREAD

**Issue by Wolf68k** [p455w0rd/WirelessCraftingTerminal#292]
I was trying to remember the point of the Magnet Card. I thought it was pick up items and put them straight into the ME system, but instead it items were either left on the ground or instantly sucked in my inventory. I noticed the filter button above the card slot. I added stone to the filter.
When I threw some down, it started to suck it up and then froze and crashed the game.

Also if you try to restart the game the same crash as soon as I try to load the world. I have remove the mod, reload the world, then exit and re-enable the mod and the world.

Crash Report.....
https://gist.github.com/p455w0rd/98f79f3b56ca3f66d8f7c317dcab79b4

**Comment by p455w0rd** [comment]
you're using the wrong WCT version for AE2 RV6..use 3.10.x versions for RV6. Also please don't paste logs in isseus. Use a service like github gist or pastebin please..also I'm completely rewriting WCT atm with a large focus on the magnet to make it better

**Comment by Wolf68k** [comment]
Twitch Desktop doesn't let you know when a mod is Beta beyond the last Release.
Most devs just want the crash report however. 

You can pre-load the Issue with text like what do with crash reports and to check this and that and what info you want listed in the report. Just a though.

**Comment by p455w0rd** [comment]
yeah..also zero devs want the report to take up the full page..hence services like github gist

**Comment by Wolf68k** [comment]
Actually there are devs that have no problem with the crash report being pasted into the Issue report.
