### ISSUE TITLE
Suggestion: config option for inf wireless cards

### ISSUE THREAD

**Issue by Aphenon** [p455w0rd/WirelessCraftingTerminal#294]
Please make a config option to disable the inter-dimensional wireless infinity booster.  To have users make a wireless access point in each dimension they want to use the terminal in.

**Comment by p455w0rd** [comment]
there is a config to enable/disable it as well as a config to use the old mechanic...if you want per-dimension use, just disable the booster card since this is how vanilla AE works..I do get what you're saying, but it's very niche and this is just not something I'm interested in doing
