### ISSUE TITLE
Left-click not working

### ISSUE THREAD

**Issue by Gravitor** [p455w0rd/WirelessCraftingTerminal#297]
While trying to extract items from my AE system, i found that i could only right-click to get half a stack and to put back an item at a time. I do have both inventory tweaks and mouse tweaks installed, although i doubt that those are the problem.

**Comment by Alecsey2suvorov** [comment]
" Make sure the AE2 version you are using matches the WCT version!

AE2 RV2=WCT RV2

AE2 RV3=WCT RV3 "

Update to beta 3.10.82 RV6
