### ISSUE TITLE
[Suggestion] Terminal Sizing

### ISSUE THREAD

**Issue by condensedapple** [p455w0rd/WirelessCraftingTerminal#3]
new feature: add an option to resize/autosize the wct. This would be nice for Notebook users with small screens in order to use their wct properly.

**Comment by p455w0rd** [comment]
I've tested in a ton of different resolutions. It should automatically resize to fit any resolution. The only issue I have found is that at certain obscure (windowed) resolutions, with NEI installed, it may clip the top of the NEI text box. Could you perhaps provide an animated gif showing the issue you're experiencing? A great program for this is called ScreenToGif

**Comment by condensedapple** [comment]
Thank you, I'll try this out later today.

**Comment by kurokuno** [comment]
and i think this is the issue this is with a normal gui size that most people i know use 


http://i.imgur.com/m92KmZt.png?1

**Comment by p455w0rd** [comment]
Are you using the RV2 or RV3 version?

**Comment by kurokuno** [comment]
rev 3

**Comment by p455w0rd** [comment]
weird..I to always use Normal GUI size and that's what I use for this when developing it. I am not able to reproduce this. I do have an idea though. What is your screen resolution and are you running in fullscreen mode?

**Comment by kurokuno** [comment]
1920x1080 and not full screen

**Comment by p455w0rd** [comment]
This is what happens when I resize: http://p455w0rd.net/mc/WCT/WCT-Resize.gif I actually put a lot of time into the resizing/auto-sizing. Running @ 1920x1080 as well. Worst comes to worst, I'll just get rid of my code and use AE2's which has the tall/small options

**Comment by condensedapple** [comment]
I have two different terminals, I cant figure out what causes this.
http://85.214.16.155:81/randomstuff/

**Comment by p455w0rd** [comment]
If you want, follow me on Twitter and I'll DM you my Skype info and we'll get this sorted

**Comment by p455w0rd** [comment]
@TheRealp455w0rd

**Comment by p455w0rd** [comment]
it may very well be a Win 10 issue? I run 7. Was also thinking maybe gpu..I run AMD..most people run nVidia...I'll get something worked out.

**Comment by condensedapple** [comment]
The terminal looks right if i size my minecraft to about 1/8 of my screen

**Comment by kurokuno** [comment]
here we go http://gph.is/1TDY5fM gif of it

**Comment by p455w0rd** [comment]
ok, I will implement AE's optional style..maybe just use there code to completely replace mine. It will take some time as I update rv3 and rv2 at the same time, but I should have it up tonight. Sorry I can't make it happen any faster =(

**Comment by kurokuno** [comment]
its not a major issue its fine =D don't feel bad sorry we had so much trouble showing you the issue in the first place PS love the mod and the rate that you are bug fixing <3

**Comment by condensedapple** [comment]
you and your mod are absolutely amazing! Keep up the awesome work!
here a gif of the strange behavior (re-opening changes interface): http://85.214.16.155:81/randomstuff/wct.gif (no change with F11/fullscreen
got 100 wither spawned in my survival world (a config option for the drop rate would be nice) ;)

**Comment by p455w0rd** [comment]
During testing it took me 58 withers to get it to drop. (The rate is technically 1/50). Submit an issue for a Feature Request for the drop rate to be configurable, and I'll see what I can do ;)

**Comment by p455w0rd** [comment]
Also, thank you for that latest gif..it sheds some light onto the issue for sure..I'm not doing anything when It's resized horizontally, so I'll look into that and also just generally look into making it work on all scales (small, normal, large, auto)..For me, when I resize horizontally, nothing happens. It may actually be a Java version issue. I'm developing on Java 1.7 just to make sure it's backward compatible for people that haven't updated. And I'm not saying that it would be Java itself, but rather a library like LJWGL which relies on a certain version of Java.

**Comment by p455w0rd** [comment]
I finally am able to duplicate this bug =D Working on it now.

**Comment by p455w0rd** [comment]
Fixed and awaiting curse to approve new versions. Follow me on Twitter @TheRealp455w0rd for real-time updates

**Comment by condensedapple** [comment]
Yeah it works! Thank you for the quick update.

**Comment by p455w0rd** [comment]
re-opening as I want to add a config option to add the vanilla AE2 "Tall/Standard" options back. This won't be default, but a user requested it on Curse

**Comment by p455w0rd** [comment]
actually instead of another config option, I've decided to just add the terminal sizing back, but have it be 'Tall' by default

**Comment by p455w0rd** [comment]
https://twitter.com/TheRealp455w0rd/status/728592994278969344 =D
