### ISSUE TITLE
[1.7.10] NullPointerException when WCT is in Player Inventory

### ISSUE THREAD

**Issue by SyselMitY** [p455w0rd/WirelessCraftingTerminal#300]
I'm using WirelessCraftingTerminal-1.7.10-rv3-1.8.7.4b with appliedenergistics2-rv3-beta-6.
When I craft the WCT or have it in my inventory I get disconnected from the server and can't reconnect.

Here's the [stack trace](https://gist.github.com/SyselMitY/c166132f1bcff89454793ed9a396ad33)

**Comment by kmecpp** [comment]
Can this be fixed?

**Comment by kmecpp** [comment]
@p455w0rd I see now that it was fixed but can you upload the latest version to curse?
