### ISSUE TITLE
[1.12.2] Wrong Tooltip Name

### ISSUE THREAD

**Issue by TheSnowyChickens** [p455w0rd/WirelessCraftingTerminal#301]
Forge: 2796
MC: 1.12.2
p455w0rd's lib: 2.0.35
WCT: 3.11.83
WCTLIB: 1.0.2
Edit:
AE2: Rv6 Stable 4

Hi, I found a little text bug:
![grafik](https://user-images.githubusercontent.com/29357962/50129574-d76c2d00-0279-11e9-86cd-7c49c4de3b92.png)

**Comment by p455w0rd** [comment]
dammit lol..thank you
