### ISSUE TITLE
Latest Download requires p455w0rd's Library

### ISSUE THREAD

**Issue by bogointeractive** [p455w0rd/WirelessCraftingTerminal#304]
I downloaded the latest version and it requires p455w0rd's Library which has not been updated since September. Is there a way to get this download?

**Comment by p455w0rd** [comment]
Sorry about that! You can contact me on [discord](https://p455w0rd.net/discord) for now till its approved on CF

**Comment by HavlisCZ** [comment]
I am dealing probably with the same issue - mod AE2 wireless terminals is missing last library 2.0.36 (last updated library is 2.0.35)

**Comment by p455w0rd** [comment]
its just been approved on Curse https://minecraft.curseforge.com/projects/p455w0rds-library/files/2651697 Sorry!
