### ISSUE TITLE
WIRELESS CRAFTING ISSUE

### ISSUE THREAD

**Issue by stealthyjones** [p455w0rd/WirelessCraftingTerminal#306]
I am currently playing on a Revelations 1.12 server.  I'm having an issue (it's only me as far as i can tell) where i can open the wireless crafting grid and see everything but i cant put anything in.  I can pull out if i take half a stack at a time.  Is there anything can do to resolve this?

**Comment by AJ13th** [comment]
This bug was fixed with version 1.12.2-3.11.83! Greetings AJ
