### ISSUE TITLE
Terminal inventory glitch

### ISSUE THREAD

**Issue by AJ13th** [p455w0rd/WirelessCraftingTerminal#308]
Now that the server problem "Internal Exception java.io.IOExeption" or "internal server error" (Magnet-card problem) has been fixed, I now have the problem that I can no longer access the console or inventory! Right click on the terminal and it just glides somewhere in the player's inventory, gets deleted or doubles! Access impossible! Have the problems exclusively on my server not in singelplayer!

my data:
Minecraft 1.12.2
Forge 14.23.5.2768 (client and server)

Resourcepacks:
Conquest_1.12

Shader:
Conquest_Of_The_Sun

Mod's (on the server):
-AE2WTLib-1.12.2-1.0.6
-appliedenergistics2-RV6-stable-6
-BrandonsCore-1.12.2-2.4.8.194-universal
-ChickenChunks-1.12.2-2.4.1.73-universal
-CodeChickenLib-1.12.2-3.2.2.353-universal
-CoFHCore-1.12.2-4.6.1.22-universal
-CoFHWorld-1.12.2-1.3.0.6-universal
-Draconic Evolution 1.12.2-2.3.17.321-universal
-ExtremeReactors-1.12.2-0.4.5.49
-jei_1.12.2-4.14.3.237
-p455w0rdslib-1.12.2-2.0.36
-RedstoneFlux-1.12-2.1.0.6-universal
-ThermalDynamics-1.12.2-2.5.3.16-universal
-ThermalExpansion-1.12.2-5.5.2.39-universal
-ThermalFoundation-1.12.2-2.6.1.22-universal
-WirelessCraftingTerminal-1.12.2-3.11.87
-WirelessCraftingTerminal-1.12.2-3.11.87

Thanks in advance, do a great job, keep it up !!!
Greetings AJ

**Comment by p455w0rd** [comment]
this is so confusing..so I thought I had it fixed..but then in certain situations, it happens again...working on it..thx for reporting

**Comment by AJ13th** [comment]
Yes, I had read in other bug report's and was also confused!

In such a great mod and such a great support, very much! :) 👍🏻

**Comment by p455w0rd** [comment]
are you the owner of the server you're playing on with this bug? If so, I would appreciate if you could join my discord where I can send you a version where I have fixed it, but I would like to verify this with you before I upload to Curse :) https://p455w0rd.net/discord

**Comment by Horf** [comment]
We (on our server) have the same problem:

We are using the WCT with baubles and a binded key. I think the problem is there, if you try to open the crafting terminal via rightclick.
If you open it via the set key, it wokrs just as inteded.

**Comment by p455w0rd** [comment]
anyone is welcome to join my discord..I'll send you a fixed version before i upload to Curse so I know its fixed

**Comment by Horf** [comment]
> anyone is welcome to join my discord..I'll send you a fixed version before i upload to Curse so I know its fixed

I'm online (same nick) but can't wrote, cause I just have to wait another 5 minutes

**Comment by AJ13th** [comment]
Yes I am! But only a small server for my friend and me! If that's enough for you, we can of course test it on my own before you upload it!

I like to join on your discord but I am German and therefore not very good in English! Google is my friend! XD
