### ISSUE TITLE
JEI show Recipe/Usage hotkeys wont work in the wct

### ISSUE THREAD

**Issue by Mari023** [p455w0rd/WirelessCraftingTerminal#309]
WCT-Version: 1.12.2-3.11.87
I am using "F6" & "F7", my open terminal hotkey is "R".
No other hotkeys are interfering.
In the "normal" Terminal it works just fine.

**Comment by p455w0rd** [comment]
I recommend updating WCT, though, that won't solve this issue..just a suggestion. I'll look into how AE2 is doing this (if they're even doing anything at all) and see what I can do. This is more of a feature request than a bug since it's purely a mod interaction issue. Thanks for reporting :)

**Comment by p455w0rd** [comment]
so after testing..this actually works fine..you just need to hold `Ctrl` while pressing `R`/`U`..this is the way AE2 functions as well
