### ISSUE TITLE
UseOldInfinityMechanic = True not working?

### ISSUE THREAD

**Issue by acanady** [p455w0rd/WirelessCraftingTerminal#310]
I'm currently using WCT version 3.11.88 and in the config it mentions that if UseOldInfinityMechanic is true then inserting 1 Infinity Booster Card into the slot will give limitless infinite range. Does this mean that the card should no longer be eaten up? I noticed that a similar issue was opened in the past but the solution, if there was one, was not there. Is that not what this config does?

**Comment by acanady** [comment]
As of now setting it to true doesn't seem to change anything at all

**Comment by p455w0rd** [comment]
The config file has changed from `WirelessCraftingTerminal.cfg` to `AE2WirelessTerminals.cfg` (this is a global config file for all of my coming AE2 Wireless Terminals which make use of the infinite range mechanic)..I plan to add a check for WirelessCraftingTerminal.cfg and replace/set the values in AE2WirelessTerminals.cfg, I'm just very busy and have not been able to get to that first. I would like to keep this issue open for others that might be experiencing the same. Thanks for the report :)

**Comment by acanady** [comment]
Ah silly me, I didn't notice. Thanks a bunch.

**Comment by NLBlacky** [comment]
We have in both `WirelessCraftingTerminal.cfg` and `AE2WirelessTerminals.cfg` the following option set to true: `# If true, then simply inserting 1 Infinity Booster Card into the slot, will give limitless infinite range.`

With this option we assume that the Infinity Booster Card was no longer being consumed. Reading @p455w0rd last comment about the change of config, I made sure we applied the change in both configs, however the card is still getting consumed? Do I need to set both configs to have that option set to false instead to make it work?

**Comment by p455w0rd** [comment]
You can delete WirelessCraftingTerminal.cfg..the file isn't used anymore.
![image](https://user-images.githubusercontent.com/12187748/51354184-cd0f9f80-1a80-11e9-8393-f11c5df2435f.png)
this is working fine..the error is one your end..no idea what you're doing wrong..but it works...

**Comment by tekkitan** [comment]
I am also not able to get "UseOldInfinityMechanic=true" working. I am on Revelation 2.7.0. I edited it in both configs (because I didn't realize the config file changed till I found this issue). I was hoping changing it in AE2WirelessTerminals.cfg would make it work but still isn't working how it did back in Infinity.

**Comment by NLBlacky** [comment]
Delete WirelessCraftingTerminal.cfg will fix this. Infinity booster card is still consumed but the power won’t be depleted. If you hate the low energy warning, lower the trigger limit from 5000 to lowest in client config.

**Comment by tekkitan** [comment]
OK thanks, I will give that a try after work!

**Comment by p455w0rd** [comment]
closing this as it definitely works since there are streamers playing packs with WCT in both modes
