### ISSUE TITLE
Wireless Crafting Terminal does not exist for some clients

### ISSUE THREAD

**Issue by hjoyn** [p455w0rd/WirelessCraftingTerminal#311]
Pack: Modified Direwolf20 1.12.2

Forge: 14.23.5.2806

Mod: 3.11.88
Mod Dependencies:
AE2WTLib 1.0.6
Applied Energistics 2 rv6-stable-6
Extra Cells 2.6.2
p455w0rdslib 2.0.36

The wireless crafting terminal does not exist on the client. It has no textures, nor shows up in JEI. The server and some other clients do acknowledge the item as existing, and connecting to a server works. The item can be obtained via crafting, but continues to have no render. The item functions if used, and is visible to other clients where the item does exist. The item can be crafted into a wireless universal terminal, and does not crash. A crash can be caused by attempting to equip the item as a bauble, which causes a crash as a result of the client not being able to render the item as a bauble. The issue originally occurred on forge version 14.23.5.2790, but persisted on 14.23.5.2770, the version the client with the working item was using, and 14.23.5.2806 when tested. 

[crash-2019-01-07_22.20.02-client.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/2735393/crash-2019-01-07_22.20.02-client.txt)

**Comment by BrockWS** [comment]
I'm not sure about the other issues, but the crash is an EC2 issue. There should be a fix available soon on Discord. https://discord.gg/kJnPCMs
