### ISSUE TITLE
Negative Charge

### ISSUE THREAD

**Issue by Zidane3838** [p455w0rd/WirelessCraftingTerminal#316]
no idea how I managed this... it's been working fine for months... last night the % started at like -1.#### and kept going down to 2.17#

Edit: oh and my plug registers it at 3KFE/T in flashes of less than a second which you can see in the second screenshot me trying to capture it lol

Edit2: Enigmatica 2 Expert wirelesscraftingterminal-1.12.2-3.11.88.jar btw

![2019-02-01_01 48 58](https://user-images.githubusercontent.com/1594255/52157542-6af49400-2655-11e9-98cb-f857367969b2.png)
![2019-02-01_01 51 42](https://user-images.githubusercontent.com/1594255/52157543-6af49400-2655-11e9-92f9-842007c5d1e2.png)

**Comment by p455w0rd** [comment]
I've tried and was not able to reproduce this in an environment with EnderIO wireless charging...I would guess mod interaction..without a lot more info, I can't reproduce and if I can't reproduce, I can't fix it

**Comment by NielsPilgaard** [comment]
I'm afraid this bug still exists, I hope I can provide some more info on it. 

The Wireless Crafting Terminal went into negative power after being placed into a Mekanism Induction Matrix multiblock, which depleted the Induction Matrix.

It was reported to me here: https://github.com/NillerMedDild/Enigmatica2Expert/issues/1487

### Versions
- WirelessCraftingTerminal-1.12.2-3.12.97
- p455w0rdslib-1.12.2-2.3.161
- AE2WTLib-1.12.2-1.0.34
- Mekanism-1.12.2-9.8.3.390
- Forge-1.12.2-14.23.5.2847
