### ISSUE TITLE
Magnet Mode keybind missing since AE2WTLib changes?

### ISSUE THREAD

**Issue by Vercci** [p455w0rd/WirelessCraftingTerminal#318]
Correct me if I'm doing something wrong, but I swear there was an easy to see and use keybind for the button that enables / disables the magnet card. I think it went missing since the change to that AE2WTLib mod.

Now there's a button on the gui that does the same thing, but that's more annoying if I could get the keybind back, or instructions on where to find the keybind now. Open wireless terminal is all alone on my controls screen in my pack (Enigmatica 2 expert 1.51)

**Comment by p455w0rd** [comment]
yeah, I removed that keybind as it is just one less thing that can go wrong during this time while I'm updating/converting code..I'll leave this issue open and reimplement it eventually
