### ISSUE TITLE
Magnet Card doesn't work in hotfix 1.7.1

### ISSUE THREAD

**Issue by RylaiSlyfe** [p455w0rd/WirelessCraftingTerminal#32]
After you fixed the problem with the tinkers crafting, I noticed, that the magnet card does suck up items, but doesn't transfer them into the network anymore

**Comment by p455w0rd** [comment]
works here..maybe you just don't have the filter set up right? to collect all items, set to blacklist mode with no items filtered. basically this is saying "blacklist nothing"--see here: http://p455w0rd.net/mc/WCT/magnetworks.gif

**Comment by p455w0rd** [comment]
well you haven't responded, so I'm going to assume this issue is resolved
