### ISSUE TITLE
[Suggestion] Let the terminal be enchantable.

### ISSUE THREAD

**Issue by TheUnderTaker11** [p455w0rd/WirelessCraftingTerminal#324]
I would like for the crafting terminal to be like a normal item in way that you can use an anvil to put an enchantment on it.           
The reason for this is because it would allow people to put the soul-bound enchant on their terminals, which I remember I used to be able to do but can't anymore for some reason.

**Comment by p455w0rd** [comment]
soon
![](https://puu.sh/CYnxx/dba56835f2.gif)
