### ISSUE TITLE
problem with mod

### ISSUE THREAD

**Issue by Lolbuser1911** [p455w0rd/WirelessCraftingTerminal#325]
Hello, when I run my game I have error message "Forge Mod Loader has found a problem with your minecraft installation
The mods and versions listed below could not be found
p455w0rdslib: any
The file 'logs / fml-lasted.log' contains more information "

I have as mod:
-Galacticraft-Planets-1.7-3.0.12.375
-GalacticraftCore-1.7-3.0.12.375
-CodeChickenCore-1.7.10-1.0.7.47-universal
-EnderStorage-1.7.10-1.4.7.37-universal
-MicdoodleCore-1.7-3.0.12.375
-appliedenergistics2-rv3-beta-6
-AssemblyMod-1.7.10-2.1
-NotEnoughItems-1.7.10-1.0.5.120-universal
-CodeChickenLib-1.7.10-1.1.3.138-universal

and the one that does not work
-WirelessCraftingTerminal-1.7.10-rv3-1.8.7.9b

if you can help me thank you for answering me

**Comment by p455w0rd** [comment]
you need p455w0rdslib: https://minecraft.curseforge.com/projects/p455w0rds-library/files/2359471
