### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ZataraTMM** [p455w0rd/WirelessCraftingTerminal#326]
Isn't an issue, just a suggestion. Didn't know where to post it. Would it be possible to add liquids to the terminal with the ability to switch it? Liquids/items button

**Comment by p455w0rd** [comment]
stay tuned...

**Comment by ZataraTMM** [comment]
Thank you

**Comment by p455w0rd** [comment]
[Wireless Fluid Terminal](https://minecraft.curseforge.com/projects/wireless-fluid-terminal)
