### ISSUE TITLE
Crash when pressing the “open wireless crafting terminal” key while it’s in the off-hand

### ISSUE THREAD

**Issue by Dimentive** [p455w0rd/WirelessCraftingTerminal#328]
When I put my wireless crafting terminal in my off-hand and pressed the key that opens the wireless crafting terminal, my game immediately crashed.

Crash report: https://pastebin.com/raw/QuUyGUqk

#### Versions

* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.63a](https://minecraft.curseforge.com/projects/enigmatica2/files/2691579))
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **Wireless Crafting Terminal:** [3.11.88](https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2654188) (latest)
* **Applied Energistics 2:** [rv6-stable-6](https://minecraft.curseforge.com/projects/applied-energistics-2/files/2652453) (latest)

**Comment by p455w0rd** [comment]
wrong issue lol
