### ISSUE TITLE
Crash when shift + click to open

### ISSUE THREAD

**Issue by Will11690** [p455w0rd/WirelessCraftingTerminal#329]
I'm playing on enigmatica 2 expert 1.57 on a private server with a friend and any time I accidentally hold shift when I open the terminal it crashes the games. My friend has also had it happen to him

**Comment by p455w0rd** [comment]
can i get a log?

**Comment by Will11690** [comment]
I'm working on getting one. For some reason its not making a crash report when it happens so I have to crash my game again

**Comment by Y0ungSandwich** [comment]
I believe I have reproduced this in my modpack. 
Crash Report:
https://gist.github.com/Y0ungSandwich/6a58bcced02effa88a7a7ce43d3e39bf

Full Log:
https://gist.github.com/Y0ungSandwich/a92d5ffc491a621c542a43ea0b9a83c4
