### ISSUE TITLE
Crash when making witchery wolf altar

### ISSUE THREAD

**Issue by Stalkstalks** [p455w0rd/WirelessCraftingTerminal#33]
Getting a crash when making a witchery wolf altar, regarding 
net.p455w0rd.wirelesscraftingterminal.proxy.CommonProxy.onPlayerCraftingEvent

Got it on a server - when using the crafting terminal, it just booted me from the server.
When using a crafting table, it actually crashed the server

**Comment by p455w0rd** [comment]
well..seems to be taking Curse a bit longer than usual..you can get fixed versions here:
http://p455w0rd.net/mc/WCT/WirelessCraftingTerminal-1.7.10-rv2-1.7.4b.jar
http://p455w0rd.net/mc/WCT/WirelessCraftingTerminal-1.7.10-rv3-1.7.4b.jar
