### ISSUE TITLE
Wireless crafting terminal with magnet card magnetizes ALL items when ME storage system is full

### ISSUE THREAD

**Issue by Dimentive** [p455w0rd/WirelessCraftingTerminal#331]
After my ME storage system got completely full, not being able to fit any more items, my wireless crafting terminal with the magnet card upgrade started magnetizing every single item, even though I’ve whitelist certain ores. I also tried switching to blacklist mode and turning off “Use ore dictionary” but to no avail. I confirmed that the magnet card upgrade is causing this as removing the magnet card from my wireless terminal or disabling it stops this behaviour.

#### Versions

* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.65a](https://minecraft.curseforge.com/projects/enigmatica2/files/2700051), latest)
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **Wireless Crafting Terminal:** [3.11.88](https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2654188) (latest)
* **Applied Energistics 2:** [rv6-stable-6](https://minecraft.curseforge.com/projects/applied-energistics-2/files/2652453) (latest)

**Comment by p455w0rd** [comment]
is this full as in just the 63 types, or full as in no more space for any of the item types inside?

**Comment by Dimentive** [comment]
Both. All my cells were either full in terms of types or in terms of bytes. When dropping items that couldn’t fit inside any of my disks or external storage, they were instantly magnetized into my inventory (with no delay). I didn’t test with items that _could_ fit inside my ME storage.

**Comment by p455w0rd** [comment]
this honeslty sounds like it's working the way its supposed to..you can change the magnet mode with the button to left in the WCT gui which will:
1: Do nothing
2: Add 'extra' items to inventory (extra items are items that wont fit in your AE network)
3: Extra Items left on ground..the items that cannot fit in your AE netowrk will be left lone

**Comment by Dimentive** [comment]
It didn’t work as expected. As mentioned, it started magnetizing _all_ items, even ones that weren’t whitelisted when my ME storage system was full. It ignored the whitelist completely.

**Comment by p455w0rd** [comment]
[screen recording](https://puu.sh/DwNzQ/2b630f9a59.webm)
in dev I've tested this extensively, and it appears to be fixed

**Comment by Dimentive** [comment]
Thank you! 👍 I’ll give you my own feedback on whether or not it still occurs to me the next time I play.

**Comment by p455w0rd** [comment]
this fix isnt live yet
