### ISSUE TITLE
Key press "B" deletes all text in search bar

### ISSUE THREAD

**Issue by B00msht1ck** [p455w0rd/WirelessCraftingTerminal#332]
This just started for me while playing — was working fine at first, then this issue popped up.

As title says, in the WCT I can type any other letters but if I hit "b" it deletes all the text in the search bar (and adds the "b" character in).

I've crafted new WCT, reloaded client, deleted and re-downloaded modpack files, tested in a different world, no matter what I do this issue won't go away.

Have also tested with AE2 Crafting Terminal, no text issues there — only happening in the WCT.

**Comment by p455w0rd** [comment]
i cannot reproduce this in recent versions, plese reopen if this issue still persists

**Comment by NielsPilgaard** [comment]
I can confirm that this no longer happens with `WirelessCraftingTerminal-1.12.2-3.12.97`
