### ISSUE TITLE
Terminal displays negative values in discription

### ISSUE THREAD

**Issue by Technify82** [p455w0rd/WirelessCraftingTerminal#333]
I hooked up a Spectre Energy Injector to my Draconic Evolution Pylon which immediately emptied the Energy Core and apparently dumped it all into the wireless crafting terminal. I am using the Ender  Spectre Charger as a bauble. Here is a link to my modpack: 

https://minecraft.curseforge.com/projects/slugs/files

The Forge version I am using is : 14.23.5.2836

I figured that I would start here since the terminal was the only thing affected (not including losing 3 Billion RF....)

![2019-05-10_22 17 25](https://user-images.githubusercontent.com/50507552/57564218-5885a700-7376-11e9-817a-25efb166f0b5.png)
![2019-05-10_22 29 46](https://user-images.githubusercontent.com/50507552/57564219-5885a700-7376-11e9-8dd3-7d5db0212036.png)
![2019-05-10_22 29 58](https://user-images.githubusercontent.com/50507552/57564220-5885a700-7376-11e9-9a70-182daa71705d.png)

Thank-you

**Comment by p455w0rd** [comment]
Through all of my testing I am unable to reproduce this. This means that it likely is due to mod interaction and actually could quite possibly be a one-off. I cannot be sure, After the coming update, if the issue persists, please reopen
