### ISSUE TITLE
How to disable infinity energy.

### ISSUE THREAD

**Issue by pikizin** [p455w0rd/WirelessCraftingTerminal#336]
How to disable infinity energy?

For me is broken system consuming 1 infinity boost in 5 seconds...

Non sense...

I want disable that system... or i will use creative item.
![2019-05-29_12 16 06](https://user-images.githubusercontent.com/51034518/58568964-935b5c00-820b-11e9-9ad5-791d552d9aa9.png)
![2019-05-29_12 16 08](https://user-images.githubusercontent.com/51034518/58568965-935b5c00-820b-11e9-8031-a9b8efd9f6fb.png)

**Comment by p455w0rd** [comment]
check configs
