### ISSUE TITLE
Crash when crafting using ibench mod's crafting ability

### ISSUE THREAD

**Issue by Stalkstalks** [p455w0rd/WirelessCraftingTerminal#34]
Tried to craft minecraft doors using ibench mod's crafting interface, crashed server.

**Comment by p455w0rd** [comment]
ok...maybe provide a crash report?

**Comment by Stalkstalks** [comment]
http://pastebin.com/SQ85nheH

**Comment by p455w0rd** [comment]
ok..i'll get to it  soon...i'll have a fix up tonight

**Comment by p455w0rd** [comment]
same error as with #33
