### ISSUE TITLE
Crash while loading game

### ISSUE THREAD

**Issue by jacobwilki01** [p455w0rd/WirelessCraftingTerminal#340]
While loading the game, I get the following crash: https://pastebin.com/yPdTLSuS

Here is the complete mod list: https://pastebin.com/wRwS20dH

It crashed during Initialization.

MC Version: 1.12.2
Lib Version: 1.0.27
WCT Version: 3.11.88
AE2 Version: rv6-stable-6

**Comment by p455w0rd** [comment]
update wct
