### ISSUE TITLE
Bug: Terminals not accepting wireless charging anymore.

### ISSUE THREAD

**Issue by SirAron111** [p455w0rd/WirelessCraftingTerminal#342]
Bug that causes the wireless crafting Terminals to not be charged from wireless chargers anymore since the big update to the mod. Now the only way to charge it is by putting it in a charging block like the infuser. Before you could also charge them with random things spectra charger or wireless charger from ender io or batteries from actually additions so I think that some function has been lost that normally looks for things that charge stuff.

**Comment by p455w0rd** [comment]
yeah..i did accidentally delete some code..fixed in dev..i'll be pushing a batch of updates as soon as I get this last /dank/null bug i have fixed..hopefully today still

**Comment by vovacat17** [comment]
When is this one getting fixed? I believe it is related to a crash I am having.  The jetpack is trying to charge the terminal, so there's a conflict.
[crash-2019-11-13_20.04.08-client.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/3842485/crash-2019-11-13_20.04.08-client.txt)

**Comment by p455w0rd** [comment]
That crash is unrelated according to what it is reporting. It's reporting that the class `thundr.redstonerepository.api.IArmorEnderium` doesn't exist, but is being referenced from SimplyJetpacks (specifically `tonius.simplyjetpacks.item.ItemJetpack#chargeInventory`) somehow.
As to when..as per the label, it is fixed. If you mean `When will it be live?`: As soon as I get the current batch of bugfixes/feature requests implemented for AE2WTLib and associated terminals. ETA: a day or so hopefully

**Comment by vovacat17** [comment]
Nice, waiting then. I still strongly believe the crash has something to do with the terminal being unable to charge, as it happens instantly once the terminal is put in the hotbar. Now I've turned the charger on my jetpack off and so no crash happens, the terminal is fully usable.
