### ISSUE TITLE
Infinity Energy resets in Crafting Grid

### ISSUE THREAD

**Issue by Wxrlds** [p455w0rd/WirelessCraftingTerminal#346]
The Infinity Energy value resets if you try to combine two terminals to form the Ultimate Terminal (you don't have to craft the Ultimate Terminal in order to receive a energy reset)

Video instructions: [https://www.youtube.com/watch?v=EVfI0rkFhnI](https://www.youtube.com/watch?v=EVfI0rkFhnI)
At the end of the video you can see it resetting the value

**Comment by p455w0rd** [comment]
![](https://puu.sh/EE52z/a7167ac960.gif) Thanks for reporting with the video..without the video, I'd have been lost :)
