### ISSUE TITLE
Toggle focus key does not toggle

### ISSUE THREAD

**Issue by Dalethium** [p455w0rd/WirelessCraftingTerminal#349]
#170 
The key for ae2's focus is a toggle, and should work as shown in [this GIF](https://i.imgur.com/dYWZNCD.gifv) However it works [like this ](https://i.imgur.com/iv7NcJy.gifv).

The first GIF is of a ME pattern terminal, the second is of a Creative Wireless Crafting Terminal

[Mods](https://pastebin.com/DYUMGH5k)

**Comment by p455w0rd** [comment]
i mean it actually functions the sdame..the issue is rendering..I did this intentionally, but I have reverted code to refelcts AE2's functionality now
