### ISSUE TITLE
Crafting Status disconnects client from server

### ISSUE THREAD

**Issue by RylaiSlyfe** [p455w0rd/WirelessCraftingTerminal#35]

**Comment by p455w0rd** [comment]
I am unable to reproduce this..can you please explain in more detail exactly how you went about doing this?

**Comment by p455w0rd** [comment]
also..please post full crash logs (this lets me know what other mods you're running and has other useful information)

**Comment by RylaiSlyfe** [comment]
there is no crash log because nothing crashes. The client just gets disconnected with "A fatal error has occured, this connection is terminated."

Everything I have to do is click on crafting status in the terminal

**Comment by p455w0rd** [comment]
can i get your server info so I can connect and test this?

**Comment by p455w0rd** [comment]
I have tried literally everything and it works fine here :/

**Comment by p455w0rd** [comment]
also what pack you're running/mod list if so

**Comment by RylaiSlyfe** [comment]
feed  the beast infinity evolved 2.5.0 is the pack we're using. Sorry I can't give you the server infos :/

**Comment by p455w0rd** [comment]
well then I can't fix this, sorry :/

**Comment by p455w0rd** [comment]
i even went as far as to install the FTB Infinty Evolved server(latest version)..works fine

**Comment by p455w0rd** [comment]
I was finally able to reproduce this..fixing now
