### ISSUE TITLE
EnderIO Inventory charger can't charge WCT but can charge ME WT from AE2

### ISSUE THREAD

**Issue by RobinMontferme** [p455w0rd/WirelessCraftingTerminal#350]
AE2 ver :  rv6-stable-7
Enderio ver: 1.12.2 - 5.0.46
WCT ver: 1.12.2 - 3.12.93
AE2WTLib ver: 1.12.2 - 1.0.30

EnderIo invenotry charger are capable of charging AE2 ME wireless Terminal but not
thr Wireless Terminal.  Tested with all type of inventory charger. Checked that the WCT wasn't in any bauble slot.

**Comment by p455w0rd** [comment]
#342
