### ISSUE TITLE
Wireless Crafting Terminal Not Charging Wirelessly

### ISSUE THREAD

**Issue by Deathadderx** [p455w0rd/WirelessCraftingTerminal#351]
I've recently installed the mod to accompany with the skyfactory 4 modpack, however since downloading the mod, and crafting the item it will not charge. I have wireless chargers set up that would normally charge the wireless terminals from AE2, it will only charge from the Mekanism energy cubes, is there a way for it to charge wireless or am I crazy?

**Comment by mrambow** [comment]
I've the same issue with a custom modpack
* AE2WTLib-1.12.2-1.0.30.jar
* appliedenergistics2-rv6-stable-7.jar
* EnderIO-1.12.2-5.0.50.jar

**Comment by p455w0rd** [comment]
#342
