### ISSUE TITLE
Extra inventory slots for cards not showing up

### ISSUE THREAD

**Issue by Vareska** [p455w0rd/WirelessCraftingTerminal#353]
Ive tried everything I can think of, Ive loaded just JEI, AE2 and Wireless crafting + libs and the inventory slots for the wireless crafting terminals still wont show up, im using forge for 1.12.2.

![image](https://user-images.githubusercontent.com/6834727/65007166-350ed200-d8fd-11e9-8a77-930ca1dbd69a.png)
 this is how my inventory looks.

**Comment by Vareska** [comment]
anyone got any idea why the extra inventory slots arnt showing up?

**Comment by KiddieD** [comment]
The slots for the cards are inside the terminals themselves. @Vareska
