### ISSUE TITLE
Feature request: Terminals don't support CTRL+A

### ISSUE THREAD

**Issue by KiddieD** [p455w0rd/WirelessCraftingTerminal#355]
The terminals don't support CTRL+A for usage with the delete key. The native AE2 terminals do. It would be nice if CTRL+A worked for easy and speedy workflows.

**Comment by p455w0rd** [comment]
i agree..i'll look into it

**Comment by TheJulianJES** [comment]
Not sure if this belongs or here or if it's a new issue:
Currently it seems like that the Wireless Crafting Terminal in JEI Synronized mode always moves the cursor in the textfield to the last position after half a second.
It also unselects the entire text (if selected using CTRL+A).
With Wireless Pattern/Interface Terminal this doesn't happen.

("WirelessCraftingTerminal-1.12.2-3.12.97" is the version I'm using)

I can also create a new issue if you want (and add proper information there).

**Comment by HumbleDeer** [comment]
It seems implementing the feature has broken part of it and another integration. I've experienced this too. In the end, CTRL+A still doesn't work properly (selects, but doesn't stay selected.)
