### ISSUE TITLE
Halloween wither skeleton + pumpkin rendering of player in terminal crashes client

### ISSUE THREAD

**Issue by yilrus** [p455w0rd/WirelessCraftingTerminal#356]
Crash log: https://pastebin.com/cpZ8qMqH
To reproduce: Open terminal, will crash within 10 secs, might be specific to my setup or E2E configs
Pack: Enigmatica 2: Expert v1.69 (don't know about the latest which is 1.72). Not sure if this has been fixed upstream but not in my version of the pack.

**Comment by Warrock3280** [comment]
Same thing. But crash occurs exactly when you pick up any item in WCT or press **Clear grid** button (X).

**Comment by coldino** [comment]
Same:
```
Time: 10/31/19 1:01 AM
Description: Updating screen events

java.lang.ClassCastException: net.minecraft.entity.monster.EntityWitherSkeleton cannot be cast to net.minecraft.entity.player.EntityPlayer
	at p455w0rd.wct.client.gui.GuiWCT.func_146273_a(GuiWCT.java:275)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at p455w0rd.wct.client.gui.GuiWCT.func_146274_d(GuiWCT.java:157)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by SeseMueller** [comment]
Same here. Vanillafix doesn't help, but also suggest, that the crash is caused by the Crafting terminal mod. 1.71 on Enigmatica 2 Expert doesn't fix it either.

**Comment by Wheelz86** [comment]
Same problem here.

**Comment by sapient** [comment]
Problem is that some mod is doing Halloween shenanigans and turning the player into a Wither Skelly, WCT tries to get its inventory (thinking its the player) and crashes. 

WCT should add a check in for this (ridiculous) situation, but the mod that turns the player into a Wither Skeleton is probably doing it in a stupid way and the quick solution is to figure out which mod that is and disable its "Holliday ""FUN"" Feature"

**Comment by Immow** [comment]
> Problem is that some mod is doing Halloween shenanigans and turning the player into a Wither Skelly, WCT tries to get its inventory (thinking its the player) and crashes.
> 
> WCT should add a check in for this (ridiculous) situation, but the mod that turns the player into a Wither Skeleton is probably doing it in a stupid way and the quick solution is to figure out which mod that is and disable its "Holliday ""FUN"" Feature"
> 
> Edit:
> if (isHalloween) {
> entity = new EntityWitherSkeleton(Minecraft.getMinecraft().world);
> entity.setItemStackToSlot(EntityEquipmentSlot.HEAD, new ItemStack(Blocks.LIT_PUMPKIN));
> }
> 
> So the culprit really is WCT with the badly tested "FUN" stuff.

Where did you find this?

**Comment by sapient** [comment]
https://github.com/p455w0rd/WirelessCraftingTerminal/blob/f5cb620eaf755f4ffaf32b4279b30accd3a8ce3e/src/main/java/p455w0rd/wct/client/gui/GuiWCT.java#L576

**Comment by tsssp** [comment]
Same here.

**Comment by RNADNA47** [comment]
Confirming this bug. I updated to the latest versions of all p4545w0rd's mods:

1.12.2-1.0.30 of AE2WTLib
1.12.2-2.2.156 of p455w0rdslib
1.12.2-3.12.93 of this mod

I can watch the wither skel just fine in the WCT. However, if I attempt to withdraw an item from AE2 wirelessly ... crash.

**Comment by galori** [comment]
Everyone on my Enigmatic 2 Server is crashing with the same error using WCT @p455w0rd

**Comment by Schnabelriechen** [comment]
So this undocumented easter-egg prevented players worldwide from playing the game. Great job @p455w0rd

**Comment by Ravalli03** [comment]
I don't think it's another mod causing this, it's only the WCT showing the Halloween thing. If you open your normal inventory, it doesn't show the wither skeleton.

**Comment by p455w0rd** [comment]
I was gone over Halloween, a PR has been submitted to fix this. AE2 RV6 has updated, so I'll be updating that as well in the next update
