### ISSUE TITLE
Crash when crafting/clicking items into the terminal.

### ISSUE THREAD

**Issue by ArkhamAggron** [p455w0rd/WirelessCraftingTerminal#359]
[crash-2019-10-31_09.31.33-client.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/3794360/crash-2019-10-31_09.31.33-client.txt)

**Comment by ArkhamAggron** [comment]
Edit: it crashes when i have placed more than 3 items in any of the slots of thd crafting grid and when i shift click things into the system

**Comment by Parthurax** [comment]
same issue.....

**Comment by Picticon** [comment]
It is related to an untested Halloween easter egg event. As a workaround you can change the date on your computer to Nov 1 until Halloween is over.

**Comment by Warrock3280** [comment]
Duplicate of #356
