### ISSUE TITLE
Minetweaker support

### ISSUE THREAD

**Issue by JasonMcRay** [p455w0rd/WirelessCraftingTerminal#36]
I am trying to change the recipe for WCT items for my modpack. On singleplayer everything works fine without any issues. However on server I am experiencing missmatch between NEI and the actual recipe.

#### What Happens:
NEI shows default recipe on server. But can't actually craft it. I need to use the minetweaked recipe.

#### What is supposed to happen:
NEI should show the recipe I changed it to via minetweaker.

#### To reproduce:
1. Load MC with NEI, WCT, AE2 and Minetweaker
2. In scripts folder make ae2.zs file
3. Into the file put
```
recipes.remove(<ae2wct:wirelessCraftingTerminal>); // removes the recipe
recipes.addShaped(<ae2wct:wirelessCraftingTerminal>, [[<minecraft:dirt>, <minecraft:dirt>]]); // adds new recipe
```
4. Start singleplayer
4a. In NEI you can see that WCT requires 2 blocks of dirt to craft - OK
5. Start multiplayer
5a. In NEI you can see that WCT wants the recipe default to the mod
5b. If you try to craft the WCT with the shown recipe, it will not work (will not allow you to pull the item out of the crafting table)
5c. If you try to craft the WCT with the 2 blocks of dirt (like it was shown in Singleplayer) the output will not show in the crafting output, but you can click on the spot where the WCT should be and pull it out.

Same goes for all other items added by your mod (Magnet Card, Infinity Booster, ...)

#### Mod Version:
WCT: rv3-1.7.4b
AE2: rv3-beta-6
NEI: 1.0.5.120
MT: 3.0.10B

**Comment by p455w0rd** [comment]
the reason this happens is because of the two modes within my mod. Due to this I have to do a sync at every player login (this includes loading a world when offline). This is why this is happening. I may be able to add in minetweaker support. I'll look into this in a bit =]. I'm going to mark this as a feature request for MineTweaker support.

**Comment by p455w0rd** [comment]
Okay, so the simplest way I could figure out to implement this was to add another config option. It allows for minetweaker overriding if set to true. What this does is not remove/add recipes during the config sync process. With this enabled all recipes are removed, so you will be in charge of adding any methods of getting all items.

**Comment by JasonMcRay** [comment]
That sounds good. Thank you
