### ISSUE TITLE
Can't find ae2utlib

### ISSUE THREAD

**Issue by Azimdur** [p455w0rd/WirelessCraftingTerminal#360]
Hello,

When I install the wireless crafting terminal mod, forge says that I need the library ae2utlib, but I can't find it on google.

I'm using revision appliedenergistics2-rv6-stable-7, and forge1.12.2-14.23.5.2847

**Comment by p455w0rd** [comment]
never heard of ae2utlib...you might try googling ae2wtlib (AE2 Wireless Terminal Library)
