### ISSUE TITLE
Crashing when opening Terminal

### ISSUE THREAD

**Issue by someKumo** [p455w0rd/WirelessCraftingTerminal#388]
When I open the terminal then there is not my Skin, but a Wither Skeleton
and when I have it open for a longer time my Minecraft crashes with 
`The game crashed whilst updating screen events
Error: java.lang.ClassCastException: net.minecraft.entity.monster.EntityWitherSkeleton cannot be cast to net.minecraft.entity.player.EntityPlayer
Exit Code: -1`
Crashlog:
[crash-2021-10-31_12.58.45-client.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/7448699/crash-2021-10-31_12.58.45-client.txt)
Latest:
[latest.log](https://github.com/p455w0rd/WirelessCraftingTerminal/files/7448700/latest.log)

**Comment by GuivinALT** [comment]
Same problem.
Voteup.
Seems to be a bug from a hidden easter egg for halloween.

Epic failed.

**Comment by someKumo** [comment]
it was indeed a bug with the Halloween event
