### ISSUE TITLE
WCT drains entire Draconic Evolution Flux Capacitor

### ISSUE THREAD

**Issue by condensedapple** [p455w0rd/WirelessCraftingTerminal#4]
The WCT, when in hotbar, drains a flux capacitor (wyvern or draconic) instantly (even if the wct is at 99.99%). This does not occur when using some other flux cpacitor (Flux Capacitors from ThermalExpansion, Quitit Cell from QuantumFlux). Other AE-Terminals (AE2/ExtraCells/ThaumicEnergistics) are not affected.
Also reported to [DraconicEvolution](https://github.com/brandon3055/Draconic-Evolution/issues/304)

**Comment by p455w0rd** [comment]
I'll look into this. This happens with other terminals too with certain versions of AE2. I may just add code to check if DE is installed and then do checks to see if the flux cap is in your inventory. I've seen this happen on many streams. I will also talk with @brandon3055 about this.

**Comment by brandon3055** [comment]
@p455w0rd From what i can tell this isnt an issue on my end. Is it possible your returning more then the actual amount of energy that was received in IEnergyContaierItem#receiveEnergy ? 

I tried tracing your code but i couldn't figure out the energy conversion system.
