### ISSUE TITLE
Cant shift click craft in WCT when out of range of wireless access point

### ISSUE THREAD

**Issue by kuba12345** [p455w0rd/WirelessCraftingTerminal#40]
When i try to shift click craft in range of WAP (wireless ac point) it work normally
When i try to shift click craft out of range WAP (with infinity card in WCT) nothing happen
:/

**Comment by p455w0rd** [comment]
I'll get on this asap =D

**Comment by kuba12345** [comment]
Because i am playing Single there is easy way to solve it : edit config for infinity range,,

**Comment by p455w0rd** [comment]
no

**Comment by p455w0rd** [comment]
just be patient..I'll get a new version up today that will solve this along with another bug =D

**Comment by kuba12345** [comment]
I just added some numbers to range :D :D now i can go to ME everywhere :D

**Comment by kuba12345** [comment]
and can't use WCT in other dimensions it say: no energy in network or something like that :D

**Comment by p455w0rd** [comment]
ohh..you mean in AE2 config...this is still a bug as the wireless crafting terminal isn't supposed to be affected by ae2's range limits when the infinity booster card is installed..so I will still get a bugfix version up today

**Comment by kuba12345** [comment]
yes AE2 config :D some numbers and it is all :D
