### ISSUE TITLE
FPS Hit

### ISSUE THREAD

**Issue by Mattabase** [p455w0rd/WirelessCraftingTerminal#41]
So, what is the best way to chat with you, because using the latest version of the mod for Rv3 I get a HUGE fps hit when looking at other players.  

http://i.imgur.com/LIBRfgZ.png

**Comment by p455w0rd** [comment]
I replied to you on curse not 2 minutes after you posted

**Comment by Mattabase** [comment]
Ok, so tested with latest release, everything is great now. 

Also I was just posting in multiple locations because I was unsure of the best way to get a hold of you. 

Thanks for speedy fix. <3

**Comment by p455w0rd** [comment]
awesome =D

**Comment by SvEgiiVEteR** [comment]
I have the same problem
WirelessCraftingTerminal-1.7.10-rv2-1.8.3b.jar

**Comment by p455w0rd** [comment]
can you please post fml-client-lastest.log

**Comment by SvEgiiVEteR** [comment]
ок. 
https://gist.github.com/b252676b501e3d4ad476c8678e01404c
also drops fps if E press. as there is also the character seen

**Comment by p455w0rd** [comment]
well this only happens in rv2..I'll be able to devote my full attention to this in 30 mins or so to figure out why this is happening

**Comment by p455w0rd** [comment]
I've opened #42 for this issue

**Comment by nahoul** [comment]
i didn't want to create a new bug, seems to be the same. when i finally got the game working with Rev 3 file, i got a huge FPS hit. tried disabling WCT, didn't help. after 3 hours of trying i discovered that the first time i disabled WCT to test, it didn't get disabled. 

so in summary, the culprit is WCT, and guessing same issue as above.

updated AE to Rev build 6, "ae2-rv3-beta-6
WCT "1.7.10-rv3-1.8.4.1b"

is the above fixed in the most recent version?, am i using the wrong version?

**Comment by p455w0rd** [comment]
no and it is actually probably a different issue..i'll try to get a fix out yet tonight

**Comment by p455w0rd** [comment]
are you around?

**Comment by p455w0rd** [comment]
I'm not getting any FPS hit, but I need for you to test this version before I upload it to Curse. @nahoul

**Comment by p455w0rd** [comment]
I kinda worded that wrong i guess. I haven't experienced any FPS hit. I did change something that would probably be the culprit though. Basically, the version checker relies on the player tick event. I use this to add delay to the version check so I don't add to the player's internet traffic spike they get when loading and all the other mods do their version checks. It doesn't do anything after the initial check but it was still technically running and calculating an if statement which after initial version check always returns false. I've changed it now to completely unregister itself from the FML event bus after the version check.

**Comment by SteelShot** [comment]
Dunno if this is related, but adding WCT drops my fps by aroun 20-40%, removing it fps increases, I thought it was Pneumaticraft(recently added it) but it wasn't.

**Comment by p455w0rd** [comment]
i have a possibly fixed version...need someone to test it..hop on IRC: https://esper.net/publicirc.php channel= #p455w0rdCraft if you want to test out out the version i have..i have a pretty decent system and I'm not experiencing any fps hit, so if you gpu is only like 1 or 2gb or you're running on integrated gfx, you may experience this more easily than I can

**Comment by nahoul** [comment]
thanks for thew quick reply. i will check when i get back home. where did you upload the fix?

**Comment by p455w0rd** [comment]
it's on curse..steelshot was experiencing the same and hopped on IRC and tested

**Comment by nahoul** [comment]
hmm, didn't work for me. you are talking about 1.7.10-rv3-1.8.4.2b?
any mod you recommend i disable to check cause. binary check isn't that easy, disabling mods break the system, lots of cross dependencies :(. or is it a code related issue?

my FPS is still at 0-3 FPS :(

**Comment by nahoul** [comment]
hmm, didn't work for me. you are talking about 1.7.10-rv3-1.8.4.2b right?
any mod you recommend i disable to check cause. binary check isn't that easy, disabling mods break the system, lots of cross dependencies :(. or is it a code related issue?
i tested creating a new world. high FPS for the first few seconds, then plummeted to 0-3 
my FPS is still at 0-3 FPS :(

**Comment by p455w0rd** [comment]
I seriously have no clue what could be causing this other than a terribly low end PC...

**Comment by SvEgiiVEteR** [comment]
I can say that for me WirelessCraftingTerminal-1.7.10-rv2-1.8.4.2b.jar
works.
maybe the reason is another mod?
rv3 is not checked...

**Comment by SteelShot** [comment]
nahoul compile me a modpack zip, ill test it out,  we will se if it is hardware related :)

**Comment by nahoul** [comment]
my PC isn't low end, not by my standards :stuck_out_tongue: 
intel-i7 3.2 Gh
8 GB Ram
dedicated video ram, i think it was 3 GB

barely have anything installed, but i can remove steam and razor if needed :)

i installed a fresh Space astronomy installation, without any additional mods that my current instance have.

**Comment by p455w0rd** [comment]
ok...testing now with space astronomy and yeah that system should run this with ease

**Comment by SteelShot** [comment]
InGameInfoXML, Integrated Circuits were atleast the mods that lagged me for a while, until i removed em

**Comment by nahoul** [comment]
testing it without InGamInfoXML as suggested by steel shot

**Comment by p455w0rd** [comment]
yup..i'm getting it now with space astronomy..i'll look more into it

**Comment by nahoul** [comment]
do you mean you are getting the FPS hit too?

**Comment by p455w0rd** [comment]
yes and I do believe it's WCT.. weird though cuz it's only with this pack..I'm running i7 4790K (4GHz), 16GB ram, and 4GB vram, so it's def not pos PC lol

**Comment by p455w0rd** [comment]
I think I found the issue..testing test build now =]

**Comment by p455w0rd** [comment]
try this and tell me your results: http://p455w0rd.net/mc/WCT/WirelessCraftingTerminal-1.7.10-rv3-1.8.4.2b.jar

**Comment by nahoul** [comment]
yup you did it :)

thanks a lot. out of curiosity, was related to an existing mod in the pack. could help others who have the mod, but not the pack :)

**Comment by p455w0rd** [comment]
nope..derp on my end
