### ISSUE TITLE
FPS Hit in RV2

### ISSUE THREAD

**Issue by p455w0rd** [p455w0rd/WirelessCraftingTerminal#42]
looking into this

**Comment by p455w0rd** [comment]
So when I fixed #41 I forgot to carry those changes over to RV2...I'll have a new version up asap..should be within the hour.

**Comment by p455w0rd** [comment]
just waiting for Curse approval

**Comment by p455w0rd** [comment]
It is now available on Curse: http://minecraft.curseforge.com/projects/wireless-crafting-terminal

**Comment by SvEgiiVEteR** [comment]
all ok))
