### ISSUE TITLE
[Issue] Crash while crafting in "normal" crafting grid

### ISSUE THREAD

**Issue by accessdenied0** [p455w0rd/WirelessCraftingTerminal#5]
Hello @p455w0rd,

I recently installed you mod. It loaded all up without any issue, but soon I tried to craft something from IE in a "normal" crafting grid ("normal" because it was actually the Project E Philosopher Stone Grid > C ) I got this crash: http://pastebin.com/uraS0Dt1

hope for your help,

access_denied

**Comment by kurokuno** [comment]
can confirm crafting anything in a normal table of any kind seems to crash

**Comment by p455w0rd** [comment]
Sorry for leaving you guys in the dark. I have already addressed and fixed this. Trying to reproduce the NEI bug, once that is fixed, a new round of uploads will happen.

**Comment by Stalkstalks** [comment]
You aren't going to be happy with this... but I just got the same crash while trying to break a vibrant alloy ingot down into nuggets using the minecraft 2x2 inventory crafting grid, using version 1.5.4b.

**Comment by p455w0rd** [comment]
rv2 or rv3?

**Comment by p455w0rd** [comment]
Would much rather someone report it than to just have a bug I don't know about running wild in my code =D I've just reproduced the error in RV2, prolly same for RV3..this wilol be an easy fix. Just finished coding the new magnet filter options in RV3..gotta transfer those to RV3, then I'll work this bug out and then we should be good for an update

**Comment by Stalkstalks** [comment]
Rv2

**Comment by p455w0rd** [comment]
just went ahead and fixed it =D http://p455w0rd.net/mc/WCT/WirelessCraftingTerminal-1.7.10-rv2-1.5.6b.jar (This has the new filter options implemented too)

**Comment by Stalkstalks** [comment]
I appear to be able to use the inventory and crafting table grids without crashes on 1.5.6b. Thanks!
