### ISSUE TITLE
NEI Crafting broken

### ISSUE THREAD

**Issue by Halmex** [p455w0rd/WirelessCraftingTerminal#50]
If I try to Shift-click a NEI recipe in the Wireless Crafting Terminal and the recipe can use different kinds of material nothing happens. For example if the recipe can use MFR rubber and IC2 rubber.

**Comment by p455w0rd** [comment]
thanks for posting..I'll look into this now

**Comment by p455w0rd** [comment]
Same issue as #44 ...author of issue failed to mention that the shifting-clciking he was talking about was the NEI shift-clicking. Closing this issue and will be reporting progress via #44
