### ISSUE TITLE
Version Checker issue?

### ISSUE THREAD

**Issue by SteelShot** [p455w0rd/WirelessCraftingTerminal#51]
So i've just updated to 1.8.4b RV2, but it seems it says its the wrong version, checking in the in game mods list shows that its the latest one. I did rename the file to just WirelessCraftingTerminal.jar.

![8bcepfz](https://cloud.githubusercontent.com/assets/5291010/15515567/ae960836-21e6-11e6-8e02-8168c7475c81.png)

![bmxwvpb](https://cloud.githubusercontent.com/assets/5291010/15515488/656109e0-21e6-11e6-82cb-cfa9845ab06a.png)

**Comment by p455w0rd** [comment]
going ot be posting a hotfix soon, i'll take of this as well and the fix will be included. thanks for posting =D
