### ISSUE TITLE
server shutdown in single player when i right click the terminal for the first time

### ISSUE THREAD

**Issue by nahoul** [p455w0rd/WirelessCraftingTerminal#52]
Hello Again, i am back,
so i finally crafted the terminal, excited about using it. here is my observations
1- it's not charging like other items do, my powersuite usualy charges my wireless terminal and jetpack
2- when i right clicked to check it out at 0 energy, game crashed. but not the typical Java crash. it took me to the disconnected from server (local i guess since,  i am playing single player) and takes me back to the server connect screen.

i will test and find out if the same issue happens after i charge it :)

Cheers

**Comment by nahoul** [comment]
tested it charged. same. a fatal  error caused the connection to close :(

**Comment by nahoul** [comment]
this crash happens when the terminal is not linked. 

as soon s i linked it opened fine. heads up :)

**Comment by p455w0rd** [comment]
i'll look into it, thanks
