### ISSUE TITLE
Power Bar disappears when NEI is opened

### ISSUE THREAD

**Issue by nahoul** [p455w0rd/WirelessCraftingTerminal#53]
Hello,
just giving you input to perfect the mod

i noticed the energy bar of the WCT disappears when i open NEI. i would need to right click the WCT to open it, for the energy brar to show up. is this working as intended?

**Comment by p455w0rd** [comment]
if you are referring to the item in the list, yes, this is because it is full.

**Comment by p455w0rd** [comment]
just checked both versions and the durability bar displays as it should

**Comment by nahoul** [comment]
yup. that's it. i have a solar charger on power helmet, keeps it charged. if its designed to disappear when fully charged, then it's working as intended :)
