### ISSUE TITLE
Suggestion: search bar on top clickable area

### ISSUE THREAD

**Issue by nahoul** [p455w0rd/WirelessCraftingTerminal#54]
Hello,
i am not sure how simple this is.
in the AE2 wireless terminal, clicking the search bar is easy. it seems the area of effect when clicking means showing a cursor to type is large. in WCT, it's a smaller area. you need to be accurate when clicking the search box to get a cursor for typing 

is it worth changing :)

**Comment by p455w0rd** [comment]
i'll look into it..if this is true, i'll make the area a bit bigger..it really can't be off by more than 2 pixels though
