### ISSUE TITLE
I need some Help and i have a Idear what you can add to you mod

### ISSUE THREAD

**Issue by maginator** [p455w0rd/WirelessCraftingTerminal#55]
Hello, i have WCT installed on my Client and on my server i have the Version WTC 1.7.10 -rv3-1.8.4.3b and Applied Energistics rev3 -beta-5 if i right click on my WTC i left the game and there stand A Fatal error has occured ... I hpe you can help me. PS: I stalled it in FTB infinty 2.5.0 and i add some mods like ae2 stuff. and my Idear is to make a Wireless Multi Termial that you can with shift rightclick open a menue and you can put the Wireless termial in some other Me security Terminal and than you can chose on who me you wold have items. sry my English is not verry Perffect  im from Germany and scool English is not verry good but i hope you understand it

**Comment by p455w0rd** [comment]
No new features are being added to the 1.7.10 version of Wireless Crafting Terminal. I will keep this in mind when I begin developing it for 1.9 AE2

**Comment by maginator** [comment]
ok and why i kicked from server if i right click my Wireless Crafting Termial?

**Comment by p455w0rd** [comment]
it's not linked already reported in #52 - fix will be in next update

**Comment by maginator** [comment]
its say it is Linked

**Comment by p455w0rd** [comment]
what pack? i'll look into it

**Comment by maginator** [comment]
FTB Infinty

**Comment by p455w0rd** [comment]
evolved or skyblock?

**Comment by maginator** [comment]
Evolved, Recomanded

**Comment by p455w0rd** [comment]
on esper you have to PM me in order for me to know that you need my attention

**Comment by p455w0rd** [comment]
ok..i'll try to replicate the bug and fix it

**Comment by maginator** [comment]
ok i dont no but i have installed Ae2 stuff

**Comment by p455w0rd** [comment]
it is still the same problem from #52 - closing this issue
