### ISSUE TITLE
Suggestion: Fluid and Gas terminal

### ISSUE THREAD

**Issue by nahoul** [p455w0rd/WirelessCraftingTerminal#56]
Hello,
in Extra Cells, you can add flid and gas modules to the wireless terminal. shift right clicking the terminal in the air switches view from fluid to items to gas. 

is it possible to implement? just an addition i thought i would suggest :)

**Comment by p455w0rd** [comment]
I don't want to step on toes. I have begun implementing an API and if @DrummerMC wishes to implement the Wireless Crafting Terminal as an additional option to the EC2 Universal Terminal, then I would be open to fully implementing the API. This would be the _ONLY_ new feature I would be willing to implement for the 1.7.10 version of the terminal. This is actually the sole reason behind starting the API. I was going to contact him myself, but 1.9 became a thing and I decided it would be best to wait. At the moment, WCT is hideous code-wise. I have learned a lot and in the 1.9 version I will essentially be recoding from the ground up to make it easier to work with for other mod authors. If he wishes to add WCT, I would make it identical to adding the vanilla AE2 Wireless Access Terminal. Therefore it would only be ~3 lines of code. Up to him =)

**Comment by DrummerMC** [comment]
I can implement it in ec2

**Comment by p455w0rd** [comment]
Cool. Let me clear out the rest of this issues list and I'll fully implement the API. Cool is I just PM you on IRC when it's ready?

**Comment by p455w0rd** [comment]
Just waiting to hear back from @DrummerMC on IRC =]

**Comment by p455w0rd** [comment]
reopening since this is about to become a thing :D - just so I can reference/close via push

**Comment by p455w0rd** [comment]
just waiting to hear back from @DrummerMC :)

**Comment by operinko** [comment]
The Infinite Range upgrade does not apply to the added Fluid&Gas modules, at least. Any plans on making that work as well?
