### ISSUE TITLE
Client-side crash when using the wct

### ISSUE THREAD

**Issue by condensedapple** [p455w0rd/WirelessCraftingTerminal#57]
Updated my server to latest rv3 of WCT, and now I crash to title screen when trying to open the WCT
Relevant code in client-log: https://gist.github.com/condensedapple/196ffdb8adab02c46e5d82b1377e1298
It worked before updating and it is linked, and it does not crash in singleplayer. In the server console no error message appears.
I am reporting this as I am not sure if this is related to #55 and #52.

**Comment by p455w0rd** [comment]
it is..i already have it fixed..just working out other stuff and then i'll upload it

**Comment by condensedapple** [comment]
cant even report a bug without you having fixed it already ;)
im curious: why doesnt it crash in SP for me, but it is for other people?

**Comment by p455w0rd** [comment]
i have no idea..I really don't even know why it's doing it to be honest, but I am good at making hacky workarounds so..anyway..it's on curse

**Comment by p455w0rd** [comment]
=D

**Comment by condensedapple** [comment]
NICE
