### ISSUE TITLE
WCT disappears from inventory after crash.

### ISSUE THREAD

**Issue by nahoul** [p455w0rd/WirelessCraftingTerminal#59]
This happened twice so far. i lost 2 terminals along with the infinity card and magnet card they held.

i am unable to tell you what exactly happened. but i move the terminal to my inventory from the hot bar, game crashes. i log back in, and it's gone.  all i can tell you for now, it randomly happens when you move the WCT to inventory. crash and loss

i will try replicate the issue, although it's an expensive issue to replicate out of creative.

**Comment by p455w0rd** [comment]
any news on this as I am unable to replicate

**Comment by p455w0rd** [comment]
will be uploading new update tonight..if i do not hear from you I will assume this issue is closed since I cannot reproduce this bug

**Comment by nahoul** [comment]
sorry i was out of town on business. i was unable to reproduce the issue. good move closing it for now :P

**Comment by p455w0rd** [comment]
whatever it was, it was probably fixed in latest update...there was a MAJOR bug that I fixed that caused client crashes..but only to the main screen
