### ISSUE TITLE
Unable to craft with rv3-1.8.6.1b

### ISSUE THREAD

**Issue by FnordMan** [p455w0rd/WirelessCraftingTerminal#62]
Unfortunately I don't have a lot of info other than I can't craft a thing. I click on the item to be crafted and the terminal window immediately closes. 

Removing the mod makes it so I can craft things again. 

I also have Extra Cells 2 installed as far as AE2 mods go.

**Comment by p455w0rd** [comment]
alright i'll look into this and get a fix out asap

**Comment by p455w0rd** [comment]
can you please check which ae2 version you are using (the filename would be great) along with the WCT version and post them here please

**Comment by p455w0rd** [comment]
also whether or not you're playing on a server or offline

**Comment by FnordMan** [comment]
AE2 rv3-beta-6

Happened with both a server and single player. (Same world, shut the server down and copied it over)

Also discovered I have the ae2stuff mod installed. 

Config wise I did turn easy mod on.

**Comment by SvEgiiVEteR** [comment]
https://gist.github.com/11abcc93ff75b5c69593175251691747
It seems to have the same problem
simply throws with the SSP without Crush

**Comment by p455w0rd** [comment]
yeah I don't know why tf this is happening..works fine for me in SSP, but same in SMP..just gotta rework the system.. getActionableNode() retuns the closest WAP on the netowrk your wireless term is linked to..technically should be working..I even reverted code on my end..dunno..i'll have it fixed by morning

**Comment by FnordMan** [comment]
Forgot to mention: I've got channels disabled in AE2's config. 

I don't even have anything wireless deployed yet, I only recently started building an AE2 system. 

I can provide a copy of the world and mod list if you need.

**Comment by p455w0rd** [comment]
won't be necessary..I've found the bug and I'm working on it now

**Comment by p455w0rd** [comment]
just an update..i've fixed it on RV3, working on RV2..as soon as this is working, I'll get the new build up on Curse

**Comment by p455w0rd** [comment]
btw I'm testing in all environments, so there should be zero issues

**Comment by p455w0rd** [comment]
1.8.6.2 is live on Curse..NEI shift-clicking should be functional as well as all other functionality..only time will tell

**Comment by SvEgiiVEteR** [comment]
Thank you. all OK

**Comment by FnordMan** [comment]
Just tried 1.8.6.2b, still doe the same thing, click on something to craft it and the window closes. Click the hammer and it kicks you out of the game or server. (single / multiplayer)

**Comment by p455w0rd** [comment]
forgot about that...i will open a new issue for this..shouldn't be hard to fix..basically same fixes I made in the latest version, but to a different file
