### ISSUE TITLE
autocrafting crashes in 1.8.6.2b

### ISSUE THREAD

**Issue by p455w0rd** [p455w0rd/WirelessCraftingTerminal#63]
referred by @FnordMan on #62 ..investigating

**Comment by p455w0rd** [comment]
I will use this post for updating results as I test
=====================================
RV3 tested in server environment - works fine

**Comment by p455w0rd** [comment]
So unless you can provide me with more info, I have to mark this as invalid as everything works on my end. I will leave this issue open in hopes that someone with some actual replicatable info will respond.

**Comment by FnordMan** [comment]
Did you try it in another dimension? I've got my AE2 setup running in an RFTools dimensions
[modlist.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/296645/modlist.txt)
/\ modlist

Also: crafting doesn't work at all in any wired terminal, same with the crafting status thing. Loaded up the test world and discovered that any wireless terminal does in fact work normally. It's definitely something you're doing as when I remove this mod everything behaves normally.

**Comment by p455w0rd** [comment]
running tests with AE2 RV3 Beta 6 now..I have been developing using RV3 Beta 5, but perhaps there was something changed that would cause this. I'll post results as I get them

**Comment by p455w0rd** [comment]
Well this is a gif recorded just now, using the RV3 modlist from above, but using AE2 RV3 Beta 6 instead: https://gfycat.com/GlassTenseFawn I need something to go by (a place to start looking). If you have no crash report, then fml-client-latest.log (from /logs directory) will work. If you have access to the server, fml-server-latest.log would help as well. Make sure to force the 'crash' to happen before copying the contents of either of these files as a new version of each of these files is generated every time you launch the client/server. Use a service like pastebin and post the link(s) here for me to review. This has to be a conflict with another mod as everything is working flawlessly for me. I'm dedicated to having my mod work in most situations (Though there are a few that I will not touch, like MystCraft incompatibility). I just need input. The sooner you can provide what I need, the sooner I can get a fix out for the bug, so check back here often if you are able to.

**Comment by FnordMan** [comment]
Try it with a wired crafting or ME terminal. As I stated above it works fine with either wireless terminal but fails on the wired ones. 

Attached the forge log, there's an error in there I got when I clicked crafting status on a "normal" (wired ) terminal
[fml-client-latest.zip](https://github.com/p455w0rd/WirelessCraftingTerminal/files/296702/fml-client-latest.zip)
\/ snipped out the relevant bits I saw in the console log after it booted me out of the ssp world. 
[borkbork.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/296703/borkbork.txt)

**Comment by p455w0rd** [comment]
I will inspect that log file, but here's what I get using a wired terminal: https://gfycat.com/SafeGreenBaleenwhale Same mods/specs as listed above. Just so you know, I'm not claiming it isn't my mod. It appears that it has to be WCT from what you've said. But my mod doesn't in any way alter the AE2 code. There's no ASM/reflection. So I'm kind of stumped as to why this is happening. It has to be somehow the way my mod is interacting with another mod. I'll keep digging.

**Comment by FnordMan** [comment]
That's really strange, i'm "special" then...

**Comment by p455w0rd** [comment]
What launcher are you using?

**Comment by FnordMan** [comment]
Plain vanilla MC launcher w/ forge 1614

**Comment by p455w0rd** [comment]
Can you zip those mods up so I can install them to try to get to the bottom of this? Something is modifying the AE2 class that does the handling for that GUI. We'll get this. It would really help if you could hop on IRC. https://esper.net/publicirc.php channel is #p455w0rdCraft

**Comment by p455w0rd** [comment]
we found out this issue was a one-off thing due to modifying the modlist of an already created world
