### ISSUE TITLE
Lag and loud noise when picking up massive amunt of items with magnetic. ALso, Magnetic card stopped picking up items after a while

### ISSUE THREAD

**Issue by nahoul** [p455w0rd/WirelessCraftingTerminal#65]
Hello,
i can't replicate the issue, but this could be connected to another issue, 

if the termina gets an influx of a large amount of items on the ground, example, massiving mining with a Vajra or picking up my items after dying. the first few milliseconds of the picking up sound gets stuck in a loop as if, it's picking up thousands of items at once. only way out of it is to log out then log back in.

i believe as soon as this loud noise/FPS hit happens, magnetic card break.

**Comment by p455w0rd** [comment]
I've had this happen too, just not yet with the WCT. The part of the code that does the picking up is based on jotato's magnet from quantumflux and I've had it happen when using vein miner..the only real way to fix this would be to change the way the magnet card picks up items which would mean a slower process..I will look into figuring something out.

**Comment by p455w0rd** [comment]
yeah..i will leave the magnet as-is for now..in the 1.9.4 I'll use a different method for the magnet, but this works well enough for now
