### ISSUE TITLE
Unlinking and Trash doesn't work

### ISSUE THREAD

**Issue by chezpaul** [p455w0rd/WirelessCraftingTerminal#68]
I'm having several issues with the terminal.
First off, thanks for creating it. Great idea.
Now to the problems.

It often resets itself when I log back in the next day. I will find the terminal in the charging station but it won't be linked anymore and the wireless booster card is gone. So I have to recreate a card and re link.
This has happened three times already in 5 days. So it's not every time.

I'm also having trash problems. When I drag items to trash and empty trash, they will disappear but after 3 or 4 items, all items re appear in my possession.

Otherwise great work when it works.

Oh, I'l also had it stop working mid game and I then need to re link and new booster card.

I'm running Forge 1614. on KCauldron 1614.201. Using your latest version and AE2 rev3 beta6

**Comment by p455w0rd** [comment]
I can't reproduce this. It's more than likely something on the server's end. I just tested the trash and it works fine. I do not support "KCauldron, Bukkit, Spigot, Spiget" or any other trash that uses a "plugins" based system. I don't know why this would happen nor do I have any desire to waste any time hunting the issue down. I'll leave the issue open for anyone who experiences the same so they can see my POV on the matter.

**Comment by chezpaul** [comment]
Cool.
Just for info, I've been doing this for 2 years now. I always work with all latest mods and plugins. And my problems can always be reproduced in Forge and have never been because of KCauldron. 
Everyone is always trying their eyes because of Cauldron but it's never the culprit. 
I promise. ;-)

Thanks for leaving this open.

**Comment by p455w0rd** [comment]
Okay..to confirm that it's my mod, set up a new local server using only forge with AE2 & WCT. I guarantee it will work.
