### ISSUE TITLE
Crash When clicking the Crafting Status in AE2 crafting terminal

### ISSUE THREAD

**Issue by eaves12** [p455w0rd/WirelessCraftingTerminal#69]
Bug 1: Game crashes when clicking the crafting Status in AE2 Crafting terminal window.
Bug 2: When clicking any autocraftable item in the AE2 Crafting Terminal window, the terminal just closes ( just like when you hit ESC)

WCT Version : tried WirelessCraftingTerminal-1.7.10-rv3-1.8.7b AND WirelessCraftingTerminal-1.7.10-rv3-1.8.7b1

bugs occur on easy mode and hard mode.

AE2 Version : appliedenergistics2-rv3-beta-5

Extracells2 Version : ExtraCells-1.7.10-2.3.9b188

AE2 Stuff is also installed : ae2stuff-rv3-0.5.1.9-mc1.7.10

Pack : FTB Infinity 2.5.0
Forge Version : 10.13.4.1614
Launcher used : Curse.

Removing WCT solves the issue.

Update: autocrafting works when I click on the item using the normal AE2 Wireless terminal AND the WTC wireless crafting terminal, the bug just occurs on the normal crafting terminal

**Comment by p455w0rd** [comment]
My code does not in any way modify anything outside of the mod. Therefore it simply isn't possible that my mod is affecting default AE2 behavior. This has happened before and was the result of a corrupt world save. I just tested and it works perfectly fine on my end.

**Comment by p455w0rd** [comment]
To test..create a new instance that only uses WCT/AE2..it will work
