### ISSUE TITLE
Infinity booster card keeps falling

### ISSUE THREAD

**Issue by eaves12** [p455w0rd/WirelessCraftingTerminal#70]
When ever I open the WCT and scroll down the items using the mouse (the mouse must be hovering ON the items in the terminal) the infinity booster card gets stuck on the cursor, as if I clicked on it, and it keeps falling out of the WCT for no reason.

Version : WirelessCraftingTerminal-1.7.10-rv3-1.8.7b1
Forge : 10.13.4.1614

**Comment by p455w0rd** [comment]
looking into it

**Comment by p455w0rd** [comment]
I can't reproduce the issue. I've recorded a gif here: http://p455w0rd.net/mc/wct_scrolling.gif So, I would guess that it's either your mouse or another mod (maybe MouseTweaks) interfering

**Comment by eaves12** [comment]
it was Indeed Mouse tweaks, I disabled the WheelTweak option in mouse tweak's config file and the problem disappeared.
