### ISSUE TITLE
Crafting GUI not showing up with WCT installed

### ISSUE THREAD

**Issue by JasonMcRay** [p455w0rd/WirelessCraftingTerminal#72]
Relevance: #64 

It happens from time to time. Wierd is, that I have 2 terminals in my base. One further away - this one is causing me problems and headache. And second one is near my autocrafting place. Sometimes I am unable to issue autocrafting from the further terminal, when I run to the closer one, I can craft just fine. Sometimes it works just fine, sometimes it is not working.

I really dont know what to blame, where could be a problem or how to reliably recreate it.... it just happens.

AE2: rv3 beta 6
WCT: 1.8.6.2b
Forge: 1614
Pack: InfiTech 2

**Comment by p455w0rd** [comment]
hmmm..I have to be to work in 2 hrs, but after I get off I'll see if I can replicate it. This is very peculiar, but I do know where to look, so I'll fiddle with the code and see if I can come up with anything reliably reproducible. Thanks for the report!

**Comment by p455w0rd** [comment]
I just watched https://www.youtube.com/watch?v=DXVb7k9Ssu8 - I will assume this is you and the issue you're describing? WCT doesn't modify anything default AE2 does and therefore wouldn't affect the default terminals. I will go through closed issues, because something very similar has been reported before and I believe we were able to pin down the culprit.

**Comment by p455w0rd** [comment]
Did you add WCT to the mod list before generating the World?Check https://github.com/p455w0rd/WirelessCraftingTerminal/issues/63#issuecomment-223466068

**Comment by JasonMcRay** [comment]
WCT has been added after the world has been generated.

**Comment by JasonMcRay** [comment]
I just want to confirm... I have disabled WCT in my instance and for couple days I had no issue with not being able to issue crafting from any of my terminals.

**Comment by p455w0rd** [comment]
yeah it's something to do with adding WCT to an already created world...so I dunno..I work a full time job + I'm dev'ing on a couple 1.9.4/1.10 projects and I have web work on the side which leaves very little time for me to figure this out..the solution is to only use WCT on a new world/server instance..I do plan to look into it when I get time, but currently, my schedule full...maybe @DrummerMC wouldn't mind looking into it? ;)
