### ISSUE TITLE
Magnet card on server causes lag.

### ISSUE THREAD

**Issue by wiloxe** [p455w0rd/WirelessCraftingTerminal#75]
Hello. So i'm using an modpack and i've added few mods to this modpack where me and my friends play on, I just got myself the crafting terminal with the magnet card but when i enabled it and put it into the wireless terminal that's when the console outputed a wall of text and in game it's like i'm picking up millions of items in a loop sound. And the server starts to lag and is unplayable (Untill upgrade is removed)

Error Code: http://pastebin.com/VmNzq5E8
Modlist: http://pastebin.com/fXGp53F3

Tell me if i missed anything.
[Haven't tested on singleplayer]
Many Thanks -Wiloxe

EDIT: Fixed some missleading info.

**Comment by p455w0rd** [comment]
I'll look into this when I get a moment. From a brief read, it looks like it has to do with right-clicking. This is _not_ console spam. If you have a copy of the console spam you speak of, it would probably help. Thanks for the report.

**Comment by wiloxe** [comment]
Sorry about that. It was late that time and i did not check the entire console and i thought it was a flood first but i was wrong. I'll include the entire log file of me only starting the server logging on and then using the magnet card. 
Full Log:
[fml-server-latest.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/462148/fml-server-latest.txt)
