### ISSUE TITLE
[ 1.10.2] Update Request

### ISSUE THREAD

**Issue by Morpheus1101** [p455w0rd/WirelessCraftingTerminal#76]
With AE2 rv4 floating around, id kill to have this as a thing now, so how bout it by weekend? k tnxs :P

**Comment by EPIICTHUNDERCAT** [comment]
UPDATE IT ! lazy

**Comment by dshadowwolf** [comment]
Please don't mis-use issue trackers like this, people. It's annoying to the programmer(s) who rely on issue trackers for making what they work on as good as it can be.

It's also seriously bad manners. You're basically demanding something from the programmer/modder - someone who is already providing the mod for you free of charge.

**Comment by p455w0rd** [comment]
@dshadowwolf these guys are just my homies talkin shit lol..you could join our discord server at http://discord.mcmoddev.com/ if you'd like to join us ;) on a more relevant note...I have definitely been work on this..a lot..just a lot to do and I want it to be better, so it's taking a while..soon enough :) I'll be testing it on our dev server before any official CF releaes...

**Comment by dshadowwolf** [comment]
and... Gah! Okay, My bad :)

**Comment by DeadSix27** [comment]
Any update? (As in, news)

**Comment by p455w0rd** [comment]
i have done a good deal of work on updating..this just isn't high priority for me atm..the api is horrible (not the code, but what the api gives access to)..hasn't changed as far as accessing the crafting gui..i will probably finish the update..but i don't know when i'll have time to

**Comment by DeadSix27** [comment]
np, was just wondering (when I saw the refined storage one popup on curseforge)
on the other hand didn't shartlle or yueh mention to talk to him if one has ideas for API improvements?
