### ISSUE TITLE
Can't use ME Crafting Terminal in The Nether after installing WCT

### ISSUE THREAD

**Issue by kman3107** [p455w0rd/WirelessCraftingTerminal#77]
I have my AE2 Wither farm in The Nether, I've been using it daily, but after I installed the Wireless Crafting Terminal mod I can't use the auto-crafting and thus making the entire thing useless.  
If I click on the item I want to craft like the picture under, it just closes the Crafting Terminal. 
![vlcsnap-error245](https://cloud.githubusercontent.com/assets/10728652/19616639/e98e8dc0-9818-11e6-967a-9b6811d55784.png)

And if I click on Crafting Status like here 
![vlcsnap-error546](https://cloud.githubusercontent.com/assets/10728652/19616644/fcbb3aec-9818-11e6-809d-04c445b52f74.png)
Then this happens 
![vlcsnap-error665](https://cloud.githubusercontent.com/assets/10728652/19616645/0904b9c2-9819-11e6-83c2-0b2e780c5ce7.png)

I am running FTB Infinity Evolved 2.6.0 (Curse App). The only modification I have done to the pack is adding the Wireless Crafting Terminal mod (WirelessCraftingTerminal-1.7.10-rv3-1.8.7.1b.jar)

PS: I deleted WCT and tested again just to make sure. As you can see in the picture below it works fine without WCT 
![minecraft 1 7 10 22 10 2016 05 39 41](https://cloud.githubusercontent.com/assets/10728652/19616691/63103b5c-981a-11e6-867a-bc8221d69626.png)

**Comment by p455w0rd** [comment]
i will look into it

**Comment by p455w0rd** [comment]
no longer supporting 1.7.10..sorry
