### ISSUE TITLE
Item Magnet Causes Crashes

### ISSUE THREAD

**Issue by Wealthyturtle** [p455w0rd/WirelessCraftingTerminal#79]
AE2 Version: RV2-Stable-10
Wireless Crafting Terminal Version: RV2-1.8.7B

The User Crashes Without Having an Item Magnet in His Inventory

Crash Report: http://pastebin.com/7gc7kXxJ

(Reported on Behalf of Shadow_Fade)

**Comment by p455w0rd** [comment]
Straight from [Curse Forge](https://minecraft.curseforge.com/projects/wireless-crafting-terminal):
![img](https://puu.sh/spdf1/93790cbf24.png)
