### ISSUE TITLE
[Feature Request]  Infinity Booster Cart drop rate config option

### ISSUE THREAD

**Issue by condensedapple** [p455w0rd/WirelessCraftingTerminal#8]
First of all, a little config option to control the drop rate of the infinity booster card.
More ideas:

- seperate drop rates for wither & dragon (wither is "automated" easier)
- drop rates for the DraconicEvolution-Dragon (seems reasonable)
- API for other mods to enable their authors to add the infinity booster card as a drop of boss mobs (dunno whether this is included in your existent API)

**Comment by p455w0rd** [comment]
As far as the API thing. That isn't an API issue. Basically if another mod author wants to add the item, they just make their mod dependant on my mod, then make their mod load after mine to ensure the item has been registered, then adjust the drop. No API interaction needed. The API is primarly for opening the WCT without have to do all the crazy checks. It is, however, broken atm. It's on my TODO list. Will add drop rate option soon. Also, I will see about adding DE integration to add it to the DE dragon..shouldn't be hard. Also, the wither automation is why I made the drop a bit more rare. The item itself has a max stack size of 1, so if you were to, say, collect wither drops and throw them into your AE system, until you have a way of disposing item, this would clog your system. I made the drop rate high to kinda avoid this as well as make it difficult as the Infinity Booster Card is extremely OP. For now I think I'll make so the Dragon drops it 100% of the time and add the config option for withers.

**Comment by condensedapple** [comment]
Thx for the explanation, good idea.

**Comment by p455w0rd** [comment]
Just implemented this ;) No DE support and after thinking about it, I think that getting it from the dragon 100% of the time should suffice. In a SMP environment this would mean the first person to kill the dragon gets the booster card..kind of a bonus..everyone else will have to work a bit harder to get it. So anyway, it'll be included in next update.

**Comment by p455w0rd** [comment]
Fixed awaiting curse to approve new versions. Follow me on Twitter @TheRealp455w0rd for real-time updates
