### ISSUE TITLE
Magnet Card visal shift klick bug

### ISSUE THREAD

**Issue by Dream-Master** [p455w0rd/WirelessCraftingTerminal#80]
![image](https://cloud.githubusercontent.com/assets/2970688/20643860/12a2f580-b424-11e6-9b22-3073a3307ff8.png)

Using lastest ersion rv3

If not using shift clicks it looks normal.
![image](https://cloud.githubusercontent.com/assets/2970688/20643864/3c5b8aae-b424-11e6-8718-ce34a5fcab86.png)

**Comment by p455w0rd** [comment]
I haven't coded in 1.7.10 for something like 6 months now..tho I haven't made a formal announcement, I am no longer supporting 1.7.10 mods. 1.10.2 is stable and I am actively working on a number of projects for it..I don't know what's causing this, but I simply do not have the time to regress.. You're more than welcome to join https://discord.gg/wUHHBVA to see what myself and many others are working on for 1.10.2 and 1.11 ..WCT for 1.10.2 is on the todo list, just not high priority atm..it will be coming, just when I have time... I currently run a communty, and actively work on ~6 projects along with helping members learn to mod..this takes 110% of my time
