### ISSUE TITLE
[Visual] Purple Cape?

### ISSUE THREAD

**Issue by SteelShot** [p455w0rd/WirelessCraftingTerminal#84]
After updating the Mod to 1.7.10-rv3-1.8.7.2b and the latest Lib 1.7.10-1.0.3, i have noticed that my cape is purple.

[IMG]http://i.imgur.com/i3iYr0x.png[/IMG]

I'am not sure if there a another mod that added a cape or something, but this is the only mod, I know that gives me a cape :)

Mod List:
https://paste.ee/p/Kj5TJ
https://modlister.com/user/SteelShot

**Comment by p455w0rd** [comment]
can u please join me on discord? https://discord.gg/9J7yhUP
