### ISSUE TITLE
[1.7.10] Cannot Shift-Left-Click in Recipes (NEI Feature) in Other Dimensions Except for the Overworld using AE2WCT Terminals

### ISSUE THREAD

**Issue by Wealthyturtle** [p455w0rd/WirelessCraftingTerminal#89]
Basically, You Cannot Shift-Left-Click in Recipes (Which is an NEI Feature) in Other Dimensions Except for the Overworld, when Using AE2WCT Wireless Crafting Terminals.

Video: [https://www.youtube.com/watch?v=d4_ajxc33Hk&feature=youtu.be](https://www.youtube.com/watch?v=d4_ajxc33Hk&feature=youtu.be)

**Comment by p455w0rd** [comment]
https://puu.sh/tq2A3/180e889429.gif - working fine here...i pushed the final update for the 1.7.10 branch earlier..
