### ISSUE TITLE
Terminal not working in other dimensions

### ISSUE THREAD

**Issue by ThisIsTheGitHubAccount4MUHAKL** [p455w0rd/WirelessCraftingTerminal#90]
Mc 1.10.2 , WirelessCraftingTerminal-1.10.2-0.0.4.jar, forge-1.10.2-12.18.3.2209

wireless term is working well in OVERWORLD , using booster card
Not working ( message "NO POWER") when in 
- Nether / END
- RFtools dimensions
- Advanced rocketry dimensions 

It works a couple of times , until power of terminal goes below 99,94 % 

btw: booster card drops only from DRAGON, killed 20 Withers-no drop 
1 dragon - 1 drop

best regards

**Comment by p455w0rd** [comment]
booster card only has 5% chance from withers..took me over 80 kills last i tested..i'll look into that..I have WCT being tested for me and I've tested as well and it definitely works for me in other dims with only AE2, WCT, p455w0rds Lib, and EnderIO

**Comment by ThisIsTheGitHubAccount4MUHAKL** [comment]
It's working now, with IC2 chunk loader.
I thought, its working like the the quantum link chamber, without chunk loader

so, it was my bug

**Comment by p455w0rd** [comment]
I'm going to keep this issue open..I have a fix in the works for situations like this implemented in p455w0rd's Library..i'll do some testing soon..if all goes well, chunkloading won't be an issue. Thanks tho...glad you got it figured out :)

**Comment by p455w0rd** [comment]
Just tested :) In the next 1.10.2 WCT update, when you place an AE2 controller in world, it will also serve as a single chunk chunk loader, which will solve this problem :)
