### ISSUE TITLE
[1.10.2] Crash when using scroll-wheel in WCT GUI

### ISSUE THREAD

**Issue by SnowShock35** [p455w0rd/WirelessCraftingTerminal#91]
### Issue Information

- Minecraft 1.10.2
- Minecraft Forge 12.18.3.2221
- p455w0rdlib 1.0.9
- WCT 0.0.5

### Issue Description

When using the scroll wheel feature that's available in the regular AE terminals within your WCT the game crashes to desktop 

### Issue Media

[Crash Report](http://pastebin.com/py0mcdpN)

**Comment by p455w0rd** [comment]
Thanks for the reports :) I'll have it up on Curse asap
