### ISSUE TITLE
[1.10.2] [Suggestion] Configuration Option for Chunk-Loading Controllers

### ISSUE THREAD

**Issue by SnowShock35** [p455w0rd/WirelessCraftingTerminal#93]
In the latest version of WCT you added a force chunk load on every me controller that's placed. I understand the reasoning for adding this however on behalf of server owners and modpack makers, not having it configurable is a bad call imo. It will most likely turn a few heads away because of this which is never good because users will miss out on using the mod. 

You could also have it give an error in chat when a player tries to use it cross-dimensionally and the chunk where the controller is isn't loaded and therefore could avoid repetitive reports. Not sure how feasible that is but just another suggestion.

**Comment by p455w0rd** [comment]
Though your reasoning is hardly on point, I agree that it should be configurable and will add configs and get an update out asap which fixes all current bugs and has configs.
