### ISSUE TITLE
Wireless Term Magnet Lag's server to the point of crashing when picking up alot of item's 

### ISSUE THREAD

**Issue by Mylezz** [p455w0rd/WirelessCraftingTerminal#97]
_I was testing how well the magnet worked and i drooped around 15k oak saplings and i turned on the magnet and the server lagged out and needed to be stooped and restarted._

Here is the full log
[latest - Copy.txt](https://github.com/p455w0rd/WirelessCraftingTerminal/files/730699/latest.-.Copy.txt)

**Comment by p455w0rd** [comment]
shouldn't be happening in latest 1.7.10 version on Curse..if it is, I don't know what to telll ya..don't drop 15k entities in world...that's just dumb
