### ISSUE TITLE
Wireless Crafting Terminal + Additinal Loot Table = This?

### ISSUE THREAD

**Issue by wiloxe** [p455w0rd/WirelessCraftingTerminal#98]
So it's me again with kinda similar issue from last time but I'm not entirely sure if this is an ALT issue or WCT issue. But to be on the safe side I'm gonna post this here since it only happens with the WCT

So if we install the magnet card and set it to put any extra items in inventory you get this:
Video: https://www.youtube.com/watch?v=k76glddhkkM
Won't be able to do pastebin. 
(You have exceeded the maximum paste size of 512 kilobytes per paste. PRO users don't have this limit!)
Log: https://www.dropbox.com/s/eghpxxdv880v9cq/fml-server-latest.log?dl=0
With any other magnet mod for an example like Botania we don't get this error.
And yes it works fine if we set the card to leave extra items on the ground.

(If you have read the log when I first joined I attempted to reproduce this by myself however instead of getting the flood you saw in the video I get some other errors instead.

**Comment by p455w0rd** [comment]
Checking into it, but just FYI, there is always gist.github.com for logs :)

**Comment by p455w0rd** [comment]
does this occur in latest version?
